/*
 * morgana.h
 *
 *  Created on: Mar 28, 2018
 *      Author: dominik
 */

#ifndef INCLUDE_C_TILE_FATA_MORGANA_H_
#define INCLUDE_C_TILE_FATA_MORGANA_H_

#include "constants/fata_morgana.h"

#define DESERT_MAP 21
#define DESERT_BANK 3

void do_fata_morgana();

typedef struct morgana_anim {
    u16 blocks[4];
    u16 walkfield;
} morgana_anim;

extern const morgana_anim morgana_anims[NUM_FATA_MORGANA_BLOCKS];

/**
 * Gets the fata morgana animation by a block idx
 * @param block the block_idx to get the fata morgana of
 * @return the idx of the fata morgana animation
 */
int fata_morgana_index_by_block(u16 block);

// LUT for fata morgana blocks: Generated by tools/fata_morgana_lut.py
extern const u16 fata_morgana_blocks[][3];
// LUT for fata morgana blocks size: Generated by tools/fata_morgana_lut.py
extern const int fata_morgana_blocks_cnt[1];

#endif /* INCLUDE_C_TILE_FATA_MORGANA_H_ */
