.global ability_descriptions
        
.align 4
ability_descriptions:
    .word str_ability_descr_0x0
    .word str_ability_descr_0x1
    .word str_ability_descr_0x2
    .word str_ability_descr_0x3
    .word str_ability_descr_0x4
    .word str_ability_descr_0x5
    .word str_ability_descr_0x6
    .word str_ability_descr_0x7
    .word str_ability_descr_0x8
    .word str_ability_descr_0x9
    .word str_ability_descr_0xa
    .word str_ability_descr_0xb
    .word str_ability_descr_0xc
    .word str_ability_descr_0xd
    .word str_ability_descr_0xe
    .word str_ability_descr_0xf
    .word str_ability_descr_0x10
    .word str_ability_descr_0x11
    .word str_ability_descr_0x12
    .word str_ability_descr_0x13
    .word str_ability_descr_0x14
    .word str_ability_descr_0x15
    .word str_ability_descr_0x16
    .word str_ability_descr_0x17
    .word str_ability_descr_0x18
    .word str_ability_descr_0x19
    .word str_ability_descr_0x1a
    .word str_ability_descr_0x1b
    .word str_ability_descr_0x1c
    .word str_ability_descr_0x1d
    .word str_ability_descr_0x1e
    .word str_ability_descr_0x1f
    .word str_ability_descr_0x20
    .word str_ability_descr_0x21
    .word str_ability_descr_0x22
    .word str_ability_descr_0x23
    .word str_ability_descr_0x24
    .word str_ability_descr_0x25
    .word str_ability_descr_0x26
    .word str_ability_descr_0x27
    .word str_ability_descr_0x28
    .word str_ability_descr_0x29
    .word str_ability_descr_0x2a
    .word str_ability_descr_0x2b
    .word str_ability_descr_0x2c
    .word str_ability_descr_0x2d
    .word str_ability_descr_0x2e
    .word str_ability_descr_0x2f
    .word str_ability_descr_0x30
    .word str_ability_descr_0x31
    .word str_ability_descr_0x32
    .word str_ability_descr_0x33
    .word str_ability_descr_0x34
    .word str_ability_descr_0x35
    .word str_ability_descr_0x36
    .word str_ability_descr_0x37
    .word str_ability_descr_0x38
    .word str_ability_descr_0x39
    .word str_ability_descr_0x3a
    .word str_ability_descr_0x3b
    .word str_ability_descr_0x3c
    .word str_ability_descr_0x3d
    .word str_ability_descr_0x3e
    .word str_ability_descr_0x3f
    .word str_ability_descr_0x40
    .word str_ability_descr_0x41
    .word str_ability_descr_0x42
    .word str_ability_descr_0x43
    .word str_ability_descr_0x44
    .word str_ability_descr_0x45
    .word str_ability_descr_0x46
    .word str_ability_descr_0x47
    .word str_ability_descr_0x48
    .word str_ability_descr_0x49
    .word str_ability_descr_0x4a
    .word str_ability_descr_0x4b
    .word str_ability_descr_0x4c
    .word str_ability_descr_0x4d
    .word str_ability_descr_0x4e
    .word str_ability_descr_0x4f
    .word str_ability_descr_0x50
    .word str_ability_descr_0x51
    .word str_ability_descr_0x52
    .word str_ability_descr_0x53
    .word str_ability_descr_0x54
    .word str_ability_descr_0x55
    .word str_ability_descr_0x56
    .word str_ability_descr_0x57
    .word str_ability_descr_0x58
    .word str_ability_descr_0x59
    .word str_ability_descr_0x5a
    .word str_ability_descr_0x5b
    .word str_ability_descr_0x5c
    .word str_ability_descr_0x5d
    .word str_ability_descr_0x5e
    .word str_ability_descr_0x5f
    .word str_ability_descr_0x60
    .word str_ability_descr_0x61
    .word str_ability_descr_0x62
    .word str_ability_descr_0x63
    .word str_ability_descr_0x64
    .word str_ability_descr_0x65
    .word str_ability_descr_0x66
    .word str_ability_descr_0x67
    .word str_ability_descr_0x68
    .word str_ability_descr_0x69
    .word str_ability_descr_0x6a
    .word str_ability_descr_0x6b
    .word str_ability_descr_0x6c
    .word str_ability_descr_0x6d
    .word str_ability_descr_0x6e
    .word str_ability_descr_0x6f
    .word str_ability_descr_0x70
