/*
 * sprite.h
 *
 *  Created on: Mar 28, 2018
 *      Author: dominik
 */

#ifndef INCLUDE_C_OVERWORLD_SPRITE_H_
#define INCLUDE_C_OVERWORLD_SPRITE_H_

/*
 * File:   overworld_sprites.h
 * Author: Domi
 *
 * Created on 16. Juni 2016, 11:14
 */


#include "types.h"
#include "oam.h"

extern u8 ow_anim_standard_npc[];
extern u8 ow_anim_ho_oh[];
extern u8 ow_anim_hiro[];
extern u8 ow_anim_hiro_sit[];
extern u8 ow_anim_hiro_call[];
extern u8 ow_anim_hiro_rod[];
extern u8 ow_anim_hiro_call2[];
extern u8 ow_anim_hiro_bike[];
extern u8 ow_anim_none[];

extern u8 ow_formation_16_32[];
extern u8 ow_formation_128_64[];
extern u8 ow_formation_32_32[];
extern u8 ow_formation_64_64[];
extern u8 ow_formation_16_16[];

extern sprite ow_final_oam_16_32;
extern sprite ow_final_oam_128_64;
extern sprite ow_final_oam_64_64;
extern sprite ow_final_oam_32_32;
extern sprite ow_final_oam_16_16;


typedef struct overworld_sprite {
    u16 tiles_tag; //Tiles tag
    u16 pal_tag; //0x1100 + PalID
    u16 unkown; //usually 0x11FF
    u16 size; //in bytes, e.g. for 32x16 := 0x100
    u16 width;
    u16 height;
    u8 palette_slot : 4;
    u8 shadow_size : 2;
    u8 inanimate : 1;
    u8 disable_reflection : 1; // unused in violet
    u8 field_D;
    u8 field_E;
    u8 field_F;
    sprite *final_oam; //NSE := Pointer 1
    void *formation; //NSE := Pointer 2
    void *animation; //NSE := Anim Pointer
    graphic *graphics; //NSE := equals Pointer 3
    rotscale_frame **rotscales; //No NSE equal
} overworld_sprite;

extern const unsigned short gfx_ow_deoxys_normal_0Tiles[];
extern const unsigned short gfx_ow_deoxys_normal_1Tiles[];
extern const unsigned short gfx_ow_deoxys_normal_2Tiles[];
extern const unsigned short gfx_ow_deoxys_normal_3Tiles[];
extern const unsigned short gfx_ow_deoxys_normal_4Tiles[];
extern const unsigned short gfx_ow_deoxys_normal_5Tiles[];
extern const unsigned short gfx_ow_deoxys_normal_6Tiles[];
extern const unsigned short gfx_ow_deoxys_normal_7Tiles[];
extern const unsigned short gfx_ow_deoxys_normal_8Tiles[];
extern const unsigned short gfx_ow_registeel_0Tiles[];
extern const unsigned short gfx_ow_registeel_1Tiles[];
extern const unsigned short gfx_ow_registeel_2Tiles[];
extern const unsigned short gfx_ow_registeel_3Tiles[];
extern const unsigned short gfx_ow_registeel_4Tiles[];
extern const unsigned short gfx_ow_registeel_5Tiles[];
extern const unsigned short gfx_ow_registeel_6Tiles[];
extern const unsigned short gfx_ow_registeel_7Tiles[];
extern const unsigned short gfx_ow_registeel_8Tiles[];
extern const unsigned short gfx_ow_regice_0Tiles[];
extern const unsigned short gfx_ow_regice_1Tiles[];
extern const unsigned short gfx_ow_regice_2Tiles[];
extern const unsigned short gfx_ow_regice_3Tiles[];
extern const unsigned short gfx_ow_regice_4Tiles[];
extern const unsigned short gfx_ow_regice_5Tiles[];
extern const unsigned short gfx_ow_regice_6Tiles[];
extern const unsigned short gfx_ow_regice_7Tiles[];
extern const unsigned short gfx_ow_regice_8Tiles[];
extern const unsigned short gfx_ow_regirock_0Tiles[];
extern const unsigned short gfx_ow_regirock_1Tiles[];
extern const unsigned short gfx_ow_regirock_2Tiles[];
extern const unsigned short gfx_ow_regirock_3Tiles[];
extern const unsigned short gfx_ow_regirock_4Tiles[];
extern const unsigned short gfx_ow_regirock_5Tiles[];
extern const unsigned short gfx_ow_regirock_6Tiles[];
extern const unsigned short gfx_ow_regirock_7Tiles[];
extern const unsigned short gfx_ow_regirock_8Tiles[];
extern const unsigned short gfx_ow_voltilamm_0Tiles[];
extern const unsigned short gfx_ow_voltilamm_1Tiles[];
extern const unsigned short gfx_ow_voltilamm_2Tiles[];
extern const unsigned short gfx_ow_voltilamm_3Tiles[];
extern const unsigned short gfx_ow_voltilamm_4Tiles[];
extern const unsigned short gfx_ow_voltilamm_5Tiles[];
extern const unsigned short gfx_ow_voltilamm_6Tiles[];
extern const unsigned short gfx_ow_voltilamm_7Tiles[];
extern const unsigned short gfx_ow_voltilamm_8Tiles[];
extern const unsigned short gfx_ow_staralili_0Tiles[];
extern const unsigned short gfx_ow_staralili_1Tiles[];
extern const unsigned short gfx_ow_staralili_2Tiles[];
extern const unsigned short gfx_ow_staralili_3Tiles[];
extern const unsigned short gfx_ow_staralili_4Tiles[];
extern const unsigned short gfx_ow_staralili_5Tiles[];
extern const unsigned short gfx_ow_staralili_6Tiles[];
extern const unsigned short gfx_ow_staralili_7Tiles[];
extern const unsigned short gfx_ow_staralili_8Tiles[];
extern const unsigned short gfx_ow_larissa_0Tiles[];
extern const unsigned short gfx_ow_larissa_1Tiles[];
extern const unsigned short gfx_ow_larissa_2Tiles[];
extern const unsigned short gfx_ow_larissa_3Tiles[];
extern const unsigned short gfx_ow_larissa_4Tiles[];
extern const unsigned short gfx_ow_larissa_5Tiles[];
extern const unsigned short gfx_ow_larissa_6Tiles[];
extern const unsigned short gfx_ow_larissa_7Tiles[];
extern const unsigned short gfx_ow_larissa_8Tiles[];
extern const unsigned short gfx_ow_elise_0Tiles[];
extern const unsigned short gfx_ow_elise_1Tiles[];
extern const unsigned short gfx_ow_elise_2Tiles[];
extern const unsigned short gfx_ow_elise_3Tiles[];
extern const unsigned short gfx_ow_elise_4Tiles[];
extern const unsigned short gfx_ow_elise_5Tiles[];
extern const unsigned short gfx_ow_elise_6Tiles[];
extern const unsigned short gfx_ow_elise_7Tiles[];
extern const unsigned short gfx_ow_elise_8Tiles[];
extern const unsigned short gfx_ow_faun_young_0Tiles[];
extern const unsigned short gfx_ow_faun_young_1Tiles[];
extern const unsigned short gfx_ow_faun_young_2Tiles[];
extern const unsigned short gfx_ow_faun_young_3Tiles[];
extern const unsigned short gfx_ow_faun_young_4Tiles[];
extern const unsigned short gfx_ow_faun_young_5Tiles[];
extern const unsigned short gfx_ow_faun_young_6Tiles[];
extern const unsigned short gfx_ow_faun_young_7Tiles[];
extern const unsigned short gfx_ow_faun_young_8Tiles[];
extern const unsigned short gfx_ow_egg_0Tiles[];
extern const unsigned short gfx_ow_rin_0Tiles[];
extern const unsigned short gfx_ow_rin_1Tiles[];
extern const unsigned short gfx_ow_rin_2Tiles[];
extern const unsigned short gfx_ow_rin_3Tiles[];
extern const unsigned short gfx_ow_rin_4Tiles[];
extern const unsigned short gfx_ow_rin_5Tiles[];
extern const unsigned short gfx_ow_rin_6Tiles[];
extern const unsigned short gfx_ow_rin_7Tiles[];
extern const unsigned short gfx_ow_rin_8Tiles[];
extern const unsigned short gfx_ow_blaise_0Tiles[];
extern const unsigned short gfx_ow_blaise_1Tiles[];
extern const unsigned short gfx_ow_blaise_2Tiles[];
extern const unsigned short gfx_ow_blaise_3Tiles[];
extern const unsigned short gfx_ow_blaise_4Tiles[];
extern const unsigned short gfx_ow_blaise_5Tiles[];
extern const unsigned short gfx_ow_blaise_6Tiles[];
extern const unsigned short gfx_ow_blaise_7Tiles[];
extern const unsigned short gfx_ow_blaise_8Tiles[];
extern const unsigned short gfx_ow_mia_0Tiles[];
extern const unsigned short gfx_ow_mia_1Tiles[];
extern const unsigned short gfx_ow_mia_2Tiles[];
extern const unsigned short gfx_ow_mia_3Tiles[];
extern const unsigned short gfx_ow_mia_4Tiles[];
extern const unsigned short gfx_ow_mia_5Tiles[];
extern const unsigned short gfx_ow_mia_6Tiles[];
extern const unsigned short gfx_ow_mia_7Tiles[];
extern const unsigned short gfx_ow_mia_8Tiles[];
extern const u8 gfx_ow_lesterTiles[];
extern const unsigned short gfx_ow_faun_0Tiles[];
extern const unsigned short gfx_ow_faun_1Tiles[];
extern const unsigned short gfx_ow_faun_2Tiles[];
extern const unsigned short gfx_ow_faun_3Tiles[];
extern const unsigned short gfx_ow_faun_4Tiles[];
extern const unsigned short gfx_ow_faun_5Tiles[];
extern const unsigned short gfx_ow_faun_6Tiles[];
extern const unsigned short gfx_ow_faun_7Tiles[];
extern const unsigned short gfx_ow_faun_8Tiles[];
extern const unsigned short gfx_ow_revolutionary_0Tiles[];
extern const unsigned short gfx_ow_revolutionary_1Tiles[];
extern const unsigned short gfx_ow_revolutionary_2Tiles[];
extern const unsigned short gfx_ow_revolutionary_3Tiles[];
extern const unsigned short gfx_ow_revolutionary_4Tiles[];
extern const unsigned short gfx_ow_revolutionary_5Tiles[];
extern const unsigned short gfx_ow_revolutionary_6Tiles[];
extern const unsigned short gfx_ow_revolutionary_7Tiles[];
extern const unsigned short gfx_ow_revolutionary_8Tiles[];
extern const unsigned short gfx_ow_rival_0Tiles[];
extern const unsigned short gfx_ow_rival_1Tiles[];
extern const unsigned short gfx_ow_rival_2Tiles[];
extern const unsigned short gfx_ow_rival_3Tiles[];
extern const unsigned short gfx_ow_rival_4Tiles[];
extern const unsigned short gfx_ow_rival_5Tiles[];
extern const unsigned short gfx_ow_rival_6Tiles[];
extern const unsigned short gfx_ow_rival_7Tiles[];
extern const unsigned short gfx_ow_rival_8Tiles[];
extern const unsigned short gfx_ow_tann_0Tiles[];
extern const unsigned short gfx_ow_tann_1Tiles[];
extern const unsigned short gfx_ow_tann_2Tiles[];
extern const unsigned short gfx_ow_tann_3Tiles[];
extern const unsigned short gfx_ow_tann_4Tiles[];
extern const unsigned short gfx_ow_tann_5Tiles[];
extern const unsigned short gfx_ow_tann_6Tiles[];
extern const unsigned short gfx_ow_tann_7Tiles[];
extern const unsigned short gfx_ow_tann_8Tiles[];
extern const unsigned short gfx_ow_felix_0Tiles[];
extern const unsigned short gfx_ow_felix_1Tiles[];
extern const unsigned short gfx_ow_felix_2Tiles[];
extern const unsigned short gfx_ow_felix_3Tiles[];
extern const unsigned short gfx_ow_felix_4Tiles[];
extern const unsigned short gfx_ow_felix_5Tiles[];
extern const unsigned short gfx_ow_felix_6Tiles[];
extern const unsigned short gfx_ow_felix_7Tiles[];
extern const unsigned short gfx_ow_felix_8Tiles[];
extern const unsigned short gfx_ow_albus_0Tiles[];
extern const unsigned short gfx_ow_albus_1Tiles[];
extern const unsigned short gfx_ow_albus_2Tiles[];
extern const unsigned short gfx_ow_albus_3Tiles[];
extern const unsigned short gfx_ow_albus_4Tiles[];
extern const unsigned short gfx_ow_albus_5Tiles[];
extern const unsigned short gfx_ow_albus_6Tiles[];
extern const unsigned short gfx_ow_albus_7Tiles[];
extern const unsigned short gfx_ow_albus_8Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_0Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_1Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_2Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_3Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_4Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_5Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_6Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_7Tiles[];
extern const unsigned short gfx_ow_violet_grunt_f_8Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_0Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_1Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_2Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_3Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_4Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_5Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_6Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_7Tiles[];
extern const unsigned short gfx_ow_violet_grunt_m_8Tiles[];
extern const unsigned short gfx_ow_primus_0Tiles[];
extern const unsigned short gfx_ow_primus_1Tiles[];
extern const unsigned short gfx_ow_primus_2Tiles[];
extern const unsigned short gfx_ow_primus_3Tiles[];
extern const unsigned short gfx_ow_primus_4Tiles[];
extern const unsigned short gfx_ow_primus_5Tiles[];
extern const unsigned short gfx_ow_primus_6Tiles[];
extern const unsigned short gfx_ow_primus_7Tiles[];
extern const unsigned short gfx_ow_primus_8Tiles[];
extern const unsigned short gfx_ow_hiro_call_bike_0Tiles[];
extern const unsigned short gfx_ow_hiro_call_bike_1Tiles[];
extern const unsigned short gfx_ow_hiro_call_bike_2Tiles[];
extern const unsigned short gfx_ow_hiro_call_bike_3Tiles[];
extern const unsigned short gfx_ow_hiro_call_bike_4Tiles[];
extern const unsigned short gfx_ow_hiro_call_bike_5Tiles[];
extern const unsigned short gfx_ow_hiro_call2_0Tiles[];
extern const unsigned short gfx_ow_hiro_call2_1Tiles[];
extern const unsigned short gfx_ow_hiro_call2_2Tiles[];
extern const unsigned short gfx_ow_hiro_call2_3Tiles[];
extern const unsigned short gfx_ow_hiro_call2_4Tiles[];
extern const unsigned short gfx_ow_hiro_call2_5Tiles[];
extern const unsigned short gfx_ow_hiro_call2_6Tiles[];
extern const unsigned short gfx_ow_hiro_call2_7Tiles[];
extern const unsigned short gfx_ow_hiro_call2_8Tiles[];
extern const unsigned short gfx_ow_hiro_rod_0Tiles[];
extern const unsigned short gfx_ow_hiro_rod_1Tiles[];
extern const unsigned short gfx_ow_hiro_rod_2Tiles[];
extern const unsigned short gfx_ow_hiro_rod_3Tiles[];
extern const unsigned short gfx_ow_hiro_rod_4Tiles[];
extern const unsigned short gfx_ow_hiro_rod_5Tiles[];
extern const unsigned short gfx_ow_hiro_rod_6Tiles[];
extern const unsigned short gfx_ow_hiro_rod_7Tiles[];
extern const unsigned short gfx_ow_hiro_rod_8Tiles[];
extern const unsigned short gfx_ow_hiro_rod_9Tiles[];
extern const unsigned short gfx_ow_hiro_rod_10Tiles[];
extern const unsigned short gfx_ow_hiro_rod_11Tiles[];
extern const unsigned short gfx_ow_hiro_call_0Tiles[];
extern const unsigned short gfx_ow_hiro_call_1Tiles[];
extern const unsigned short gfx_ow_hiro_call_2Tiles[];
extern const unsigned short gfx_ow_hiro_call_3Tiles[];
extern const unsigned short gfx_ow_hiro_call_4Tiles[];
extern const unsigned short gfx_ow_hiro_call_5Tiles[];
extern const unsigned short gfx_ow_hiro_call_6Tiles[];
extern const unsigned short gfx_ow_hiro_call_7Tiles[];
extern const unsigned short gfx_ow_hiro_call_8Tiles[];
extern const unsigned short gfx_ow_hiro_sit_0Tiles[];
extern const unsigned short gfx_ow_hiro_sit_1Tiles[];
extern const unsigned short gfx_ow_hiro_sit_2Tiles[];
extern const unsigned short gfx_ow_hiro_sit_3Tiles[];
extern const unsigned short gfx_ow_hiro_sit_4Tiles[];
extern const unsigned short gfx_ow_hiro_sit_5Tiles[];
extern const unsigned short gfx_ow_hiro_sit_6Tiles[];
extern const unsigned short gfx_ow_hiro_sit_7Tiles[];
extern const unsigned short gfx_ow_hiro_sit_8Tiles[];
extern const unsigned short gfx_ow_hiro_sit_9Tiles[];
extern const unsigned short gfx_ow_hiro_sit_10Tiles[];
extern const unsigned short gfx_ow_hiro_sit_11Tiles[];
extern const unsigned short gfx_ow_hiro_0Tiles[];
extern const unsigned short gfx_ow_hiro_1Tiles[];
extern const unsigned short gfx_ow_hiro_2Tiles[];
extern const unsigned short gfx_ow_hiro_3Tiles[];
extern const unsigned short gfx_ow_hiro_4Tiles[];
extern const unsigned short gfx_ow_hiro_5Tiles[];
extern const unsigned short gfx_ow_hiro_6Tiles[];
extern const unsigned short gfx_ow_hiro_7Tiles[];
extern const unsigned short gfx_ow_hiro_8Tiles[];
extern const unsigned short gfx_ow_hiro_9Tiles[];
extern const unsigned short gfx_ow_hiro_10Tiles[];
extern const unsigned short gfx_ow_hiro_11Tiles[];
extern const unsigned short gfx_ow_hiro_12Tiles[];
extern const unsigned short gfx_ow_hiro_13Tiles[];
extern const unsigned short gfx_ow_hiro_14Tiles[];
extern const unsigned short gfx_ow_hiro_15Tiles[];
extern const unsigned short gfx_ow_hiro_16Tiles[];
extern const unsigned short gfx_ow_hiro_17Tiles[];
extern const unsigned short gfx_ow_hiro_18Tiles[];
extern const unsigned short gfx_ow_hiro_19Tiles[];
extern const unsigned short gfx_ow_hiroine_0Tiles[];
extern const unsigned short gfx_ow_hiroine_1Tiles[];
extern const unsigned short gfx_ow_hiroine_2Tiles[];
extern const unsigned short gfx_ow_hiroine_3Tiles[];
extern const unsigned short gfx_ow_hiroine_4Tiles[];
extern const unsigned short gfx_ow_hiroine_5Tiles[];
extern const unsigned short gfx_ow_hiroine_6Tiles[];
extern const unsigned short gfx_ow_hiroine_7Tiles[];
extern const unsigned short gfx_ow_hiroine_8Tiles[];
extern const unsigned short gfx_ow_hiroine_9Tiles[];
extern const unsigned short gfx_ow_hiroine_10Tiles[];
extern const unsigned short gfx_ow_hiroine_11Tiles[];
extern const unsigned short gfx_ow_hiroine_12Tiles[];
extern const unsigned short gfx_ow_hiroine_13Tiles[];
extern const unsigned short gfx_ow_hiroine_14Tiles[];
extern const unsigned short gfx_ow_hiroine_15Tiles[];
extern const unsigned short gfx_ow_hiroine_16Tiles[];
extern const unsigned short gfx_ow_hiroine_17Tiles[];
extern const unsigned short gfx_ow_hiroine_18Tiles[];
extern const unsigned short gfx_ow_hiroine_19Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_0Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_1Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_2Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_3Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_4Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_5Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_6Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_7Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_8Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_9Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_10Tiles[];
extern const unsigned short gfx_ow_hiroine_rod_11Tiles[];
extern const unsigned short gfx_ow_hiroine_call_0Tiles[];
extern const unsigned short gfx_ow_hiroine_call_1Tiles[];
extern const unsigned short gfx_ow_hiroine_call_2Tiles[];
extern const unsigned short gfx_ow_hiroine_call_3Tiles[];
extern const unsigned short gfx_ow_hiroine_call_4Tiles[];
extern const unsigned short gfx_ow_hiroine_call_5Tiles[];
extern const unsigned short gfx_pskate_0Tiles[];
extern const unsigned short gfx_pskate_1Tiles[];
extern const unsigned short gfx_pskate_2Tiles[];
extern const unsigned short gfx_pskate_3Tiles[];
extern const unsigned short gfx_pskate_4Tiles[];
extern const unsigned short gfx_pskate_5Tiles[];
extern const unsigned short gfx_pskate_6Tiles[];
extern const unsigned short gfx_pskate_7Tiles[];
extern const unsigned short gfx_pskate_8Tiles[];
extern const unsigned short gfx_pskatef_0Tiles[];
extern const unsigned short gfx_pskatef_1Tiles[];
extern const unsigned short gfx_pskatef_2Tiles[];
extern const unsigned short gfx_pskatef_3Tiles[];
extern const unsigned short gfx_pskatef_4Tiles[];
extern const unsigned short gfx_pskatef_5Tiles[];
extern const unsigned short gfx_pskatef_6Tiles[];
extern const unsigned short gfx_pskatef_7Tiles[];
extern const unsigned short gfx_pskatef_8Tiles[];
extern const unsigned short gfx_ow_igva_0Tiles[];
extern const unsigned short gfx_ow_igva_0Tiles[];
extern const unsigned short gfx_ow_igva_1Tiles[];
extern const unsigned short gfx_ow_igva_1Tiles[];
extern const unsigned short gfx_ow_igva_2Tiles[];
extern const unsigned short gfx_ow_igva_2Tiles[];
extern const unsigned short gfx_ow_igva_3Tiles[];
extern const unsigned short gfx_ow_igva_3Tiles[];
extern const unsigned short gfx_ow_igva_4Tiles[];
extern const unsigned short gfx_ow_igva_4Tiles[];
extern const unsigned short gfx_ow_igva_5Tiles[];
extern const unsigned short gfx_ow_igva_5Tiles[];
extern const unsigned short gfx_ow_igva_6Tiles[];
extern const unsigned short gfx_ow_igva_6Tiles[];
extern const unsigned short gfx_ow_igva_7Tiles[];
extern const unsigned short gfx_ow_igva_7Tiles[];
extern const unsigned short gfx_ow_igva_8Tiles[];
extern const unsigned short gfx_ow_igva_8Tiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_bbshipTiles[];
extern const unsigned short gfx_ow_mpirate_0Tiles[];
extern const unsigned short gfx_ow_mpirate_0Tiles[];
extern const unsigned short gfx_ow_mpirate_1Tiles[];
extern const unsigned short gfx_ow_mpirate_1Tiles[];
extern const unsigned short gfx_ow_mpirate_2Tiles[];
extern const unsigned short gfx_ow_mpirate_2Tiles[];
extern const unsigned short gfx_ow_mpirate_3Tiles[];
extern const unsigned short gfx_ow_mpirate_3Tiles[];
extern const unsigned short gfx_ow_mpirate_4Tiles[];
extern const unsigned short gfx_ow_mpirate_4Tiles[];
extern const unsigned short gfx_ow_mpirate_5Tiles[];
extern const unsigned short gfx_ow_mpirate_5Tiles[];
extern const unsigned short gfx_ow_mpirate_6Tiles[];
extern const unsigned short gfx_ow_mpirate_6Tiles[];
extern const unsigned short gfx_ow_mpirate_7Tiles[];
extern const unsigned short gfx_ow_mpirate_7Tiles[];
extern const unsigned short gfx_ow_mpirate_8Tiles[];
extern const unsigned short gfx_ow_mpirate_8Tiles[];
extern const unsigned short gfx_ow_shape_animal_0Tiles[];
extern const unsigned short gfx_ow_shape_animal_0Tiles[];
extern const unsigned short gfx_ow_shape_animal_1Tiles[];
extern const unsigned short gfx_ow_shape_animal_1Tiles[];
extern const unsigned short gfx_ow_shape_animal_2Tiles[];
extern const unsigned short gfx_ow_shape_animal_2Tiles[];
extern const unsigned short gfx_ow_shape_animal_0Tiles[];
extern const unsigned short gfx_ow_shape_animal_0Tiles[];
extern const unsigned short gfx_ow_shape_animal_1Tiles[];
extern const unsigned short gfx_ow_shape_animal_1Tiles[];
extern const unsigned short gfx_ow_shape_animal_2Tiles[];
extern const unsigned short gfx_ow_shape_animal_2Tiles[];
extern const unsigned short gfx_ow_shape_human_0Tiles[];
extern const unsigned short gfx_ow_shape_human_0Tiles[];
extern const unsigned short gfx_ow_shape_human_1Tiles[];
extern const unsigned short gfx_ow_shape_human_1Tiles[];
extern const unsigned short gfx_ow_shape_human_2Tiles[];
extern const unsigned short gfx_ow_shape_human_2Tiles[];
extern const unsigned short gfx_ow_shape_human_0Tiles[];
extern const unsigned short gfx_ow_shape_human_0Tiles[];
extern const unsigned short gfx_ow_shape_human_1Tiles[];
extern const unsigned short gfx_ow_shape_human_1Tiles[];
extern const unsigned short gfx_ow_shape_human_2Tiles[];
extern const unsigned short gfx_ow_shape_human_2Tiles[];
extern const unsigned short gfx_ow_shape_tail_0Tiles[];
extern const unsigned short gfx_ow_shape_tail_0Tiles[];
extern const unsigned short gfx_ow_shape_tail_1Tiles[];
extern const unsigned short gfx_ow_shape_tail_1Tiles[];
extern const unsigned short gfx_ow_shape_tail_2Tiles[];
extern const unsigned short gfx_ow_shape_tail_2Tiles[];
extern const unsigned short gfx_ow_shape_tail_0Tiles[];
extern const unsigned short gfx_ow_shape_tail_0Tiles[];
extern const unsigned short gfx_ow_shape_tail_1Tiles[];
extern const unsigned short gfx_ow_shape_tail_1Tiles[];
extern const unsigned short gfx_ow_shape_tail_2Tiles[];
extern const unsigned short gfx_ow_shape_tail_2Tiles[];
extern const unsigned short gfx_ow_shape_snake_0Tiles[];
extern const unsigned short gfx_ow_shape_snake_0Tiles[];
extern const unsigned short gfx_ow_shape_snake_1Tiles[];
extern const unsigned short gfx_ow_shape_snake_1Tiles[];
extern const unsigned short gfx_ow_shape_snake_2Tiles[];
extern const unsigned short gfx_ow_shape_snake_2Tiles[];
extern const unsigned short gfx_ow_shape_snake_0Tiles[];
extern const unsigned short gfx_ow_shape_snake_0Tiles[];
extern const unsigned short gfx_ow_shape_snake_1Tiles[];
extern const unsigned short gfx_ow_shape_snake_1Tiles[];
extern const unsigned short gfx_ow_shape_snake_2Tiles[];
extern const unsigned short gfx_ow_shape_snake_2Tiles[];
extern const unsigned short gfx_ow_shape_winsect_0Tiles[];
extern const unsigned short gfx_ow_shape_winsect_0Tiles[];
extern const unsigned short gfx_ow_shape_winsect_1Tiles[];
extern const unsigned short gfx_ow_shape_winsect_1Tiles[];
extern const unsigned short gfx_ow_shape_winsect_2Tiles[];
extern const unsigned short gfx_ow_shape_winsect_2Tiles[];
extern const unsigned short gfx_ow_shape_winsect_0Tiles[];
extern const unsigned short gfx_ow_shape_winsect_0Tiles[];
extern const unsigned short gfx_ow_shape_winsect_1Tiles[];
extern const unsigned short gfx_ow_shape_winsect_1Tiles[];
extern const unsigned short gfx_ow_shape_winsect_2Tiles[];
extern const unsigned short gfx_ow_shape_winsect_2Tiles[];
extern const unsigned short gfx_ow_shape_winged_0Tiles[];
extern const unsigned short gfx_ow_shape_winged_0Tiles[];
extern const unsigned short gfx_ow_shape_winged_1Tiles[];
extern const unsigned short gfx_ow_shape_winged_1Tiles[];
extern const unsigned short gfx_ow_shape_winged_2Tiles[];
extern const unsigned short gfx_ow_shape_winged_2Tiles[];
extern const unsigned short gfx_ow_shape_winged_0Tiles[];
extern const unsigned short gfx_ow_shape_winged_0Tiles[];
extern const unsigned short gfx_ow_shape_winged_1Tiles[];
extern const unsigned short gfx_ow_shape_winged_1Tiles[];
extern const unsigned short gfx_ow_shape_winged_2Tiles[];
extern const unsigned short gfx_ow_shape_winged_2Tiles[];
extern const unsigned short gfx_ow_shape_insect_0Tiles[];
extern const unsigned short gfx_ow_shape_insect_0Tiles[];
extern const unsigned short gfx_ow_shape_insect_1Tiles[];
extern const unsigned short gfx_ow_shape_insect_1Tiles[];
extern const unsigned short gfx_ow_shape_insect_2Tiles[];
extern const unsigned short gfx_ow_shape_insect_2Tiles[];
extern const unsigned short gfx_ow_shape_insect_0Tiles[];
extern const unsigned short gfx_ow_shape_insect_0Tiles[];
extern const unsigned short gfx_ow_shape_insect_1Tiles[];
extern const unsigned short gfx_ow_shape_insect_1Tiles[];
extern const unsigned short gfx_ow_shape_insect_2Tiles[];
extern const unsigned short gfx_ow_shape_insect_2Tiles[];
extern const unsigned short gfx_ow_shape_head_0Tiles[];
extern const unsigned short gfx_ow_shape_head_0Tiles[];
extern const unsigned short gfx_ow_shape_head_1Tiles[];
extern const unsigned short gfx_ow_shape_head_1Tiles[];
extern const unsigned short gfx_ow_shape_head_2Tiles[];
extern const unsigned short gfx_ow_shape_head_2Tiles[];
extern const unsigned short gfx_ow_shape_head_0Tiles[];
extern const unsigned short gfx_ow_shape_head_0Tiles[];
extern const unsigned short gfx_ow_shape_head_1Tiles[];
extern const unsigned short gfx_ow_shape_head_1Tiles[];
extern const unsigned short gfx_ow_shape_head_2Tiles[];
extern const unsigned short gfx_ow_shape_head_2Tiles[];
extern const unsigned short gfx_ow_shape_arms_0Tiles[];
extern const unsigned short gfx_ow_shape_arms_0Tiles[];
extern const unsigned short gfx_ow_shape_arms_1Tiles[];
extern const unsigned short gfx_ow_shape_arms_1Tiles[];
extern const unsigned short gfx_ow_shape_arms_2Tiles[];
extern const unsigned short gfx_ow_shape_arms_2Tiles[];
extern const unsigned short gfx_ow_shape_arms_0Tiles[];
extern const unsigned short gfx_ow_shape_arms_0Tiles[];
extern const unsigned short gfx_ow_shape_arms_1Tiles[];
extern const unsigned short gfx_ow_shape_arms_1Tiles[];
extern const unsigned short gfx_ow_shape_arms_2Tiles[];
extern const unsigned short gfx_ow_shape_arms_2Tiles[];
extern const unsigned short gfx_ow_shape_legs_0Tiles[];
extern const unsigned short gfx_ow_shape_legs_0Tiles[];
extern const unsigned short gfx_ow_shape_legs_1Tiles[];
extern const unsigned short gfx_ow_shape_legs_1Tiles[];
extern const unsigned short gfx_ow_shape_legs_2Tiles[];
extern const unsigned short gfx_ow_shape_legs_2Tiles[];
extern const unsigned short gfx_ow_shape_legs_0Tiles[];
extern const unsigned short gfx_ow_shape_legs_0Tiles[];
extern const unsigned short gfx_ow_shape_legs_1Tiles[];
extern const unsigned short gfx_ow_shape_legs_1Tiles[];
extern const unsigned short gfx_ow_shape_legs_2Tiles[];
extern const unsigned short gfx_ow_shape_legs_2Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_0Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_0Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_1Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_1Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_2Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_2Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_0Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_0Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_1Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_1Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_2Tiles[];
extern const unsigned short gfx_ow_shape_tentacles_2Tiles[];
extern const unsigned short gfx_ow_shape_fish_0Tiles[];
extern const unsigned short gfx_ow_shape_fish_0Tiles[];
extern const unsigned short gfx_ow_shape_fish_1Tiles[];
extern const unsigned short gfx_ow_shape_fish_1Tiles[];
extern const unsigned short gfx_ow_shape_fish_2Tiles[];
extern const unsigned short gfx_ow_shape_fish_2Tiles[];
extern const unsigned short gfx_ow_shape_fish_0Tiles[];
extern const unsigned short gfx_ow_shape_fish_0Tiles[];
extern const unsigned short gfx_ow_shape_fish_1Tiles[];
extern const unsigned short gfx_ow_shape_fish_1Tiles[];
extern const unsigned short gfx_ow_shape_fish_2Tiles[];
extern const unsigned short gfx_ow_shape_fish_2Tiles[];
extern const unsigned short gfx_ow_shape_ball_0Tiles[];
extern const unsigned short gfx_ow_shape_ball_0Tiles[];
extern const unsigned short gfx_ow_shape_ball_1Tiles[];
extern const unsigned short gfx_ow_shape_ball_1Tiles[];
extern const unsigned short gfx_ow_shape_ball_2Tiles[];
extern const unsigned short gfx_ow_shape_ball_2Tiles[];
extern const unsigned short gfx_ow_shape_ball_0Tiles[];
extern const unsigned short gfx_ow_shape_ball_0Tiles[];
extern const unsigned short gfx_ow_shape_ball_1Tiles[];
extern const unsigned short gfx_ow_shape_ball_1Tiles[];
extern const unsigned short gfx_ow_shape_ball_2Tiles[];
extern const unsigned short gfx_ow_shape_ball_2Tiles[];
extern const unsigned short gfx_ow_shape_multi_0Tiles[];
extern const unsigned short gfx_ow_shape_multi_0Tiles[];
extern const unsigned short gfx_ow_shape_multi_1Tiles[];
extern const unsigned short gfx_ow_shape_multi_1Tiles[];
extern const unsigned short gfx_ow_shape_multi_2Tiles[];
extern const unsigned short gfx_ow_shape_multi_2Tiles[];
extern const unsigned short gfx_ow_shape_multi_0Tiles[];
extern const unsigned short gfx_ow_shape_multi_0Tiles[];
extern const unsigned short gfx_ow_shape_multi_1Tiles[];
extern const unsigned short gfx_ow_shape_multi_1Tiles[];
extern const unsigned short gfx_ow_shape_multi_2Tiles[];
extern const unsigned short gfx_ow_shape_multi_2Tiles[];
extern const unsigned short gfx_ow_mistral_0Tiles[];
extern const unsigned short gfx_ow_mistral_0Tiles[];
extern const unsigned short gfx_ow_mistral_1Tiles[];
extern const unsigned short gfx_ow_mistral_1Tiles[];
extern const unsigned short gfx_ow_mistral_2Tiles[];
extern const unsigned short gfx_ow_mistral_2Tiles[];
extern const unsigned short gfx_ow_mistral_3Tiles[];
extern const unsigned short gfx_ow_mistral_3Tiles[];
extern const unsigned short gfx_ow_mistral_4Tiles[];
extern const unsigned short gfx_ow_mistral_4Tiles[];
extern const unsigned short gfx_ow_mistral_5Tiles[];
extern const unsigned short gfx_ow_mistral_5Tiles[];
extern const unsigned short gfx_ow_mistral_6Tiles[];
extern const unsigned short gfx_ow_mistral_6Tiles[];
extern const unsigned short gfx_ow_mistral_7Tiles[];
extern const unsigned short gfx_ow_mistral_7Tiles[];
extern const unsigned short gfx_ow_mistral_8Tiles[];
extern const unsigned short gfx_ow_mistral_8Tiles[];
extern const unsigned short gfx_ow_manus_0Tiles[];
extern const unsigned short gfx_ow_manus_0Tiles[];
extern const unsigned short gfx_ow_manus_1Tiles[];
extern const unsigned short gfx_ow_manus_1Tiles[];
extern const unsigned short gfx_ow_manus_2Tiles[];
extern const unsigned short gfx_ow_manus_2Tiles[];
extern const unsigned short gfx_ow_manus_3Tiles[];
extern const unsigned short gfx_ow_manus_3Tiles[];
extern const unsigned short gfx_ow_manus_4Tiles[];
extern const unsigned short gfx_ow_manus_4Tiles[];
extern const unsigned short gfx_ow_manus_5Tiles[];
extern const unsigned short gfx_ow_manus_5Tiles[];
extern const unsigned short gfx_ow_manus_6Tiles[];
extern const unsigned short gfx_ow_manus_6Tiles[];
extern const unsigned short gfx_ow_manus_7Tiles[];
extern const unsigned short gfx_ow_manus_7Tiles[];
extern const unsigned short gfx_ow_manus_8Tiles[];
extern const unsigned short gfx_ow_manus_8Tiles[];
extern const unsigned short gfx_ow_altaria_0Tiles[];
extern const unsigned short gfx_ow_altaria_0Tiles[];
extern const unsigned short gfx_ow_altaria_0Tiles[];
extern const unsigned short gfx_ow_altaria_0Tiles[];
extern const unsigned short gfx_ow_altaria_0Tiles[];
extern const unsigned short gfx_ow_altaria_1Tiles[];
extern const unsigned short gfx_ow_altaria_1Tiles[];
extern const unsigned short gfx_ow_altaria_0Tiles[];
extern const unsigned short gfx_ow_altaria_1Tiles[];
extern const unsigned short gfx_ow_altaria_0Tiles[];
extern const unsigned short gfx_ow_altaria_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_0Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_0Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_2Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_2Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_0Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_0Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_2Tiles[];
extern const unsigned short gfx_ow_cloudrider_fem_2Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_0Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_0Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_2Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_2Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_0Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_0Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_1Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_2Tiles[];
extern const unsigned short gfx_ow_cloudrider_male_2Tiles[];
extern const unsigned short gfx_ow_moltres_0Tiles[];
extern const unsigned short gfx_ow_moltres_0Tiles[];
extern const unsigned short gfx_ow_moltres_0Tiles[];
extern const unsigned short gfx_ow_moltres_0Tiles[];
extern const unsigned short gfx_ow_moltres_0Tiles[];
extern const unsigned short gfx_ow_moltres_1Tiles[];
extern const unsigned short gfx_ow_moltres_1Tiles[];
extern const unsigned short gfx_ow_moltres_0Tiles[];
extern const unsigned short gfx_ow_moltres_1Tiles[];
extern const unsigned short gfx_ow_moltres_0Tiles[];
extern const unsigned short gfx_ow_moltres_1Tiles[];
extern const unsigned short gfx_ow_diserakt_0Tiles[];
extern const unsigned short gfx_ow_diserakt_0Tiles[];
extern const unsigned short gfx_ow_diserakt_2Tiles[];
extern const unsigned short gfx_ow_diserakt_2Tiles[];
extern const unsigned short gfx_ow_diserakt_1Tiles[];
extern const unsigned short gfx_ow_diserakt_1Tiles[];
extern const unsigned short gfx_ow_diserakt_0Tiles[];
extern const unsigned short gfx_ow_diserakt_0Tiles[];
extern const unsigned short gfx_ow_diserakt_2Tiles[];
extern const unsigned short gfx_ow_diserakt_2Tiles[];
extern const unsigned short gfx_ow_diserakt_1Tiles[];
extern const unsigned short gfx_ow_diserakt_1Tiles[];
extern const unsigned short gfx_ow_groudon_0Tiles[];
extern const unsigned short gfx_ow_groudon_0Tiles[];
extern const unsigned short gfx_ow_groudon_0Tiles[];
extern const unsigned short gfx_ow_groudon_0Tiles[];
extern const unsigned short gfx_ow_groudon_1Tiles[];
extern const unsigned short gfx_ow_groudon_1Tiles[];
extern const unsigned short gfx_ow_groudon_2Tiles[];
extern const unsigned short gfx_ow_groudon_2Tiles[];
extern const unsigned short gfx_ow_groudon_1Tiles[];
extern const unsigned short gfx_ow_groudon_2Tiles[];
extern const unsigned short gfx_ow_groudon_1Tiles[];
extern const unsigned short gfx_ow_groudon_2Tiles[];
extern const unsigned short gfx_ow_rubys_0Tiles[];
extern const unsigned short gfx_ow_rubys_0Tiles[];
extern const unsigned short gfx_ow_rubys_1Tiles[];
extern const unsigned short gfx_ow_rubys_1Tiles[];
extern const unsigned short gfx_ow_rubys_2Tiles[];
extern const unsigned short gfx_ow_rubys_2Tiles[];
extern const unsigned short gfx_ow_rubys_3Tiles[];
extern const unsigned short gfx_ow_rubys_3Tiles[];
extern const unsigned short gfx_ow_rubys_4Tiles[];
extern const unsigned short gfx_ow_rubys_4Tiles[];
extern const unsigned short gfx_ow_rubys_5Tiles[];
extern const unsigned short gfx_ow_rubys_5Tiles[];
extern const unsigned short gfx_ow_rubys_6Tiles[];
extern const unsigned short gfx_ow_rubys_6Tiles[];
extern const unsigned short gfx_ow_rubys_7Tiles[];
extern const unsigned short gfx_ow_rubys_7Tiles[];
extern const unsigned short gfx_ow_rubys_8Tiles[];
extern const unsigned short gfx_ow_rubys_8Tiles[];
extern const unsigned short gfx_ow_hiroine_sit_0Tiles[];
extern const unsigned short gfx_ow_hiroine_sit_1Tiles[];
extern const unsigned short gfx_ow_hiroine_sit_2Tiles[];
extern const unsigned short gfx_ow_botogel_0Tiles[];
extern const unsigned short gfx_ow_botogel_1Tiles[];
extern const unsigned short gfx_ow_botogel_2Tiles[];
extern const unsigned short gfx_ow_mother_0Tiles[];
extern const unsigned short gfx_ow_mother_1Tiles[];
extern const unsigned short gfx_ow_mother_2Tiles[];
extern const unsigned short gfx_ow_mother_3Tiles[];
extern const unsigned short gfx_ow_mother_4Tiles[];
extern const unsigned short gfx_ow_mother_5Tiles[];
extern const unsigned short gfx_ow_mother_6Tiles[];
extern const unsigned short gfx_ow_mother_7Tiles[];
extern const unsigned short gfx_ow_mother_8Tiles[];
extern const unsigned short gfx_ow_drampaTiles[];
extern const unsigned short gfx_ow_blackbeardTiles[];
extern const unsigned short gfx_ow_teahTiles[];
extern const unsigned short gfx_ow_narcissaTiles[];
extern const unsigned short gfx_ow_harrenfeld_0Tiles[];
extern const unsigned short gfx_ow_harrenfeld_1Tiles[];
extern const unsigned short gfx_ow_harrenfeld_2Tiles[];
extern const unsigned short gfx_ow_harrenfeld_3Tiles[];
extern const unsigned short gfx_ow_harrenfeld_4Tiles[];
extern const unsigned short gfx_ow_harrenfeld_5Tiles[];
extern const unsigned short gfx_ow_harrenfeld_6Tiles[];
extern const unsigned short gfx_ow_harrenfeld_7Tiles[];
extern const unsigned short gfx_ow_harrenfeld_8Tiles[];
extern const unsigned short gfx_ow_butler_0Tiles[];
extern const unsigned short gfx_ow_butler_1Tiles[];
extern const unsigned short gfx_ow_butler_2Tiles[];
extern const unsigned short gfx_ow_butler_3Tiles[];
extern const unsigned short gfx_ow_butler_4Tiles[];
extern const unsigned short gfx_ow_butler_5Tiles[];
extern const unsigned short gfx_ow_butler_6Tiles[];
extern const unsigned short gfx_ow_butler_7Tiles[];
extern const unsigned short gfx_ow_butler_8Tiles[];
extern const unsigned short gfx_ow_lucius_0Tiles[];
extern const unsigned short gfx_ow_lucius_1Tiles[];
extern const unsigned short gfx_ow_lucius_2Tiles[];
extern const unsigned short gfx_ow_lucius_3Tiles[];
extern const unsigned short gfx_ow_lucius_4Tiles[];
extern const unsigned short gfx_ow_lucius_5Tiles[];
extern const unsigned short gfx_ow_lucius_6Tiles[];
extern const unsigned short gfx_ow_lucius_7Tiles[];
extern const unsigned short gfx_ow_lucius_8Tiles[];
extern const u8 gfx_ow_luckyTiles[];


#define OVERWORLD_PLAYER_PICTURE_CONTEXT_WALKING 0
#define OVERWORLD_PLAYER_PICTURE_CONTEXT_BIKING 1

/**
 * Gets the picture of the player in a given context.
 * @param context the context the player is in
 * @return the picture of the player
 **/
u8 player_get_overworld_picture(u8 context);


/**
 * Finds the overworld_sprite structure of a picture idx.
 * @param picture the picture of the overworld
 * @return sprite the overworld_sprite structure
 **/
overworld_sprite *overworld_get(u16 picture);

/**
 * Translates map coordinates to coordinates for an oam.
 * @param map_x the x on the map in blocks
 * @param map_y the y on the map in blocks
 * @param oam_x resulting oam x coordinate
 * @param oam_y resulting oam y coordinate
 **/
void map_position_to_oam_position(s16 map_x, s16 map_y, s16 *oam_x, s16 *oam_y);

#endif /* INCLUDE_C_OVERWORLD_SPRITE_H_ */
