#ifndef H_CONST_ATTACK_AFFECTS_WHOM_FLAGS
#define H_CONST_ATTACK_AFFECTS_WHOM_FLAGS
enum attack_affects_whom_flags {
SELECTED_TARGET = 0,
TARGET_DEPENDS_ON_ATTACK = 1,
TARGET_UNUSED = 2,
RANDOM_TARGET = 4,
TARGET_BOTH_FOES = 8,
TARGET_USER = 16,
TARGET_BOTH_FOES_AND_PARTNER = 32,
TARGET_OPPONENT_FIELD = 64,
};
#endif