#ifndef H_CONST_ATTACK_FLAGS
#define H_CONST_ATTACK_FLAGS
enum attack_flags {
MAKES_CONTACT = 1,
AFFECTED_BY_PROTECT = 2,
AFFECTED_BY_MAGIC_COAT = 4,
AFFECTED_BY_SNATCH = 8,
MIRRORABLE = 16,
TRIGGERS_KINGS_ROCK = 32,
};
#endif