#ifndef H_CONST_BATTLE_BGS
#define H_CONST_BATTLE_BGS
enum battle_bgs {
BATTLE_BG_STREET = 0,
BATTLE_BG_GRASS = 1,
BATTLE_BG_MOUNTAIN = 2,
BATTLE_BG_POND = 3,
BATTLE_BG_CLOUD = 4,
BATTLE_BG_SHORE = 5,
BATTLE_BG_OCEAN = 6,
BATTLE_BG_CAVE = 7,
BATTLE_BG_DESERT = 8,
BATTLE_BG_GYM = 9,
BATTLE_BG_WATER_CAVE = 10,
BATTLE_BG_MUSEUM = 11,
BATTLE_BG_FIRE = 12,
BATTLE_BG_EVOLUTION = 13,
BATTLE_BG_CAPTURE = 14,
BATTLE_BG_MILL = 15,
};
#endif