#ifndef H_CONST_DIFFICULTIES
#define H_CONST_DIFFICULTIES
enum difficulties {
DIFFICULTY_VERY_EASY = 0,
DIFFICULTY_EASY = 1,
DIFFICULTY_NORMAL = 2,
DIFFICULTY_HARD = 3,
DIFFICULTY_VERY_HARD = 4,
};
#endif