#ifndef H_CONST_EGG_GROUPS
#define H_CONST_EGG_GROUPS
enum egg_groups {
EGG_GROUP_NONE = 0,
EGG_GROUP_MONSTER = 1,
EGG_GROUP_WASSER_1 = 2,
EGG_GROUP_KAEFER = 3,
EGG_GROUP_FLUG = 4,
EGG_GROUP_FELD = 5,
EGG_GROUP_FEE = 6,
EGG_GROUP_PFLANZE = 7,
EGG_GROUP_HUMANOTYP = 8,
EGG_GROUP_WASSER_3 = 9,
EGG_GROUP_MINERAL = 10,
EGG_GROUP_AMORPH = 11,
EGG_GROUP_WASSER_2 = 12,
EGG_GROUP_DITTO = 13,
EGG_GROUP_DRACHE = 14,
EGG_GROUP_UNBEKANNT = 15,
};
#endif