#ifndef H_CONST_ITEM_POCKETS
#define H_CONST_ITEM_POCKETS
enum item_pockets {
POCKET_NONE = 0,
POCKET_ITEMS = 1,
POCKET_KEY_ITEMS = 2,
POCKET_POKEBALLS = 3,
POCKET_TM_HM = 4,
POCKET_BERRIES = 5,
};
#endif