#ifndef H_CONST_ITEM_WEATHER_ROCK_TYPES
#define H_CONST_ITEM_WEATHER_ROCK_TYPES
enum item_weather_rock_types {
WEATHER_ROCK_RAIN = 0,
WEATHER_ROCK_SUN = 1,
WEATHER_ROCK_HAIL = 2,
WEATHER_ROCK_SANDSTORM = 3,
};
#endif