#ifndef H_CONST_LANGUAGES
#define H_CONST_LANGUAGES
enum languages {
LANGUAGE_JAPANESE = 0,
LANGUAGE_ENGLISH = 1,
LANGUAGE_FRENCH = 2,
LANGUAGE_ITALIAN = 3,
LANGUAGE_GERMAN = 4,
LANGUAGE_KOREAN = 5,
LANGUAGE_SPANISH = 6,
};
#endif