#ifndef H_CONST_MAP_WEATHERS
#define H_CONST_MAP_WEATHERS
enum map_weathers {
MAP_WEATHER_INSIDE = 0,
MAP_WEATHER_SUNNY_WITH_CLOUD_REFLECTION = 1,
MAP_WEATHER_OUTSIDE = 2,
MAP_WEATHER_RAIN = 3,
MAP_WEATHER_SNOW = 4,
MAP_WEATHER_THUNDER = 5,
MAP_WEATHER_STATIC_FOG = 6,
MAP_WEATHER_ASH = 7,
MAP_WEATHER_SANDSTORM = 8,
MAP_WEATHER_DYNAMIC_FOG = 9,
MAP_WEATHER_DENSE_FOG = 10,
MAP_WEATHER_CLOUDY = 11,
MAP_WEATHER_EXTREME_SUN = 12,
MAP_WEATHER_EXTREME_THUNDER = 13,
MAP_WEATHER_UNDERWATER = 14,
MAP_WEATHER_WEATHER_0F = 15,
};
#endif