#ifndef H_CONST_MAP_BATTLE_STYLES
#define H_CONST_MAP_BATTLE_STYLES
enum map_battle_styles {
BATTLE_TYPE_RANDOM = 0,
BATTLE_TYPE_ARENA = 1,
BATTLE_TYPE_TEAM_ROCKET = 2,
BATTLE_TYPE_03 = 3,
BATTLE_TYPE_ELITE4_FIRST = 4,
BATTLE_TYPE_ELITE4_SECOND = 5,
BATTLE_TYPE_ELITE4_THIRD = 6,
BATTLE_TYPE_ELITE4_FOURTH = 7,
BATTLE_TYPE_BIG_POKEBALL = 8,
};
#endif