#ifndef H_CONST_MAP_TYPES
#define H_CONST_MAP_TYPES
enum map_types {
MAP_TYPE_STD = 0,
MAP_TYPE_VILLAGE = 1,
MAP_TYPE_CITY = 2,
MAP_TYPE_ROUTE = 3,
MAP_TYPE_BASEMENT = 4,
MAP_TYPE_UNDERWATER = 5,
MAP_TYPE_TYPE_06 = 6,
MAP_TYPE_TYPE_07 = 7,
MAP_TYPE_INSIDE = 8,
MAP_TYPE_SECRET_BASE = 9,
};
#endif