#ifndef H_CONST_MAP_SHOW_NAME_TYPES
#define H_CONST_MAP_SHOW_NAME_TYPES
enum map_show_name_types {
DONT_SHOW = 0,
SHOW = 1,
MAP_SHOW_NAME_2 = 2,
MAP_SHOW_NAME_3 = 3,
MAP_SHOW_NAME_4 = 4,
MAP_SHOW_NAME_5 = 5,
SHOW_VILLAGE = 6,
MAP_SHOW_NAME_7 = 7,
SHOW_CITY = 13,
};
#endif