#ifndef H_CONST_MOVE_TUTOR
#define H_CONST_MOVE_TUTOR
enum move_tutor {
MOVE_TUTOR_FOKUSSTOSS = 0,
MOVE_TUTOR_GIFTHIEB = 1,
MOVE_TUTOR_FINSTERAURA = 2,
MOVE_TUTOR_EISZAHN = 3,
MOVE_TUTOR_DONNERZAHN = 4,
MOVE_TUTOR_KREUZSCHERE = 5,
MOVE_TUTOR_STEINKANTE = 6,
MOVE_TUTOR_LICHTKANONE = 7,
MOVE_TUTOR_DRACO_METEOR = 8,
MOVE_TUTOR_ENERGIEBALL = 9,
MOVE_TUTOR_DRACHENPULS = 10,
MOVE_TUTOR_FEUERZAHN = 11,
MOVE_TUTOR_EXPLOSION = 12,
MOVE_TUTOR_STEINHAGEL = 13,
MOVE_TUTOR_DELEGATOR = 14,
MOVE_TUTOR_FLORA_STATUE = 15,
MOVE_TUTOR_LOHEKANONADE = 16,
MOVE_TUTOR_AQUAHAUBITZE = 17,
MOVE_TUTOR_DONNERWELLE = 18,
};
#endif