#ifndef H_CONST_POKEMON_LANGUAGE_IDS
#define H_CONST_POKEMON_LANGUAGE_IDS
enum pokemon_language_ids {
LANGUAGE_JAP = 0,
LANGUAGE_ENG = 1,
LANGUAGE_FRA = 2,
LANGAUGE_ITA = 3,
LANGUAGE_GER = 4,
LANGUAGE_KOR = 5,
LANGUAGE_ESP = 6,
};
#endif