#ifndef H_CONST_POKEMON_STAT_NAMES
#define H_CONST_POKEMON_STAT_NAMES
enum pokemon_stat_names {
STAT_HP = 0,
STAT_ATTACK = 1,
STAT_DEFENSE = 2,
STAT_SPEED = 3,
STAT_SPECIAL_ATTACK = 4,
STAT_SPECIAL_DEFENSE = 5,
STAT_ACCURACY = 6,
STAT_EVASION = 7,
};
#endif