#ifndef H_CONST_POKEMON_SHAPES
#define H_CONST_POKEMON_SHAPES
enum pokemon_shapes {
SHAPE_QUADRUPED = 0,
SHAPE_HUMANOID = 1,
SHAPE_UPRIGHT = 2,
SHAPE_SQUIGGLE = 3,
SHAPE_BUG_WINGS = 4,
SHAPE_WINGS = 5,
SHAPE_ARMOR = 6,
SHAPE_BLOB = 7,
SHAPE_ARMS = 8,
SHAPE_LEGS = 9,
SHAPE_TENTACLES = 10,
SHAPE_FISH = 11,
SHAPE_BALL = 12,
SHAPE_HEADS = 13,
};
#endif