#ifndef H_CONST_POKEMON_COLORS
#define H_CONST_POKEMON_COLORS
enum pokemon_colors {
POKEMON_COLOR_NONE = 0,
POKEMON_COLOR_BLAU = 1,
POKEMON_COLOR_BRAUN = 2,
POKEMON_COLOR_GELB = 3,
POKEMON_COLOR_GRAU = 4,
POKEMON_COLOR_GRUEN = 5,
POKEMON_COLOR_ROSA = 6,
POKEMON_COLOR_ROT = 7,
POKEMON_COLOR_SCHWARZ = 8,
POKEMON_COLOR_VIOLETT = 9,
POKEMON_COLOR_WEISS = 10,
};
#endif