#ifndef H_CONST_POKEMON_GROWTH_RATES
#define H_CONST_POKEMON_GROWTH_RATES
enum pokemon_growth_rates {
GROWTH_RATE_MEDIUM = 0,
GROWTH_RATE_SLOW_THEN_VERY_FAST = 1,
GROWTH_RATE_FAST_THEN_VERY_SLOW = 2,
GROWTH_RATE_MEDIUM_SLOW = 3,
GROWTH_RATE_FAST = 4,
GROWTH_RATE_SLOW = 5,
};
#endif