#ifndef H_CONST_POKEMON_TYPES
#define H_CONST_POKEMON_TYPES
enum pokemon_types {
TYPE_NORMAL = 0,
TYPE_KAMPF = 1,
TYPE_FLUG = 2,
TYPE_GIFT = 3,
TYPE_BODEN = 4,
TYPE_GESTEIN = 5,
TYPE_KAEFER = 6,
TYPE_GEIST = 7,
TYPE_STAHL = 8,
TYPE_FEE = 9,
TYPE_FEUER = 10,
TYPE_WASSER = 11,
TYPE_PFLANZE = 12,
TYPE_ELEKTRO = 13,
TYPE_PSYCHO = 14,
TYPE_EIS = 15,
TYPE_DRACHE = 16,
TYPE_UNLICHT = 17,
};
#endif