#ifndef H_CONST_TRAINER_BUILDS
#define H_CONST_TRAINER_BUILDS
enum trainer_builds {
TRAINER_BUILD_NONE = 0,
TRAINER_BUILD_PHYSICAL_SWEEPER_ATTACK_PREFERENCE = 1,
TRAINER_BUILD_PHYSICAL_SWEEPER_SPEED_PREFERENCE = 2,
TRAINER_BUILD_SPECIAL_SWEEPER_SPECIAL_ATTACK_PREFERENCE = 3,
TRAINER_BUILD_SPECIAL_SWEEPER_SPEED_PREFERENCE = 4,
TRAINER_BUILD_PHYSICAL_WALL_SPECIAL_ATTACK_PREFERENCE = 5,
TRAINER_BUILD_PHYSICAL_WALL_ATTACK_PREFERENCE = 6,
TRAINER_BUILD_SPECIAL_WALL_SPECIAL_ATTACK_PREFERENCE = 7,
TRAINER_BUILD_SPECIAL_WALL_ATTACK_PREFERENCE = 8,
TRAINER_BUILD_MIXED_SWEEPER = 9,
TRAINER_BUILD_PHYSICAL_TANK = 10,
TRAINER_BUILD_SPECIAL_TANK = 11,
};
#endif