/*
 * weather.h
 *
 *  Created on: Mar 28, 2018
 *      Author: dominik
 */

#ifndef INCLUDE_C_BATTLE_WEATHER_H_
#define INCLUDE_C_BATTLE_WEATHER_H_

#include "abilities.h"
#include "constants/abilities.h"
#include "constants/battle/battle_weathers.h"

#define WEATHER_HAS_EFFECT ((!ABILITY_PRESENT(WOLKE_SIEBEN) && !ABILITY_PRESENT(KLIMASCHUTZ)))
#define WEATHER_HAS_EFFECT2 ((!ABILITY_PRESENT(WOLKE_SIEBEN) && !ABILITY_PRESENT(KLIMASCHUTZ)))

#define BATTLE_WEATHER_RAIN_ANY (BATTLE_WEATHER_RAIN | BATTLE_WEATHER_RAIN_DRIZZLE)
#define BATTLE_WEATHER_SUN_ANY (BATTLE_WEATHER_SUN | BATTLE_WEATHER_SUN_DROUGHT)
#define BATTLE_WEATHER_SANDSTORM_ANY (BATTLE_WEATHER_SANDSTORM | BATTLE_WEATHER_SANDSTORM_ABILITY)
#define BATTLE_WEATHER_HAIL_ANY (BATTLE_WEATHER_HAIL)

extern u16 battle_weather;

#endif /* INCLUDE_C_BATTLE_WEATHER_H_ */
