.global bsc_strings

.align 4
bsc_strings:
.word str_battle_xc
.word str_battle_xd
.word str_battle_xe
.word str_battle_xf
.word str_battle_x10
.word str_battle_x11
.word str_battle_x12
.word str_battle_x13
.word str_battle_x14
.word str_battle_x15
.word str_battle_x16
.word str_battle_x17
.word str_battle_x18
.word str_battle_x19
.word str_battle_x1a
.word str_battle_x1b
.word str_battle_x1c
.word str_battle_x1d
.word str_battle_x1e
.word str_battle_x1f
.word str_battle_x20
.word str_battle_x21
.word str_battle_x22
.word str_battle_x23
.word str_battle_x24
.word str_battle_x25
.word str_battle_x26
.word str_battle_x27
.word str_battle_x28
.word str_battle_x29
.word str_battle_x2a
.word str_battle_x2b
.word str_battle_x2c
.word str_battle_x2d
.word str_battle_x2e
.word str_battle_x2f
.word str_battle_x30
.word str_battle_x31
.word str_battle_x32
.word str_battle_x33
.word str_battle_x34
.word str_battle_x35
.word str_battle_x36
.word str_battle_x37
.word str_battle_x38
.word str_battle_x39
.word str_battle_x3a
.word str_battle_x3b
.word str_battle_x3c
.word str_battle_x3d
.word str_battle_x3e
.word str_battle_x3f
.word str_battle_x40
.word str_battle_x41
.word str_battle_x42
.word str_battle_x43
.word str_battle_x44
.word str_battle_x45
.word str_battle_x46
.word str_battle_x47
.word str_battle_x48
.word str_battle_x49
.word str_battle_x4a
.word str_battle_x4b
.word str_battle_x4c
.word str_battle_x4d
.word str_battle_x4e
.word str_battle_x4f
.word str_battle_x50
.word str_battle_x51
.word str_battle_x52
.word str_battle_x53
.word str_battle_x54
.word str_battle_x55
.word str_battle_x56
.word str_battle_x57
.word str_battle_x58
.word str_battle_x59
.word str_battle_x5a
.word str_battle_x5b
.word str_battle_x5c
.word str_battle_x5d
.word str_battle_x5e
.word str_battle_x5f
.word str_battle_x60
.word str_battle_x61
.word str_battle_x62
.word str_battle_x63
.word str_battle_x64
.word str_battle_x65
.word str_battle_x66
.word str_battle_x67
.word str_battle_x68
.word str_battle_x69
.word str_battle_x6a
.word str_battle_x6b
.word str_battle_x6c
.word str_battle_x6d
.word str_battle_x6e
.word str_battle_x6f
.word str_battle_x70
.word str_battle_x71
.word str_battle_x72
.word str_battle_x73
.word str_battle_x74
.word str_battle_x75
.word str_battle_x76
.word str_battle_x77
.word str_battle_x78
.word str_battle_x79
.word str_battle_x7a
.word str_battle_x7b
.word str_battle_x7c
.word str_battle_x7d
.word str_battle_x7e
.word str_battle_x7f
.word str_battle_x80
.word str_battle_x81
.word str_battle_x82
.word str_battle_x83
.word str_battle_x84
.word str_battle_x85
.word str_battle_x86
.word str_battle_x87
.word str_battle_x88
.word str_battle_x89
.word str_battle_x8a
.word str_battle_x8b
.word str_battle_x8c
.word str_battle_x8d
.word str_battle_x8e
.word str_battle_x8f
.word str_battle_x90
.word str_battle_x91
.word str_battle_x92
.word str_battle_x93
.word str_battle_x94
.word str_battle_x95
.word str_battle_x96
.word str_battle_x97
.word str_battle_x98
.word str_battle_x99
.word str_battle_x9a
.word str_battle_x9b
.word str_battle_x9c
.word str_battle_x9d
.word str_battle_x9e
.word str_battle_x9f
.word str_battle_xa0
.word str_battle_xa1
.word str_battle_xa2
.word str_battle_xa3
.word str_battle_xa4
.word str_battle_xa5
.word str_battle_xa6
.word str_battle_xa7
.word str_battle_xa8
.word str_battle_xa9
.word str_battle_xaa
.word str_battle_xab
.word str_battle_xac
.word str_battle_xad
.word str_battle_xae
.word str_battle_xaf
.word str_battle_xb0
.word str_battle_xb1
.word str_battle_xb2
.word str_battle_xb3
.word str_battle_xb4
.word str_battle_xb5
.word str_battle_xb6
.word str_battle_xb7
.word str_battle_xb8
.word str_battle_xb9
.word str_battle_xba
.word str_battle_xbb
.word str_battle_xbc
.word str_battle_xbd
.word str_battle_xbe
.word str_battle_xbf
.word str_battle_xc0
.word str_battle_xc1
.word str_battle_xc2
.word str_battle_xc3
.word str_battle_xc4
.word str_battle_xc5
.word str_battle_xc6
.word str_battle_xc7
.word str_battle_xc8
.word str_battle_xc9
.word str_battle_xca
.word str_battle_xcb
.word str_battle_xcc
.word str_battle_xcd
.word str_battle_xce
.word str_battle_xcf
.word str_battle_xd0
.word str_battle_xd1
.word str_battle_xd2
.word str_battle_xd3
.word str_battle_xd4
.word str_battle_xd5
.word str_battle_xd6
.word str_battle_xd7
.word str_battle_xd8
.word str_battle_xd9
.word str_battle_xda
.word str_battle_xdb
.word str_battle_xdc
.word str_battle_xdd
.word str_battle_xde
.word str_battle_xdf
.word str_battle_xe0
.word str_battle_xe1
.word str_battle_xe2
.word str_battle_xe3
.word str_battle_xe4
.word str_battle_xe5
.word str_battle_xe6
.word str_battle_xe7
.word str_battle_xe8
.word str_battle_xe9
.word str_battle_xea
.word str_battle_xeb
.word str_battle_xec
.word str_battle_xed
.word str_battle_xee
.word str_battle_xef
.word str_battle_xf0
.word str_battle_xf1
.word str_battle_xf2
.word str_battle_xf3
.word str_battle_xf4
.word str_battle_xf5
.word str_battle_xf6
.word str_battle_xf7
.word str_battle_xf8
.word str_battle_xf9
.word str_battle_xfa
.word str_battle_xfb
.word str_battle_xfc
.word str_battle_xfd
.word str_battle_xfe
.word str_battle_xff
.word str_battle_x100
.word str_battle_x101
.word str_battle_x102
.word str_battle_x103
.word str_battle_x104
.word str_battle_x105
.word str_battle_x106
.word str_battle_x107
.word str_battle_x108
.word str_battle_x109
.word str_battle_x10a
.word str_battle_x10b
.word str_battle_x10c
.word str_battle_x10d
.word str_battle_x10e
.word str_battle_x10f
.word str_battle_x110
.word str_battle_x111
.word str_battle_x112
.word str_battle_x113
.word str_battle_x114
.word str_battle_x115
.word str_battle_x116
.word str_battle_x117
.word str_battle_x118
.word str_battle_x119
.word str_battle_x11a
.word str_battle_x11b
.word str_battle_x11c
.word str_battle_x11d
.word str_battle_x11e
.word str_battle_x11f
.word str_battle_x120
.word str_battle_x121
.word str_battle_x122
.word str_battle_x123
.word str_battle_x124
.word str_battle_x125
.word str_battle_x126
.word str_battle_x127
.word str_battle_x128
.word str_battle_x129
.word str_battle_x12a
.word str_battle_x12b
.word str_battle_x12c
.word str_battle_x12d
.word str_battle_x12e
.word str_battle_x12f
.word str_battle_x130
.word str_battle_x131
.word str_battle_x132
.word str_battle_x133
.word str_battle_x134
.word str_battle_x135
.word str_battle_x136
.word str_battle_x137
.word str_battle_x138
.word str_battle_x139
.word str_battle_x13a
.word str_battle_x13b
.word str_battle_x13c
.word str_battle_x13d
.word str_battle_x13e
.word str_battle_x13f
.word str_battle_x140
.word str_battle_x141
.word str_battle_x142
.word str_battle_x143
.word str_battle_x144
.word str_battle_x145
.word str_battle_x146
.word str_battle_x147
.word str_battle_x148
.word str_battle_x149
.word str_battle_x14a
.word str_battle_x14b
.word str_battle_x14c
.word str_battle_x14d
.word str_battle_x14e
.word str_battle_x14f
.word str_battle_x150
.word str_battle_x151
.word str_battle_x152
.word str_battle_x153
.word str_battle_x154
.word str_battle_x155
.word str_battle_x156
.word str_battle_x157
.word str_battle_x158
.word str_battle_x159
.word str_battle_x15a
.word str_battle_x15b
.word str_battle_x15c
.word str_battle_x15d
.word str_battle_x15e
.word str_battle_x15f
.word str_battle_x160
.word str_battle_x161
.word str_battle_x162
.word str_battle_x163
.word str_battle_x164
.word str_battle_x165
.word str_battle_x166
.word str_battle_x167
.word str_battle_x168
.word str_battle_x169
.word str_battle_x16a
.word str_battle_x16b
.word str_battle_x16c
.word str_battle_x16d
.word str_battle_x16e
.word str_battle_x16f
.word str_battle_x170
.word str_battle_x171
.word str_battle_x172
.word str_battle_x173
.word str_battle_x174
.word str_battle_x175
.word str_battle_x176
.word str_battle_x177
.word str_battle_x178
.word str_battle_x179
.word str_battle_x17a
.word str_battle_x17b
.word str_battle_x17c
.word str_battle_x17d
.word str_battle_x17e
.word str_battle_x17f
.word str_battle_x180
.word str_battle_x181
.word str_battle_x182
.word str_battle_x183
.word str_battle_x184
.word str_battle_x185
.word str_battle_x186
.word str_battle_x187
.word str_battle_x188
.word str_battle_x189
.word str_battle_x18a
.word str_battle_x18b
.word str_battle_x18c
.word str_battle_x18d
.word str_battle_x18e
.word str_battle_x18f
.word str_battle_x190
.word str_battle_x191
.word str_battle_x192