.global attack_descriptions


.align 4
attack_descriptions:
	.word str_attack_desc_attack_pfund
	.word str_attack_desc_attack_karateschlag
	.word str_attack_desc_attack_duplexhieb
	.word str_attack_desc_attack_kometenhieb
	.word str_attack_desc_attack_megahieb
	.word str_attack_desc_attack_zahltag
	.word str_attack_desc_attack_feuerschlag
	.word str_attack_desc_attack_eishieb
	.word str_attack_desc_attack_donnerschlag
	.word str_attack_desc_attack_kratzer
	.word str_attack_desc_attack_klammer
	.word str_attack_desc_attack_guillotine
	.word str_attack_desc_attack_klingensturm
	.word str_attack_desc_attack_schwerttanz
	.word str_attack_desc_attack_zerschneider
	.word str_attack_desc_attack_windstoss
	.word str_attack_desc_attack_fluegelschlag
	.word str_attack_desc_attack_wirbelwind
	.word str_attack_desc_attack_fliegen
	.word str_attack_desc_attack_klammergriff
	.word str_attack_desc_attack_slam
	.word str_attack_desc_attack_rankenhieb
	.word str_attack_desc_attack_stampfer
	.word str_attack_desc_attack_doppelkick
	.word str_attack_desc_attack_megakick
	.word str_attack_desc_attack_sprungkick
	.word str_attack_desc_attack_fegekick
	.word str_attack_desc_attack_sandwirbel
	.word str_attack_desc_attack_kopfnuss
	.word str_attack_desc_attack_hornattacke
	.word str_attack_desc_attack_furienschlag
	.word str_attack_desc_attack_hornbohrer
	.word str_attack_desc_attack_tackle
	.word str_attack_desc_attack_bodyslam
	.word str_attack_desc_attack_wickel
	.word str_attack_desc_attack_bodychek
	.word str_attack_desc_attack_fuchtler
	.word str_attack_desc_attack_risikotackle
	.word str_attack_desc_attack_rutenschlag
	.word str_attack_desc_attack_giftstachel
	.word str_attack_desc_attack_duonadel
	.word str_attack_desc_attack_nadelrakete
	.word str_attack_desc_attack_silberblick
	.word str_attack_desc_attack_biss
	.word str_attack_desc_attack_heuler
	.word str_attack_desc_attack_brueller
	.word str_attack_desc_attack_gesang
	.word str_attack_desc_attack_superschall
	.word str_attack_desc_attack_ultraschall
	.word str_attack_desc_attack_aussetzer
	.word str_attack_desc_attack_saeure
	.word str_attack_desc_attack_glut
	.word str_attack_desc_attack_flammenwurf
	.word str_attack_desc_attack_weissnebel
	.word str_attack_desc_attack_aquaknarre
	.word str_attack_desc_attack_hydropumpe
	.word str_attack_desc_attack_surfer
	.word str_attack_desc_attack_eisstrahl
	.word str_attack_desc_attack_blizzard
	.word str_attack_desc_attack_psystrahl
	.word str_attack_desc_attack_blubbstrahl
	.word str_attack_desc_attack_aurorastrahl
	.word str_attack_desc_attack_hyperstrahl
	.word str_attack_desc_attack_schnabel
	.word str_attack_desc_attack_bohrschnabel
	.word str_attack_desc_attack_ueberroller
	.word str_attack_desc_attack_fusskick
	.word str_attack_desc_attack_fausthieb
	.word str_attack_desc_attack_geowurf
	.word str_attack_desc_attack_staerke
	.word str_attack_desc_attack_absorber
	.word str_attack_desc_attack_megasauger
	.word str_attack_desc_attack_egelsamen
	.word str_attack_desc_attack_wachstum
	.word str_attack_desc_attack_rasierblatt
	.word str_attack_desc_attack_solarstrahl
	.word str_attack_desc_attack_giftpuder
	.word str_attack_desc_attack_stachelspore
	.word str_attack_desc_attack_schlafpuder
	.word str_attack_desc_attack_blaettertanz
	.word str_attack_desc_attack_fadenschuss
	.word str_attack_desc_attack_drachenwut
	.word str_attack_desc_attack_feuerwirbel
	.word str_attack_desc_attack_donnerschock
	.word str_attack_desc_attack_donnerblitz
	.word str_attack_desc_attack_donnerwelle
	.word str_attack_desc_attack_donner
	.word str_attack_desc_attack_steinwurf
	.word str_attack_desc_attack_erdbeben
	.word str_attack_desc_attack_geofissur
	.word str_attack_desc_attack_schaufler
	.word str_attack_desc_attack_toxin
	.word str_attack_desc_attack_konfusion
	.word str_attack_desc_attack_psychokinese
	.word str_attack_desc_attack_hypnose
	.word str_attack_desc_attack_meditation
	.word str_attack_desc_attack_agilitaet
	.word str_attack_desc_attack_ruckzuckhieb
	.word str_attack_desc_attack_raserei
	.word str_attack_desc_attack_teleport
	.word str_attack_desc_attack_nachtnebel
	.word str_attack_desc_attack_mimikry
	.word str_attack_desc_attack_kreideschrei
	.word str_attack_desc_attack_doppelteam
	.word str_attack_desc_attack_genesung
	.word str_attack_desc_attack_haertner
	.word str_attack_desc_attack_komprimator
	.word str_attack_desc_attack_rauchwolke
	.word str_attack_desc_attack_konfustrahl
	.word str_attack_desc_attack_panzerschutz
	.word str_attack_desc_attack_einigler
	.word str_attack_desc_attack_barriere
	.word str_attack_desc_attack_lichtschild
	.word str_attack_desc_attack_dunkelnebel
	.word str_attack_desc_attack_reflektor
	.word str_attack_desc_attack_energiefokus
	.word str_attack_desc_attack_geduld
	.word str_attack_desc_attack_metronom
	.word str_attack_desc_attack_spiegeltrick
	.word str_attack_desc_attack_finale
	.word str_attack_desc_attack_eierbombe
	.word str_attack_desc_attack_schlecker
	.word str_attack_desc_attack_smog
	.word str_attack_desc_attack_schlammbad
	.word str_attack_desc_attack_knochenkeule
	.word str_attack_desc_attack_feuersturm
	.word str_attack_desc_attack_kaskade
	.word str_attack_desc_attack_schnapper
	.word str_attack_desc_attack_sternschauer
	.word str_attack_desc_attack_schaedelwumme
	.word str_attack_desc_attack_dornkanone
	.word str_attack_desc_attack_umklammerung
	.word str_attack_desc_attack_amnesie
	.word str_attack_desc_attack_psykraft
	.word str_attack_desc_attack_weichei
	.word str_attack_desc_attack_turmkick
	.word str_attack_desc_attack_giftblick
	.word str_attack_desc_attack_traumfresser
	.word str_attack_desc_attack_giftwolke
	.word str_attack_desc_attack_stakkato
	.word str_attack_desc_attack_blutsauger
	.word str_attack_desc_attack_todeskuss
	.word str_attack_desc_attack_himmelsfeger
	.word str_attack_desc_attack_wandler
	.word str_attack_desc_attack_blubber
	.word str_attack_desc_attack_irrschlag
	.word str_attack_desc_attack_pilzspore
	.word str_attack_desc_attack_blitz
	.word str_attack_desc_attack_psywelle
	.word str_attack_desc_attack_platscher
	.word str_attack_desc_attack_saeurepanzer
	.word str_attack_desc_attack_krabbhammer
	.word str_attack_desc_attack_explosion
	.word str_attack_desc_attack_kratzfurie
	.word str_attack_desc_attack_knochmerang
	.word str_attack_desc_attack_erholung
	.word str_attack_desc_attack_steinhagel
	.word str_attack_desc_attack_hyperzahn
	.word str_attack_desc_attack_schaerfer
	.word str_attack_desc_attack_umwandlung
	.word str_attack_desc_attack_triplette
	.word str_attack_desc_attack_superzahn
	.word str_attack_desc_attack_schlitzer
	.word str_attack_desc_attack_delegator
	.word str_attack_desc_attack_verzweifler
	.word str_attack_desc_attack_nachahmer
	.word str_attack_desc_attack_dreifachkick
	.word str_attack_desc_attack_raub
	.word str_attack_desc_attack_spinnennetz
	.word str_attack_desc_attack_willensleser
	.word str_attack_desc_attack_nachtmahr
	.word str_attack_desc_attack_flammenrad
	.word str_attack_desc_attack_schnarcher
	.word str_attack_desc_attack_fluch
	.word str_attack_desc_attack_dreschflegel
	.word str_attack_desc_attack_unwandlung2
	.word str_attack_desc_attack_luftstoss
	.word str_attack_desc_attack_baumwollsaat
	.word str_attack_desc_attack_gegenschlag
	.word str_attack_desc_attack_groll
	.word str_attack_desc_attack_pulverschnee
	.word str_attack_desc_attack_schutzschild
	.word str_attack_desc_attack_tempohieb
	.word str_attack_desc_attack_grimasse
	.word str_attack_desc_attack_finte
	.word str_attack_desc_attack_bitterkuss
	.word str_attack_desc_attack_bauchtrommel
	.word str_attack_desc_attack_matschbombe
	.word str_attack_desc_attack_lehmschelle
	.word str_attack_desc_attack_octazooka
	.word str_attack_desc_attack_stachler
	.word str_attack_desc_attack_blitzkanone
	.word str_attack_desc_attack_gesichte
	.word str_attack_desc_attack_abgangsbund
	.word str_attack_desc_attack_abgesang
	.word str_attack_desc_attack_eissturm
	.word str_attack_desc_attack_scanner
	.word str_attack_desc_attack_knochenhatz
	.word str_attack_desc_attack_zielschuss
	.word str_attack_desc_attack_wutanfall
	.word str_attack_desc_attack_sandsturm
	.word str_attack_desc_attack_gigasauger
	.word str_attack_desc_attack_ausdauer
	.word str_attack_desc_attack_charme
	.word str_attack_desc_attack_walzer
	.word str_attack_desc_attack_trugschlag
	.word str_attack_desc_attack_angeberei
	.word str_attack_desc_attack_milchgetraenk
	.word str_attack_desc_attack_funkensprung
	.word str_attack_desc_attack_zornklinge
	.word str_attack_desc_attack_stahlfluegel
	.word str_attack_desc_attack_horrorblick
	.word str_attack_desc_attack_anziehung
	.word str_attack_desc_attack_schlafrede
	.word str_attack_desc_attack_vitalglocke
	.word str_attack_desc_attack_rueckkehr
	.word str_attack_desc_attack_geschenk
	.word str_attack_desc_attack_frustration
	.word str_attack_desc_attack_bodyguard
	.word str_attack_desc_attack_leidteiler
	.word str_attack_desc_attack_laeuterfeuer
	.word str_attack_desc_attack_intensitaet
	.word str_attack_desc_attack_wuchtschlag
	.word str_attack_desc_attack_vielender
	.word str_attack_desc_attack_feuerodem
	.word str_attack_desc_attack_staffette
	.word str_attack_desc_attack_zugabe
	.word str_attack_desc_attack_verfolgung
	.word str_attack_desc_attack_turbodreher
	.word str_attack_desc_attack_lockduft
	.word str_attack_desc_attack_eisenschweif
	.word str_attack_desc_attack_metallklaue
	.word str_attack_desc_attack_ueberwurf
	.word str_attack_desc_attack_morgengrauen
	.word str_attack_desc_attack_synthese
	.word str_attack_desc_attack_mondschein
	.word str_attack_desc_attack_innere_kraft
	.word str_attack_desc_attack_kreuzhieb
	.word str_attack_desc_attack_windhose
	.word str_attack_desc_attack_regentanz
	.word str_attack_desc_attack_sonnentag
	.word str_attack_desc_attack_knirscher
	.word str_attack_desc_attack_fokuswelle
	.word str_attack_desc_attack_psycho_plus
	.word str_attack_desc_attack_turbotempo
	.word str_attack_desc_attack_antik_kraft
	.word str_attack_desc_attack_spukball
	.word str_attack_desc_attack_seher
	.word str_attack_desc_attack_zertruemmerer
	.word str_attack_desc_attack_whirlpool
	.word str_attack_desc_attack_pruegler
	.word str_attack_desc_attack_mogelhieb
	.word str_attack_desc_attack_aufruhr
	.word str_attack_desc_attack_horter
	.word str_attack_desc_attack_entfessler
	.word str_attack_desc_attack_verzehrer
	.word str_attack_desc_attack_hitzewelle
	.word str_attack_desc_attack_hagelsturm
	.word str_attack_desc_attack_folterknecht
	.word str_attack_desc_attack_schmeichler
	.word str_attack_desc_attack_irrlicht
	.word str_attack_desc_attack_memento_mori
	.word str_attack_desc_attack_fassade
	.word str_attack_desc_attack_power_punch
	.word str_attack_desc_attack_riechsalz
	.word str_attack_desc_attack_spotlight
	.word str_attack_desc_attack_natur_kraft
	.word str_attack_desc_attack_ladevorgang
	.word str_attack_desc_attack_verhoehner
	.word str_attack_desc_attack_rechte_hand
	.word str_attack_desc_attack_trickbetrug
	.word str_attack_desc_attack_rollentausch
	.word str_attack_desc_attack_wunschtraum
	.word str_attack_desc_attack_zuschuss
	.word str_attack_desc_attack_verwurzler
	.word str_attack_desc_attack_kraftkoloss
	.word str_attack_desc_attack_magiemantel
	.word str_attack_desc_attack_aufbereitung
	.word str_attack_desc_attack_vergeltung
	.word str_attack_desc_attack_durchbruch
	.word str_attack_desc_attack_gaehner
	.word str_attack_desc_attack_abschlag
	.word str_attack_desc_attack_notsituation
	.word str_attack_desc_attack_eruption
	.word str_attack_desc_attack_wertwechsel
	.word str_attack_desc_attack_begrenzer
	.word str_attack_desc_attack_heilung
	.word str_attack_desc_attack_nachspiel
	.word str_attack_desc_attack_uebernahme
	.word str_attack_desc_attack_geheimpower
	.word str_attack_desc_attack_taucher
	.word str_attack_desc_attack_armstoss
	.word str_attack_desc_attack_tarnung
	.word str_attack_desc_attack_schweifglanz
	.word str_attack_desc_attack_scheinwerfer
	.word str_attack_desc_attack_nebelball
	.word str_attack_desc_attack_daunenreigen
	.word str_attack_desc_attack_taumeltanz
	.word str_attack_desc_attack_feuerfeger
	.word str_attack_desc_attack_lehmsuhler
	.word str_attack_desc_attack_frostbeule
	.word str_attack_desc_attack_nietenranke
	.word str_attack_desc_attack_tagedieb
	.word str_attack_desc_attack_schallwelle
	.word str_attack_desc_attack_giftzahn
	.word str_attack_desc_attack_zermalmklaue
	.word str_attack_desc_attack_lohekanonade
	.word str_attack_desc_attack_aquahaubitze
	.word str_attack_desc_attack_sternhieb
	.word str_attack_desc_attack_erstauner
	.word str_attack_desc_attack_meteorologe
	.word str_attack_desc_attack_aromakur
	.word str_attack_desc_attack_trugtraene
	.word str_attack_desc_attack_windschnitt
	.word str_attack_desc_attack_hitzekoller
	.word str_attack_desc_attack_schnueffler
	.word str_attack_desc_attack_felsgrab
	.word str_attack_desc_attack_silberhauch
	.word str_attack_desc_attack_metallsound
	.word str_attack_desc_attack_grasfloete
	.word str_attack_desc_attack_spasskanone
	.word str_attack_desc_attack_kosmik_kraft
	.word str_attack_desc_attack_fontraenen
	.word str_attack_desc_attack_ampelleuchte
	.word str_attack_desc_attack_finsterfaust
	.word str_attack_desc_attack_sondersensor
	.word str_attack_desc_attack_himmelhieb
	.word str_attack_desc_attack_sandgrab
	.word str_attack_desc_attack_eiseskaelte
	.word str_attack_desc_attack_lehmbruehe
	.word str_attack_desc_attack_kugelsaat
	.word str_attack_desc_attack_aero_ass
	.word str_attack_desc_attack_eisspeer
	.word str_attack_desc_attack_eisenabwehr
	.word str_attack_desc_attack_rueckentzug
	.word str_attack_desc_attack_jauler
	.word str_attack_desc_attack_drachenklaue
	.word str_attack_desc_attack_fauna_statue
	.word str_attack_desc_attack_protzer
	.word str_attack_desc_attack_sprungfeder
	.word str_attack_desc_attack_lehmschuss
	.word str_attack_desc_attack_giftschweif
	.word str_attack_desc_attack_bezirzer
	.word str_attack_desc_attack_volttackle
	.word str_attack_desc_attack_zauberblatt
	.word str_attack_desc_attack_nassmacher
	.word str_attack_desc_attack_gedankengut
	.word str_attack_desc_attack_laubklinge
	.word str_attack_desc_attack_drachentanz
	.word str_attack_desc_attack_felswurf
	.word str_attack_desc_attack_schockwelle
	.word str_attack_desc_attack_aquawelle
	.word str_attack_desc_attack_kismetwunsch
	.word str_attack_desc_attack_psyschub
	.word str_attack_desc_attack_filler
	.word str_attack_desc_attack_hammerarm
	.word str_attack_desc_attack_aurasphaere
	.word str_attack_desc_attack_gifthieb
	.word str_attack_desc_attack_fokusstoss
	.word str_attack_desc_attack_patronenhieb
	.word str_attack_desc_attack_finsteraura
	.word str_attack_desc_attack_flammenblitz
	.word str_attack_desc_attack_eiszahn
	.word str_attack_desc_attack_donnerzahn
	.word str_attack_desc_attack_dunkelklaue
	.word str_attack_desc_attack_kreuzschere
	.word str_attack_desc_attack_steinkante
	.word str_attack_desc_attack_sturzflug
	.word str_attack_desc_attack_steinpolitur
	.word str_attack_desc_attack_kraxler
	.word str_attack_desc_attack_blaettersturm
	.word str_attack_desc_attack_nahkampf
	.word str_attack_desc_attack_lichtkanone
	.word str_attack_desc_attack_draco_meteor
	.word str_attack_desc_attack_nasschweif
	.word str_attack_desc_attack_zen_kopfstoss
	.word str_attack_desc_attack_energieball
	.word str_attack_desc_attack_schattenstoss
	.word str_attack_desc_attack_doppelschlag
	.word str_attack_desc_attack_tiefschlag
	.word str_attack_desc_attack_nachthieb
	.word str_attack_desc_attack_samenbombe
	.word str_attack_desc_attack_erdkraefte
	.word str_attack_desc_attack_drachenpuls
	.word str_attack_desc_attack_eissplitter
	.word str_attack_desc_attack_feuerzahn
	.word str_attack_desc_attack_wasserduese
	.word str_attack_desc_attack_zornfeuer
	.word str_attack_desc_attack_tsunami
	.word str_attack_desc_attack_stahlstreich
	.word str_attack_desc_attack_kinesiswelle
	.word str_attack_desc_attack_supernova
	.word str_attack_desc_attack_wasserspalt
	.word str_attack_desc_attack_schallstich
	.word str_attack_desc_attack_diebeskuss
	.word str_attack_desc_attack_knuddler
	.word str_attack_desc_attack_mondgewalt
	.word str_attack_desc_attack_zauberschein
	.word str_attack_desc_attack_saeuselstimme
	.word str_attack_desc_attack_bienenstich
	.word str_attack_desc_attack_schwarmstich
	.word str_attack_desc_attack_gesang_2
	.word str_attack_desc_attack_heissstein
	.word str_attack_desc_attack_gewitter
	.word str_attack_desc_attack_eisenslam
	.word str_attack_desc_attack_holzgeweih
	.word str_attack_desc_attack_kaeferbiss
	.word str_attack_desc_attack_falterreigen
	.word str_attack_desc_attack_nitroladung
	.word str_attack_desc_attack_kaefergebrumm
	.word str_attack_desc_attack_tornado
	.word str_attack_desc_attack_koenigsschild
