#include "types.h"
#include "basestats.h"
#include "pstring.h"
#include "attack.h"

u8 attack_names[ATTACK_CNT][13] = {
    	// ATTACK_NONE
	{PCHAR_MINUS,0xff,0,0,0,0,0,0,0,0,0,0,0},
	// ATTACK_PFUND
	{PCHAR_P,PCHAR_f,PCHAR_u,PCHAR_n,PCHAR_d,0xff,0,0,0,0,0,0,0},
	// ATTACK_KARATESCHLAG
	{PCHAR_K,PCHAR_a,PCHAR_r,PCHAR_a,PCHAR_t,PCHAR_e,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff},
	// ATTACK_DUPLEXHIEB
	{PCHAR_D,PCHAR_u,PCHAR_p,PCHAR_l,PCHAR_e,PCHAR_x,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0},
	// ATTACK_KOMETENHIEB
	{PCHAR_K,PCHAR_o,PCHAR_m,PCHAR_e,PCHAR_t,PCHAR_e,PCHAR_n,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0},
	// ATTACK_MEGAHIEB
	{PCHAR_M,PCHAR_e,PCHAR_g,PCHAR_a,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0,0},
	// ATTACK_ZAHLTAG
	{PCHAR_Z,PCHAR_a,PCHAR_h,PCHAR_l,PCHAR_t,PCHAR_a,PCHAR_g,0xff,0,0,0,0,0},
	// ATTACK_FEUERSCHLAG
	{PCHAR_F,PCHAR_e,PCHAR_u,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff,0},
	// ATTACK_EISHIEB
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0,0,0},
	// ATTACK_DONNERSCHLAG
	{PCHAR_D,PCHAR_o,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff},
	// ATTACK_KRATZER
	{PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_t,PCHAR_z,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_KLAMMER
	{PCHAR_K,PCHAR_l,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_GUILLOTINE
	{PCHAR_G,PCHAR_u,PCHAR_i,PCHAR_l,PCHAR_l,PCHAR_o,PCHAR_t,PCHAR_i,PCHAR_n,PCHAR_e,0xff,0,0},
	// ATTACK_KLINGENSTURM
	{PCHAR_K,PCHAR_l,PCHAR_i,PCHAR_n,PCHAR_g,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_t,PCHAR_u,PCHAR_r,PCHAR_m,0xff},
	// ATTACK_SCHWERTTANZ
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_w,PCHAR_e,PCHAR_r,PCHAR_t,PCHAR_t,PCHAR_a,PCHAR_n,PCHAR_z,0xff,0},
	// ATTACK_ZERSCHNEIDER
	{PCHAR_Z,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_n,PCHAR_e,PCHAR_i,PCHAR_d,PCHAR_e,PCHAR_r,0xff},
	// ATTACK_WINDSTOSS
	{PCHAR_W,PCHAR_i,PCHAR_n,PCHAR_d,PCHAR_s,PCHAR_t,PCHAR_o,0x15,0xff,0,0,0,0},
	// ATTACK_FLUEGELSCHLAG
	{PCHAR_F,PCHAR_l,PCHAR_ue,PCHAR_g,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff},
	// ATTACK_WIRBELWIND
	{PCHAR_W,PCHAR_i,PCHAR_r,PCHAR_b,PCHAR_e,PCHAR_l,PCHAR_w,PCHAR_i,PCHAR_n,PCHAR_d,0xff,0,0},
	// ATTACK_FLIEGEN
	{PCHAR_F,PCHAR_l,PCHAR_i,PCHAR_e,PCHAR_g,PCHAR_e,PCHAR_n,0xff,0,0,0,0,0},
	// ATTACK_KLAMMERGRIFF
	{PCHAR_K,PCHAR_l,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_r,PCHAR_g,PCHAR_r,PCHAR_i,PCHAR_f,PCHAR_f,0xff},
	// ATTACK_SLAM
	{PCHAR_S,PCHAR_l,PCHAR_a,PCHAR_m,0xff,0,0,0,0,0,0,0,0},
	// ATTACK_RANKENHIEB
	{PCHAR_R,PCHAR_a,PCHAR_n,PCHAR_k,PCHAR_e,PCHAR_n,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0},
	// ATTACK_STAMPFER
	{PCHAR_S,PCHAR_t,PCHAR_a,PCHAR_m,PCHAR_p,PCHAR_f,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_DOPPELKICK
	{PCHAR_D,PCHAR_o,PCHAR_p,PCHAR_p,PCHAR_e,PCHAR_l,PCHAR_k,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0,0},
	// ATTACK_MEGAKICK
	{PCHAR_M,PCHAR_e,PCHAR_g,PCHAR_a,PCHAR_k,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0,0,0,0},
	// ATTACK_SPRUNGKICK
	{PCHAR_S,PCHAR_p,PCHAR_r,PCHAR_u,PCHAR_n,PCHAR_g,PCHAR_k,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0,0},
	// ATTACK_FEGEKICK
	{PCHAR_F,PCHAR_e,PCHAR_g,PCHAR_e,PCHAR_k,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0,0,0,0},
	// ATTACK_SANDWIRBEL
	{PCHAR_S,PCHAR_a,PCHAR_n,PCHAR_d,PCHAR_w,PCHAR_i,PCHAR_r,PCHAR_b,PCHAR_e,PCHAR_l,0xff,0,0},
	// ATTACK_KOPFNUSS
	{PCHAR_K,PCHAR_o,PCHAR_p,PCHAR_f,PCHAR_n,PCHAR_u,PCHAR_s,PCHAR_s,0xff,0,0,0,0},
	// ATTACK_HORNATTACKE
	{PCHAR_H,PCHAR_o,PCHAR_r,PCHAR_n,PCHAR_a,PCHAR_t,PCHAR_t,PCHAR_a,PCHAR_c,PCHAR_k,PCHAR_e,0xff,0},
	// ATTACK_FURIENSCHLAG
	{PCHAR_F,PCHAR_u,PCHAR_r,PCHAR_i,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff},
	// ATTACK_HORNBOHRER
	{PCHAR_H,PCHAR_o,PCHAR_r,PCHAR_n,PCHAR_b,PCHAR_o,PCHAR_h,PCHAR_r,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_TACKLE
	{PCHAR_T,PCHAR_a,PCHAR_c,PCHAR_k,PCHAR_l,PCHAR_e,0xff,0,0,0,0,0,0},
	// ATTACK_BODYSLAM
	{PCHAR_B,PCHAR_o,PCHAR_d,PCHAR_y,PCHAR_s,PCHAR_l,PCHAR_a,PCHAR_m,0xff,0,0,0,0},
	// ATTACK_WICKEL
	{PCHAR_W,PCHAR_i,PCHAR_c,PCHAR_k,PCHAR_e,PCHAR_l,0xff,0,0,0,0,0,0},
	// ATTACK_BODYCHEK
	{PCHAR_B,PCHAR_o,PCHAR_d,PCHAR_y,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_k,0xff,0,0,0,0},
	// ATTACK_FUCHTLER
	{PCHAR_F,PCHAR_u,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_RISIKOTACKLE
	{PCHAR_R,PCHAR_i,PCHAR_s,PCHAR_i,PCHAR_k,PCHAR_o,PCHAR_t,PCHAR_a,PCHAR_c,PCHAR_k,PCHAR_l,PCHAR_e,0xff},
	// ATTACK_RUTENSCHLAG
	{PCHAR_R,PCHAR_u,PCHAR_t,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff,0},
	// ATTACK_GIFTSTACHEL
	{PCHAR_G,PCHAR_i,PCHAR_f,PCHAR_t,PCHAR_s,PCHAR_t,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_l,0xff,0},
	// ATTACK_DUONADEL
	{PCHAR_D,PCHAR_u,PCHAR_o,PCHAR_n,PCHAR_a,PCHAR_d,PCHAR_e,PCHAR_l,0xff,0,0,0,0},
	// ATTACK_NADELRAKETE
	{PCHAR_N,PCHAR_a,PCHAR_d,PCHAR_e,PCHAR_l,PCHAR_r,PCHAR_a,PCHAR_k,PCHAR_e,PCHAR_t,PCHAR_e,0xff,0},
	// ATTACK_SILBERBLICK
	{PCHAR_S,PCHAR_i,PCHAR_l,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_b,PCHAR_l,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0},
	// ATTACK_BISS
	{PCHAR_B,PCHAR_i,PCHAR_s,PCHAR_s,0xff,0,0,0,0,0,0,0,0},
	// ATTACK_HEULER
	{PCHAR_H,PCHAR_e,PCHAR_u,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0,0},
	// ATTACK_BRUELLER
	{PCHAR_B,PCHAR_r,PCHAR_ue,PCHAR_l,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_GESANG
	{PCHAR_G,PCHAR_e,PCHAR_s,PCHAR_a,PCHAR_n,PCHAR_g,0xff,0,0,0,0,0,0},
	// ATTACK_SUPERSCHALL
	{PCHAR_S,PCHAR_u,PCHAR_p,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_a,PCHAR_l,PCHAR_l,0xff,0},
	// ATTACK_ULTRASCHALL
	{PCHAR_U,PCHAR_l,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_a,PCHAR_l,PCHAR_l,0xff,0},
	// ATTACK_AUSSETZER
	{PCHAR_A,PCHAR_u,PCHAR_s,PCHAR_s,PCHAR_e,PCHAR_t,PCHAR_z,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_SAEURE
	{PCHAR_S,PCHAR_ae,PCHAR_u,PCHAR_r,PCHAR_e,0xff,0,0,0,0,0,0,0},
	// ATTACK_GLUT
	{PCHAR_G,PCHAR_l,PCHAR_u,PCHAR_t,0xff,0,0,0,0,0,0,0,0},
	// ATTACK_FLAMMENWURF
	{PCHAR_F,PCHAR_l,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_n,PCHAR_w,PCHAR_u,PCHAR_r,PCHAR_f,0xff,0},
	// ATTACK_WEISSNEBEL
	{PCHAR_W,PCHAR_e,PCHAR_i,0x15,PCHAR_n,PCHAR_e,PCHAR_b,PCHAR_e,PCHAR_l,0xff,0,0,0},
	// ATTACK_AQUAKNARRE
	{PCHAR_A,PCHAR_q,PCHAR_u,PCHAR_a,PCHAR_k,PCHAR_n,PCHAR_a,PCHAR_r,PCHAR_r,PCHAR_e,0xff,0,0},
	// ATTACK_HYDROPUMPE
	{PCHAR_H,PCHAR_y,PCHAR_d,PCHAR_r,PCHAR_o,PCHAR_p,PCHAR_u,PCHAR_m,PCHAR_p,PCHAR_e,0xff,0,0},
	// ATTACK_SURFER
	{PCHAR_S,PCHAR_u,PCHAR_r,PCHAR_f,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0,0},
	// ATTACK_EISSTRAHL
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_h,PCHAR_l,0xff,0,0,0},
	// ATTACK_BLIZZARD
	{PCHAR_B,PCHAR_l,PCHAR_i,PCHAR_z,PCHAR_z,PCHAR_a,PCHAR_r,PCHAR_d,0xff,0,0,0,0},
	// ATTACK_PSYSTRAHL
	{PCHAR_P,PCHAR_s,PCHAR_y,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_h,PCHAR_l,0xff,0,0,0},
	// ATTACK_BLUBBSTRAHL
	{PCHAR_B,PCHAR_l,PCHAR_u,PCHAR_b,PCHAR_b,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_h,PCHAR_l,0xff,0},
	// ATTACK_AURORASTRAHL
	{PCHAR_A,PCHAR_u,PCHAR_r,PCHAR_o,PCHAR_r,PCHAR_a,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_h,PCHAR_l,0xff},
	// ATTACK_HYPERSTRAHL
	{PCHAR_H,PCHAR_y,PCHAR_p,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_h,PCHAR_l,0xff,0},
	// ATTACK_SCHNABEL
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_n,PCHAR_a,PCHAR_b,PCHAR_e,PCHAR_l,0xff,0,0,0,0},
	// ATTACK_BOHRSCHNABEL
	{PCHAR_B,PCHAR_o,PCHAR_h,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_n,PCHAR_a,PCHAR_b,PCHAR_e,PCHAR_l,0xff},
	// ATTACK_UEBERROLLER
	{PCHAR_UE,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_r,PCHAR_o,PCHAR_l,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_FUSSKICK
	{PCHAR_F,PCHAR_u,0x15,PCHAR_k,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0,0,0,0,0},
	// ATTACK_FAUSTHIEB
	{PCHAR_F,PCHAR_a,PCHAR_u,PCHAR_s,PCHAR_t,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0},
	// ATTACK_GEOWURF
	{PCHAR_G,PCHAR_e,PCHAR_o,PCHAR_w,PCHAR_u,PCHAR_r,PCHAR_f,0xff,0,0,0,0,0},
	// ATTACK_STAERKE
	{PCHAR_S,PCHAR_t,PCHAR_ae,PCHAR_r,PCHAR_k,PCHAR_e,0xff,0,0,0,0,0,0},
	// ATTACK_ABSORBER
	{PCHAR_A,PCHAR_b,PCHAR_s,PCHAR_o,PCHAR_r,PCHAR_b,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_MEGASAUGER
	{PCHAR_M,PCHAR_e,PCHAR_g,PCHAR_a,PCHAR_s,PCHAR_a,PCHAR_u,PCHAR_g,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_EGELSAMEN
	{PCHAR_E,PCHAR_g,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_a,PCHAR_m,PCHAR_e,PCHAR_n,0xff,0,0,0},
	// ATTACK_WACHSTUM
	{PCHAR_W,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_s,PCHAR_t,PCHAR_u,PCHAR_m,0xff,0,0,0,0},
	// ATTACK_RASIERBLATT
	{PCHAR_R,PCHAR_a,PCHAR_s,PCHAR_i,PCHAR_e,PCHAR_r,PCHAR_b,PCHAR_l,PCHAR_a,PCHAR_t,PCHAR_t,0xff,0},
	// ATTACK_SOLARSTRAHL
	{PCHAR_S,PCHAR_o,PCHAR_l,PCHAR_a,PCHAR_r,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_h,PCHAR_l,0xff,0},
	// ATTACK_GIFTPUDER
	{PCHAR_G,PCHAR_i,PCHAR_f,PCHAR_t,PCHAR_p,PCHAR_u,PCHAR_d,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_STACHELSPORE
	{PCHAR_S,PCHAR_t,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_p,PCHAR_o,PCHAR_r,PCHAR_e,0xff},
	// ATTACK_SCHLAFPUDER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_f,PCHAR_p,PCHAR_u,PCHAR_d,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_BLAETTERTANZ
	{PCHAR_B,PCHAR_l,PCHAR_ae,PCHAR_t,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_t,PCHAR_a,PCHAR_n,PCHAR_z,0xff,0},
	// ATTACK_FADENSCHUSS
	{PCHAR_F,PCHAR_a,PCHAR_d,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_u,PCHAR_s,PCHAR_s,0xff,0},
	// ATTACK_DRACHENWUT
	{PCHAR_D,PCHAR_r,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_n,PCHAR_w,PCHAR_u,PCHAR_t,0xff,0,0},
	// ATTACK_FEUERWIRBEL
	{PCHAR_F,PCHAR_e,PCHAR_u,PCHAR_e,PCHAR_r,PCHAR_w,PCHAR_i,PCHAR_r,PCHAR_b,PCHAR_e,PCHAR_l,0xff,0},
	// ATTACK_DONNERSCHOCK
	{PCHAR_D,PCHAR_o,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_o,PCHAR_c,PCHAR_k,0xff},
	// ATTACK_DONNERBLITZ
	{PCHAR_D,PCHAR_o,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_r,PCHAR_b,PCHAR_l,PCHAR_i,PCHAR_t,PCHAR_z,0xff,0},
	// ATTACK_DONNERWELLE
	{PCHAR_D,PCHAR_o,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_r,PCHAR_w,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff,0},
	// ATTACK_DONNER
	{PCHAR_D,PCHAR_o,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0,0},
	// ATTACK_STEINWURF
	{PCHAR_S,PCHAR_t,PCHAR_e,PCHAR_i,PCHAR_n,PCHAR_w,PCHAR_u,PCHAR_r,PCHAR_f,0xff,0,0,0},
	// ATTACK_ERDBEBEN
	{PCHAR_E,PCHAR_r,PCHAR_d,PCHAR_b,PCHAR_e,PCHAR_b,PCHAR_e,PCHAR_n,0xff,0,0,0,0},
	// ATTACK_GEOFISSUR
	{PCHAR_G,PCHAR_e,PCHAR_o,PCHAR_f,PCHAR_i,PCHAR_s,PCHAR_s,PCHAR_u,PCHAR_r,0xff,0,0,0},
	// ATTACK_SCHAUFLER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_a,PCHAR_u,PCHAR_f,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_TOXIN
	{PCHAR_T,PCHAR_o,PCHAR_x,PCHAR_i,PCHAR_n,0xff,0,0,0,0,0,0,0},
	// ATTACK_KONFUSION
	{PCHAR_K,PCHAR_o,PCHAR_n,PCHAR_f,PCHAR_u,PCHAR_s,PCHAR_i,PCHAR_o,PCHAR_n,0xff,0,0,0},
	// ATTACK_PSYCHOKINESE
	{PCHAR_P,PCHAR_s,PCHAR_y,PCHAR_c,PCHAR_h,PCHAR_o,PCHAR_k,PCHAR_i,PCHAR_n,PCHAR_e,PCHAR_s,PCHAR_e,0xff},
	// ATTACK_HYPNOSE
	{PCHAR_H,PCHAR_y,PCHAR_p,PCHAR_n,PCHAR_o,PCHAR_s,PCHAR_e,0xff,0,0,0,0,0},
	// ATTACK_MEDITATION
	{PCHAR_M,PCHAR_e,PCHAR_d,PCHAR_i,PCHAR_t,PCHAR_a,PCHAR_t,PCHAR_i,PCHAR_o,PCHAR_n,0xff,0,0},
	// ATTACK_AGILITAET
	{PCHAR_A,PCHAR_g,PCHAR_i,PCHAR_l,PCHAR_i,PCHAR_t,PCHAR_ae,PCHAR_t,0xff,0,0,0,0},
	// ATTACK_RUCKZUCKHIEB
	{PCHAR_R,PCHAR_u,PCHAR_c,PCHAR_k,PCHAR_z,PCHAR_u,PCHAR_c,PCHAR_k,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff},
	// ATTACK_RASEREI
	{PCHAR_R,PCHAR_a,PCHAR_s,PCHAR_e,PCHAR_r,PCHAR_e,PCHAR_i,0xff,0,0,0,0,0},
	// ATTACK_TELEPORT
	{PCHAR_T,PCHAR_e,PCHAR_l,PCHAR_e,PCHAR_p,PCHAR_o,PCHAR_r,PCHAR_t,0xff,0,0,0,0},
	// ATTACK_NACHTNEBEL
	{PCHAR_N,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_n,PCHAR_e,PCHAR_b,PCHAR_e,PCHAR_l,0xff,0,0},
	// ATTACK_MIMIKRY
	{PCHAR_M,PCHAR_i,PCHAR_m,PCHAR_i,PCHAR_k,PCHAR_r,PCHAR_y,0xff,0,0,0,0,0},
	// ATTACK_KREIDESCHREI
	{PCHAR_K,PCHAR_r,PCHAR_e,PCHAR_i,PCHAR_d,PCHAR_e,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_r,PCHAR_e,PCHAR_i,0xff},
	// ATTACK_DOPPELTEAM
	{PCHAR_D,PCHAR_o,PCHAR_p,PCHAR_p,PCHAR_e,PCHAR_l,PCHAR_t,PCHAR_e,PCHAR_a,PCHAR_m,0xff,0,0},
	// ATTACK_GENESUNG
	{PCHAR_G,PCHAR_e,PCHAR_n,PCHAR_e,PCHAR_s,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0,0,0,0},
	// ATTACK_HAERTNER
	{PCHAR_H,PCHAR_ae,PCHAR_r,PCHAR_t,PCHAR_n,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_KOMPRIMATOR
	{PCHAR_K,PCHAR_o,PCHAR_m,PCHAR_p,PCHAR_r,PCHAR_i,PCHAR_m,PCHAR_a,PCHAR_t,PCHAR_o,PCHAR_r,0xff,0},
	// ATTACK_RAUCHWOLKE
	{PCHAR_R,PCHAR_a,PCHAR_u,PCHAR_c,PCHAR_h,PCHAR_w,PCHAR_o,PCHAR_l,PCHAR_k,PCHAR_e,0xff,0,0},
	// ATTACK_KONFUSTRAHL
	{PCHAR_K,PCHAR_o,PCHAR_n,PCHAR_f,PCHAR_u,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_h,PCHAR_l,0xff,0},
	// ATTACK_PANZERSCHUTZ
	{PCHAR_P,PCHAR_a,PCHAR_n,PCHAR_z,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_u,PCHAR_t,PCHAR_z,0xff},
	// ATTACK_EINIGLER
	{PCHAR_E,PCHAR_i,PCHAR_n,PCHAR_i,PCHAR_g,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_BARRIERE
	{PCHAR_B,PCHAR_a,PCHAR_r,PCHAR_r,PCHAR_i,PCHAR_e,PCHAR_r,PCHAR_e,0xff,0,0,0,0},
	// ATTACK_LICHTSCHILD
	{PCHAR_L,PCHAR_i,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_i,PCHAR_l,PCHAR_d,0xff,0},
	// ATTACK_DUNKELNEBEL
	{PCHAR_D,PCHAR_u,PCHAR_n,PCHAR_k,PCHAR_e,PCHAR_l,PCHAR_n,PCHAR_e,PCHAR_b,PCHAR_e,PCHAR_l,0xff,0},
	// ATTACK_REFLEKTOR
	{PCHAR_R,PCHAR_e,PCHAR_f,PCHAR_l,PCHAR_e,PCHAR_k,PCHAR_t,PCHAR_o,PCHAR_r,0xff,0,0,0},
	// ATTACK_ENERGIEFOKUS
	{PCHAR_E,PCHAR_n,PCHAR_e,PCHAR_r,PCHAR_g,PCHAR_i,PCHAR_e,PCHAR_f,PCHAR_o,PCHAR_k,PCHAR_u,PCHAR_s,0xff},
	// ATTACK_GEDULD
	{PCHAR_G,PCHAR_e,PCHAR_d,PCHAR_u,PCHAR_l,PCHAR_d,0xff,0,0,0,0,0,0},
	// ATTACK_METRONOM
	{PCHAR_M,PCHAR_e,PCHAR_t,PCHAR_r,PCHAR_o,PCHAR_n,PCHAR_o,PCHAR_m,0xff,0,0,0,0},
	// ATTACK_SPIEGELTRICK
	{PCHAR_S,PCHAR_p,PCHAR_i,PCHAR_e,PCHAR_g,PCHAR_e,PCHAR_l,PCHAR_t,PCHAR_r,PCHAR_i,PCHAR_c,PCHAR_k,0xff},
	// ATTACK_FINALE
	{PCHAR_F,PCHAR_i,PCHAR_n,PCHAR_a,PCHAR_l,PCHAR_e,0xff,0,0,0,0,0,0},
	// ATTACK_EIERBOMBE
	{PCHAR_E,PCHAR_i,PCHAR_e,PCHAR_r,PCHAR_b,PCHAR_o,PCHAR_m,PCHAR_b,PCHAR_e,0xff,0,0,0},
	// ATTACK_SCHLECKER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_e,PCHAR_c,PCHAR_k,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_SMOG
	{PCHAR_S,PCHAR_m,PCHAR_o,PCHAR_g,0xff,0,0,0,0,0,0,0,0},
	// ATTACK_SCHLAMMBAD
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_b,PCHAR_a,PCHAR_d,0xff,0,0},
	// ATTACK_KNOCHENKEULE
	{PCHAR_K,PCHAR_n,PCHAR_o,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_n,PCHAR_k,PCHAR_e,PCHAR_u,PCHAR_l,PCHAR_e,0xff},
	// ATTACK_FEUERSTURM
	{PCHAR_F,PCHAR_e,PCHAR_u,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_t,PCHAR_u,PCHAR_r,PCHAR_m,0xff,0,0},
	// ATTACK_KASKADE
	{PCHAR_K,PCHAR_a,PCHAR_s,PCHAR_k,PCHAR_a,PCHAR_d,PCHAR_e,0xff,0,0,0,0,0},
	// ATTACK_SCHNAPPER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_n,PCHAR_a,PCHAR_p,PCHAR_p,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_STERNSCHAUER
	{PCHAR_S,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_n,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_a,PCHAR_u,PCHAR_e,PCHAR_r,0xff},
	// ATTACK_SCHAEDELWUMME
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_ae,PCHAR_d,PCHAR_e,PCHAR_l,PCHAR_w,PCHAR_u,PCHAR_m,PCHAR_m,PCHAR_e,0xff},
	// ATTACK_DORNKANONE
	{PCHAR_D,PCHAR_o,PCHAR_r,PCHAR_n,PCHAR_k,PCHAR_a,PCHAR_n,PCHAR_o,PCHAR_n,PCHAR_e,0xff,0,0},
	// ATTACK_UMKLAMMERUNG
	{PCHAR_U,PCHAR_m,PCHAR_k,PCHAR_l,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_r,PCHAR_u,PCHAR_n,PCHAR_g,0xff},
	// ATTACK_AMNESIE
	{PCHAR_A,PCHAR_m,PCHAR_n,PCHAR_e,PCHAR_s,PCHAR_i,PCHAR_e,0xff,0,0,0,0,0},
	// ATTACK_PSYKRAFT
	{PCHAR_P,PCHAR_s,PCHAR_y,PCHAR_k,PCHAR_r,PCHAR_a,PCHAR_f,PCHAR_t,0xff,0,0,0,0},
	// ATTACK_WEICHEI
	{PCHAR_W,PCHAR_e,PCHAR_i,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_i,0xff,0,0,0,0,0},
	// ATTACK_TURMKICK
	{PCHAR_T,PCHAR_u,PCHAR_r,PCHAR_m,PCHAR_k,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0,0,0,0},
	// ATTACK_GIFTBLICK
	{PCHAR_G,PCHAR_i,PCHAR_f,PCHAR_t,PCHAR_b,PCHAR_l,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0,0,0},
	// ATTACK_TRAUMFRESSER
	{PCHAR_T,PCHAR_r,PCHAR_a,PCHAR_u,PCHAR_m,PCHAR_f,PCHAR_r,PCHAR_e,PCHAR_s,PCHAR_s,PCHAR_e,PCHAR_r,0xff},
	// ATTACK_GIFTWOLKE
	{PCHAR_G,PCHAR_i,PCHAR_f,PCHAR_t,PCHAR_w,PCHAR_o,PCHAR_l,PCHAR_k,PCHAR_e,0xff,0,0,0},
	// ATTACK_STAKKATO
	{PCHAR_S,PCHAR_t,PCHAR_a,PCHAR_k,PCHAR_k,PCHAR_a,PCHAR_t,PCHAR_o,0xff,0,0,0,0},
	// ATTACK_BLUTSAUGER
	{PCHAR_B,PCHAR_l,PCHAR_u,PCHAR_t,PCHAR_s,PCHAR_a,PCHAR_u,PCHAR_g,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_TODESKUSS
	{PCHAR_T,PCHAR_o,PCHAR_d,PCHAR_e,PCHAR_s,PCHAR_k,PCHAR_u,PCHAR_s,PCHAR_s,0xff,0,0,0},
	// ATTACK_HIMMELSFEGER
	{PCHAR_H,PCHAR_i,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_f,PCHAR_e,PCHAR_g,PCHAR_e,PCHAR_r,0xff},
	// ATTACK_WANDLER
	{PCHAR_W,PCHAR_a,PCHAR_n,PCHAR_d,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_BLUBBER
	{PCHAR_B,PCHAR_l,PCHAR_u,PCHAR_b,PCHAR_b,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_IRRSCHLAG
	{PCHAR_I,PCHAR_r,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff,0,0,0},
	// ATTACK_PILZSPORE
	{PCHAR_P,PCHAR_i,PCHAR_l,PCHAR_z,PCHAR_s,PCHAR_p,PCHAR_o,PCHAR_r,PCHAR_e,0xff,0,0,0},
	// ATTACK_BLITZ
	{PCHAR_B,PCHAR_l,PCHAR_i,PCHAR_t,PCHAR_z,0xff,0,0,0,0,0,0,0},
	// ATTACK_PSYWELLE
	{PCHAR_P,PCHAR_s,PCHAR_y,PCHAR_w,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff,0,0,0,0},
	// ATTACK_PLATSCHER
	{PCHAR_P,PCHAR_l,PCHAR_a,PCHAR_t,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_SAEUREPANZER
	{PCHAR_S,PCHAR_ae,PCHAR_u,PCHAR_r,PCHAR_e,PCHAR_p,PCHAR_a,PCHAR_n,PCHAR_z,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_KRABBHAMMER
	{PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_b,PCHAR_b,PCHAR_h,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_EXPLOSION
	{PCHAR_E,PCHAR_x,PCHAR_p,PCHAR_l,PCHAR_o,PCHAR_s,PCHAR_i,PCHAR_o,PCHAR_n,0xff,0,0,0},
	// ATTACK_KRATZFURIE
	{PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_t,PCHAR_z,PCHAR_f,PCHAR_u,PCHAR_r,PCHAR_i,PCHAR_e,0xff,0,0},
	// ATTACK_KNOCHMERANG
	{PCHAR_K,PCHAR_n,PCHAR_o,PCHAR_c,PCHAR_h,PCHAR_m,PCHAR_e,PCHAR_r,PCHAR_a,PCHAR_n,PCHAR_g,0xff,0},
	// ATTACK_ERHOLUNG
	{PCHAR_E,PCHAR_r,PCHAR_h,PCHAR_o,PCHAR_l,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0,0,0,0},
	// ATTACK_STEINHAGEL
	{PCHAR_S,PCHAR_t,PCHAR_e,PCHAR_i,PCHAR_n,PCHAR_h,PCHAR_a,PCHAR_g,PCHAR_e,PCHAR_l,0xff,0,0},
	// ATTACK_HYPERZAHN
	{PCHAR_H,PCHAR_y,PCHAR_p,PCHAR_e,PCHAR_r,PCHAR_z,PCHAR_a,PCHAR_h,PCHAR_n,0xff,0,0,0},
	// ATTACK_SCHAERFER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_ae,PCHAR_r,PCHAR_f,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_UMWANDLUNG
	{PCHAR_U,PCHAR_m,PCHAR_w,PCHAR_a,PCHAR_n,PCHAR_d,PCHAR_l,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0,0},
	// ATTACK_TRIPLETTE
	{PCHAR_T,PCHAR_r,PCHAR_i,PCHAR_p,PCHAR_l,PCHAR_e,PCHAR_t,PCHAR_t,PCHAR_e,0xff,0,0,0},
	// ATTACK_SUPERZAHN
	{PCHAR_S,PCHAR_u,PCHAR_p,PCHAR_e,PCHAR_r,PCHAR_z,PCHAR_a,PCHAR_h,PCHAR_n,0xff,0,0,0},
	// ATTACK_SCHLITZER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_i,PCHAR_t,PCHAR_z,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_DELEGATOR
	{PCHAR_D,PCHAR_e,PCHAR_l,PCHAR_e,PCHAR_g,PCHAR_a,PCHAR_t,PCHAR_o,PCHAR_r,0xff,0,0,0},
	// ATTACK_VERZWEIFLER
	{PCHAR_V,PCHAR_e,PCHAR_r,PCHAR_z,PCHAR_w,PCHAR_e,PCHAR_i,PCHAR_f,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_NACHAHMER
	{PCHAR_N,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_a,PCHAR_h,PCHAR_m,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_DREIFACHKICK
	{PCHAR_D,PCHAR_r,PCHAR_e,PCHAR_i,PCHAR_f,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_k,PCHAR_i,PCHAR_c,PCHAR_k,0xff},
	// ATTACK_RAUB
	{PCHAR_R,PCHAR_a,PCHAR_u,PCHAR_b,0xff,0,0,0,0,0,0,0,0},
	// ATTACK_SPINNENNETZ
	{PCHAR_S,PCHAR_p,PCHAR_i,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_t,PCHAR_z,0xff,0},
	// ATTACK_WILLENSLESER
	{PCHAR_W,PCHAR_i,PCHAR_l,PCHAR_l,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_l,PCHAR_e,PCHAR_s,PCHAR_e,PCHAR_r,0xff},
	// ATTACK_NACHTMAHR
	{PCHAR_N,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_m,PCHAR_a,PCHAR_h,PCHAR_r,0xff,0,0,0},
	// ATTACK_FLAMMENRAD
	{PCHAR_F,PCHAR_l,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_n,PCHAR_r,PCHAR_a,PCHAR_d,0xff,0,0},
	// ATTACK_SCHNARCHER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_n,PCHAR_a,PCHAR_r,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_FLUCH
	{PCHAR_F,PCHAR_l,PCHAR_u,PCHAR_c,PCHAR_h,0xff,0,0,0,0,0,0,0},
	// ATTACK_DRESCHFLEGEL
	{PCHAR_D,PCHAR_r,PCHAR_e,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_f,PCHAR_l,PCHAR_e,PCHAR_g,PCHAR_e,PCHAR_l,0xff},
	// ATTACK_UNWANDLUNG2
	{PCHAR_U,PCHAR_n,PCHAR_w,PCHAR_a,PCHAR_n,PCHAR_d,PCHAR_l,PCHAR_u,PCHAR_n,PCHAR_g,PCHAR_2,0xff,0},
	// ATTACK_LUFTSTOSS
	{PCHAR_L,PCHAR_u,PCHAR_f,PCHAR_t,PCHAR_s,PCHAR_t,PCHAR_o,0x15,0xff,0,0,0,0},
	// ATTACK_BAUMWOLLSAAT
	{PCHAR_B,PCHAR_a,PCHAR_u,PCHAR_m,PCHAR_w,PCHAR_o,PCHAR_l,PCHAR_l,PCHAR_s,PCHAR_a,PCHAR_a,PCHAR_t,0xff},
	// ATTACK_GEGENSCHLAG
	{PCHAR_G,PCHAR_e,PCHAR_g,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff,0},
	// ATTACK_GROLL
	{PCHAR_G,PCHAR_r,PCHAR_o,PCHAR_l,PCHAR_l,0xff,0,0,0,0,0,0,0},
	// ATTACK_PULVERSCHNEE
	{PCHAR_P,PCHAR_u,PCHAR_l,PCHAR_v,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_n,PCHAR_e,PCHAR_e,0xff},
	// ATTACK_SCHUTZSCHILD
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_u,PCHAR_t,PCHAR_z,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_i,PCHAR_l,PCHAR_d,0xff},
	// ATTACK_TEMPOHIEB
	{PCHAR_T,PCHAR_e,PCHAR_m,PCHAR_p,PCHAR_o,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0},
	// ATTACK_GRIMASSE
	{PCHAR_G,PCHAR_r,PCHAR_i,PCHAR_m,PCHAR_a,PCHAR_s,PCHAR_s,PCHAR_e,0xff,0,0,0,0},
	// ATTACK_FINTE
	{PCHAR_F,PCHAR_i,PCHAR_n,PCHAR_t,PCHAR_e,0xff,0,0,0,0,0,0,0},
	// ATTACK_BITTERKUSS
	{PCHAR_B,PCHAR_i,PCHAR_t,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_k,PCHAR_u,PCHAR_s,PCHAR_s,0xff,0,0},
	// ATTACK_BAUCHTROMMEL
	{PCHAR_B,PCHAR_a,PCHAR_u,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_r,PCHAR_o,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_l,0xff},
	// ATTACK_MATSCHBOMBE
	{PCHAR_M,PCHAR_a,PCHAR_t,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_b,PCHAR_o,PCHAR_m,PCHAR_b,PCHAR_e,0xff,0},
	// ATTACK_LEHMSCHELLE
	{PCHAR_L,PCHAR_e,PCHAR_h,PCHAR_m,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff,0},
	// ATTACK_OCTAZOOKA
	{PCHAR_O,PCHAR_c,PCHAR_t,PCHAR_a,PCHAR_z,PCHAR_o,PCHAR_o,PCHAR_k,PCHAR_a,0xff,0,0,0},
	// ATTACK_STACHLER
	{PCHAR_S,PCHAR_t,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_BLITZKANONE
	{PCHAR_B,PCHAR_l,PCHAR_i,PCHAR_t,PCHAR_z,PCHAR_k,PCHAR_a,PCHAR_n,PCHAR_o,PCHAR_n,PCHAR_e,0xff,0},
	// ATTACK_GESICHTE
	{PCHAR_G,PCHAR_e,PCHAR_s,PCHAR_i,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_e,0xff,0,0,0,0},
	// ATTACK_ABGANGSBUND
	{PCHAR_A,PCHAR_b,PCHAR_g,PCHAR_a,PCHAR_n,PCHAR_g,PCHAR_s,PCHAR_b,PCHAR_u,PCHAR_n,PCHAR_d,0xff,0},
	// ATTACK_ABGESANG
	{PCHAR_A,PCHAR_b,PCHAR_g,PCHAR_e,PCHAR_s,PCHAR_a,PCHAR_n,PCHAR_g,0xff,0,0,0,0},
	// ATTACK_EISSTURM
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_s,PCHAR_t,PCHAR_u,PCHAR_r,PCHAR_m,0xff,0,0,0,0},
	// ATTACK_SCANNER
	{PCHAR_S,PCHAR_c,PCHAR_a,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_KNOCHENHATZ
	{PCHAR_K,PCHAR_n,PCHAR_o,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_n,PCHAR_h,PCHAR_a,PCHAR_t,PCHAR_z,0xff,0},
	// ATTACK_ZIELSCHUSS
	{PCHAR_Z,PCHAR_i,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_u,PCHAR_s,PCHAR_s,0xff,0,0},
	// ATTACK_WUTANFALL
	{PCHAR_W,PCHAR_u,PCHAR_t,PCHAR_a,PCHAR_n,PCHAR_f,PCHAR_a,PCHAR_l,PCHAR_l,0xff,0,0,0},
	// ATTACK_SANDSTURM
	{PCHAR_S,PCHAR_a,PCHAR_n,PCHAR_d,PCHAR_s,PCHAR_t,PCHAR_u,PCHAR_r,PCHAR_m,0xff,0,0,0},
	// ATTACK_GIGASAUGER
	{PCHAR_G,PCHAR_i,PCHAR_g,PCHAR_a,PCHAR_s,PCHAR_a,PCHAR_u,PCHAR_g,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_AUSDAUER
	{PCHAR_A,PCHAR_u,PCHAR_s,PCHAR_d,PCHAR_a,PCHAR_u,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_CHARME
	{PCHAR_C,PCHAR_h,PCHAR_a,PCHAR_r,PCHAR_m,PCHAR_e,0xff,0,0,0,0,0,0},
	// ATTACK_WALZER
	{PCHAR_W,PCHAR_a,PCHAR_l,PCHAR_z,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0,0},
	// ATTACK_TRUGSCHLAG
	{PCHAR_T,PCHAR_r,PCHAR_u,PCHAR_g,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff,0,0},
	// ATTACK_ANGEBEREI
	{PCHAR_A,PCHAR_n,PCHAR_g,PCHAR_e,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_e,PCHAR_i,0xff,0,0,0},
	// ATTACK_MILCHGETRAENK
	{PCHAR_M,PCHAR_i,PCHAR_l,PCHAR_c,PCHAR_h,PCHAR_g,PCHAR_e,PCHAR_t,PCHAR_r,PCHAR_ae,PCHAR_n,PCHAR_k,0xff},
	// ATTACK_FUNKENSPRUNG
	{PCHAR_F,PCHAR_u,PCHAR_n,PCHAR_k,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_p,PCHAR_r,PCHAR_u,PCHAR_n,PCHAR_g,0xff},
	// ATTACK_ZORNKLINGE
	{PCHAR_Z,PCHAR_o,PCHAR_r,PCHAR_n,PCHAR_k,PCHAR_l,PCHAR_i,PCHAR_n,PCHAR_g,PCHAR_e,0xff,0,0},
	// ATTACK_STAHLFLUEGEL
	{PCHAR_S,PCHAR_t,PCHAR_a,PCHAR_h,PCHAR_l,PCHAR_f,PCHAR_l,PCHAR_ue,PCHAR_g,PCHAR_e,PCHAR_l,0xff,0},
	// ATTACK_HORRORBLICK
	{PCHAR_H,PCHAR_o,PCHAR_r,PCHAR_r,PCHAR_o,PCHAR_r,PCHAR_b,PCHAR_l,PCHAR_i,PCHAR_c,PCHAR_k,0xff,0},
	// ATTACK_ANZIEHUNG
	{PCHAR_A,PCHAR_n,PCHAR_z,PCHAR_i,PCHAR_e,PCHAR_h,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0,0,0},
	// ATTACK_SCHLAFREDE
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_f,PCHAR_r,PCHAR_e,PCHAR_d,PCHAR_e,0xff,0,0},
	// ATTACK_VITALGLOCKE
	{PCHAR_V,PCHAR_i,PCHAR_t,PCHAR_a,PCHAR_l,PCHAR_g,PCHAR_l,PCHAR_o,PCHAR_c,PCHAR_k,PCHAR_e,0xff,0},
	// ATTACK_RUECKKEHR
	{PCHAR_R,PCHAR_ue,PCHAR_c,PCHAR_k,PCHAR_k,PCHAR_e,PCHAR_h,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_GESCHENK
	{PCHAR_G,PCHAR_e,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_n,PCHAR_k,0xff,0,0,0,0},
	// ATTACK_FRUSTRATION
	{PCHAR_F,PCHAR_r,PCHAR_u,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_t,PCHAR_i,PCHAR_o,PCHAR_n,0xff,0},
	// ATTACK_BODYGUARD
	{PCHAR_B,PCHAR_o,PCHAR_d,PCHAR_y,PCHAR_g,PCHAR_u,PCHAR_a,PCHAR_r,PCHAR_d,0xff,0,0,0},
	// ATTACK_LEIDTEILER
	{PCHAR_L,PCHAR_e,PCHAR_i,PCHAR_d,PCHAR_t,PCHAR_e,PCHAR_i,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_LAEUTERFEUER
	{PCHAR_L,PCHAR_ae,PCHAR_u,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_f,PCHAR_e,PCHAR_u,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_INTENSITAET
	{PCHAR_I,PCHAR_n,PCHAR_t,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_i,PCHAR_t,PCHAR_ae,PCHAR_t,0xff,0,0},
	// ATTACK_WUCHTSCHLAG
	{PCHAR_W,PCHAR_u,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff,0},
	// ATTACK_VIELENDER
	{PCHAR_V,PCHAR_i,PCHAR_e,PCHAR_l,PCHAR_e,PCHAR_n,PCHAR_d,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_FEUERODEM
	{PCHAR_F,PCHAR_e,PCHAR_u,PCHAR_e,PCHAR_r,PCHAR_o,PCHAR_d,PCHAR_e,PCHAR_m,0xff,0,0,0},
	// ATTACK_STAFFETTE
	{PCHAR_S,PCHAR_t,PCHAR_a,PCHAR_f,PCHAR_f,PCHAR_e,PCHAR_t,PCHAR_t,PCHAR_e,0xff,0,0,0},
	// ATTACK_ZUGABE
	{PCHAR_Z,PCHAR_u,PCHAR_g,PCHAR_a,PCHAR_b,PCHAR_e,0xff,0,0,0,0,0,0},
	// ATTACK_VERFOLGUNG
	{PCHAR_V,PCHAR_e,PCHAR_r,PCHAR_f,PCHAR_o,PCHAR_l,PCHAR_g,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0,0},
	// ATTACK_TURBODREHER
	{PCHAR_T,PCHAR_u,PCHAR_r,PCHAR_b,PCHAR_o,PCHAR_d,PCHAR_r,PCHAR_e,PCHAR_h,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_LOCKDUFT
	{PCHAR_L,PCHAR_o,PCHAR_c,PCHAR_k,PCHAR_d,PCHAR_u,PCHAR_f,PCHAR_t,0xff,0,0,0,0},
	// ATTACK_EISENSCHWEIF
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_w,PCHAR_e,PCHAR_i,PCHAR_f,0xff},
	// ATTACK_METALLKLAUE
	{PCHAR_M,PCHAR_e,PCHAR_t,PCHAR_a,PCHAR_l,PCHAR_l,PCHAR_k,PCHAR_l,PCHAR_a,PCHAR_u,PCHAR_e,0xff,0},
	// ATTACK_UEBERWURF
	{PCHAR_UE,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_w,PCHAR_u,PCHAR_r,PCHAR_f,0xff,0,0,0,0},
	// ATTACK_MORGENGRAUEN
	{PCHAR_M,PCHAR_o,PCHAR_r,PCHAR_g,PCHAR_e,PCHAR_n,PCHAR_g,PCHAR_r,PCHAR_a,PCHAR_u,PCHAR_e,PCHAR_n,0xff},
	// ATTACK_SYNTHESE
	{PCHAR_S,PCHAR_y,PCHAR_n,PCHAR_t,PCHAR_h,PCHAR_e,PCHAR_s,PCHAR_e,0xff,0,0,0,0},
	// ATTACK_MONDSCHEIN
	{PCHAR_M,PCHAR_o,PCHAR_n,PCHAR_d,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_i,PCHAR_n,0xff,0,0},
	// ATTACK_INNERE_KRAFT
	{PCHAR_I,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_r,PCHAR_e,PCHAR_SPACE,PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_f,PCHAR_t,0xff},
	// ATTACK_KREUZHIEB
	{PCHAR_K,PCHAR_r,PCHAR_e,PCHAR_u,PCHAR_z,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0},
	// ATTACK_WINDHOSE
	{PCHAR_W,PCHAR_i,PCHAR_n,PCHAR_d,PCHAR_h,PCHAR_o,PCHAR_s,PCHAR_e,0xff,0,0,0,0},
	// ATTACK_REGENTANZ
	{PCHAR_R,PCHAR_e,PCHAR_g,PCHAR_e,PCHAR_n,PCHAR_t,PCHAR_a,PCHAR_n,PCHAR_z,0xff,0,0,0},
	// ATTACK_SONNENTAG
	{PCHAR_S,PCHAR_o,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_n,PCHAR_t,PCHAR_a,PCHAR_g,0xff,0,0,0},
	// ATTACK_KNIRSCHER
	{PCHAR_K,PCHAR_n,PCHAR_i,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_FOKUSWELLE
	{PCHAR_F,PCHAR_o,PCHAR_k,PCHAR_u,PCHAR_s,PCHAR_w,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff,0,0},
	// ATTACK_PSYCHO_PLUS
	{PCHAR_P,PCHAR_s,PCHAR_y,PCHAR_c,PCHAR_h,PCHAR_o,PCHAR_MINUS,PCHAR_P,PCHAR_l,PCHAR_u,PCHAR_s,0xff,0},
	// ATTACK_TURBOTEMPO
	{PCHAR_T,PCHAR_u,PCHAR_r,PCHAR_b,PCHAR_o,PCHAR_t,PCHAR_e,PCHAR_m,PCHAR_p,PCHAR_o,0xff,0,0},
	// ATTACK_ANTIK_KRAFT
	{PCHAR_A,PCHAR_n,PCHAR_t,PCHAR_i,PCHAR_k,PCHAR_MINUS,PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_f,PCHAR_t,0xff,0},
	// ATTACK_SPUKBALL
	{PCHAR_S,PCHAR_p,PCHAR_u,PCHAR_k,PCHAR_b,PCHAR_a,PCHAR_l,PCHAR_l,0xff,0,0,0,0},
	// ATTACK_SEHER
	{PCHAR_S,PCHAR_e,PCHAR_h,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0,0,0},
	// ATTACK_ZERTRUEMMERER
	{PCHAR_Z,PCHAR_e,PCHAR_r,PCHAR_t,PCHAR_r,PCHAR_ue,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_r,PCHAR_e,PCHAR_r,0xff},
	// ATTACK_WHIRLPOOL
	{PCHAR_W,PCHAR_h,PCHAR_i,PCHAR_r,PCHAR_l,PCHAR_p,PCHAR_o,PCHAR_o,PCHAR_l,0xff,0,0,0},
	// ATTACK_PRUEGLER
	{PCHAR_P,PCHAR_r,PCHAR_ue,PCHAR_g,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_MOGELHIEB
	{PCHAR_M,PCHAR_o,PCHAR_g,PCHAR_e,PCHAR_l,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0},
	// ATTACK_AUFRUHR
	{PCHAR_A,PCHAR_u,PCHAR_f,PCHAR_r,PCHAR_u,PCHAR_h,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_HORTER
	{PCHAR_H,PCHAR_o,PCHAR_r,PCHAR_t,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0,0},
	// ATTACK_ENTFESSLER
	{PCHAR_E,PCHAR_n,PCHAR_t,PCHAR_f,PCHAR_e,PCHAR_s,PCHAR_s,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_VERZEHRER
	{PCHAR_V,PCHAR_e,PCHAR_r,PCHAR_z,PCHAR_e,PCHAR_h,PCHAR_r,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_HITZEWELLE
	{PCHAR_H,PCHAR_i,PCHAR_t,PCHAR_z,PCHAR_e,PCHAR_w,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff,0,0},
	// ATTACK_HAGELSTURM
	{PCHAR_H,PCHAR_a,PCHAR_g,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_t,PCHAR_u,PCHAR_r,PCHAR_m,0xff,0,0},
	// ATTACK_FOLTERKNECHT
	{PCHAR_F,PCHAR_o,PCHAR_l,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_k,PCHAR_n,PCHAR_e,PCHAR_c,PCHAR_h,PCHAR_t,0xff},
	// ATTACK_SCHMEICHLER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_m,PCHAR_e,PCHAR_i,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_IRRLICHT
	{PCHAR_I,PCHAR_r,PCHAR_r,PCHAR_l,PCHAR_i,PCHAR_c,PCHAR_h,PCHAR_t,0xff,0,0,0,0},
	// ATTACK_MEMENTO_MORI
	{PCHAR_M,PCHAR_e,PCHAR_m,PCHAR_e,PCHAR_n,PCHAR_t,PCHAR_o,PCHAR_MINUS,PCHAR_M,PCHAR_o,PCHAR_r,PCHAR_i,0xff},
	// ATTACK_FASSADE
	{PCHAR_F,PCHAR_a,PCHAR_s,PCHAR_s,PCHAR_a,PCHAR_d,PCHAR_e,0xff,0,0,0,0,0},
	// ATTACK_POWER_PUNCH
	{PCHAR_P,PCHAR_o,PCHAR_w,PCHAR_e,PCHAR_r,PCHAR_MINUS,PCHAR_P,PCHAR_u,PCHAR_n,PCHAR_c,PCHAR_h,0xff,0},
	// ATTACK_RIECHSALZ
	{PCHAR_R,PCHAR_i,PCHAR_e,PCHAR_c,PCHAR_h,PCHAR_s,PCHAR_a,PCHAR_l,PCHAR_z,0xff,0,0,0},
	// ATTACK_SPOTLIGHT
	{PCHAR_S,PCHAR_p,PCHAR_o,PCHAR_t,PCHAR_l,PCHAR_i,PCHAR_g,PCHAR_h,PCHAR_t,0xff,0,0,0},
	// ATTACK_NATUR_KRAFT
	{PCHAR_N,PCHAR_a,PCHAR_t,PCHAR_u,PCHAR_r,PCHAR_MINUS,PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_f,PCHAR_t,0xff,0},
	// ATTACK_LADEVORGANG
	{PCHAR_L,PCHAR_a,PCHAR_d,PCHAR_e,PCHAR_v,PCHAR_o,PCHAR_r,PCHAR_g,PCHAR_a,PCHAR_n,PCHAR_g,0xff,0},
	// ATTACK_VERHOEHNER
	{PCHAR_V,PCHAR_e,PCHAR_r,PCHAR_h,PCHAR_oe,PCHAR_h,PCHAR_n,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_RECHTE_HAND
	{PCHAR_R,PCHAR_e,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_e,PCHAR_SPACE,PCHAR_H,PCHAR_a,PCHAR_n,PCHAR_d,0xff,0},
	// ATTACK_TRICKBETRUG
	{PCHAR_T,PCHAR_r,PCHAR_i,PCHAR_c,PCHAR_k,PCHAR_b,PCHAR_e,PCHAR_t,PCHAR_r,PCHAR_u,PCHAR_g,0xff,0},
	// ATTACK_ROLLENTAUSCH
	{PCHAR_R,PCHAR_o,PCHAR_l,PCHAR_l,PCHAR_e,PCHAR_n,PCHAR_t,PCHAR_a,PCHAR_u,PCHAR_s,PCHAR_c,PCHAR_h,0xff},
	// ATTACK_WUNSCHTRAUM
	{PCHAR_W,PCHAR_u,PCHAR_n,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_r,PCHAR_a,PCHAR_u,PCHAR_m,0xff,0},
	// ATTACK_ZUSCHUSS
	{PCHAR_Z,PCHAR_u,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_u,PCHAR_s,PCHAR_s,0xff,0,0,0,0},
	// ATTACK_VERWURZLER
	{PCHAR_V,PCHAR_e,PCHAR_r,PCHAR_w,PCHAR_u,PCHAR_r,PCHAR_z,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_KRAFTKOLOSS
	{PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_f,PCHAR_t,PCHAR_k,PCHAR_o,PCHAR_l,PCHAR_o,PCHAR_s,PCHAR_s,0xff,0},
	// ATTACK_MAGIEMANTEL
	{PCHAR_M,PCHAR_a,PCHAR_g,PCHAR_i,PCHAR_e,PCHAR_m,PCHAR_a,PCHAR_n,PCHAR_t,PCHAR_e,PCHAR_l,0xff,0},
	// ATTACK_AUFBEREITUNG
	{PCHAR_A,PCHAR_u,PCHAR_f,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_e,PCHAR_i,PCHAR_t,PCHAR_u,PCHAR_n,PCHAR_g,0xff},
	// ATTACK_VERGELTUNG
	{PCHAR_V,PCHAR_e,PCHAR_r,PCHAR_g,PCHAR_e,PCHAR_l,PCHAR_t,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0,0},
	// ATTACK_DURCHBRUCH
	{PCHAR_D,PCHAR_u,PCHAR_r,PCHAR_c,PCHAR_h,PCHAR_b,PCHAR_r,PCHAR_u,PCHAR_c,PCHAR_h,0xff,0,0},
	// ATTACK_GAEHNER
	{PCHAR_G,PCHAR_ae,PCHAR_h,PCHAR_n,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0,0},
	// ATTACK_ABSCHLAG
	{PCHAR_A,PCHAR_b,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff,0,0,0,0},
	// ATTACK_NOTSITUATION
	{PCHAR_N,PCHAR_o,PCHAR_t,PCHAR_s,PCHAR_i,PCHAR_t,PCHAR_u,PCHAR_a,PCHAR_t,PCHAR_i,PCHAR_o,PCHAR_n,0xff},
	// ATTACK_ERUPTION
	{PCHAR_E,PCHAR_r,PCHAR_u,PCHAR_p,PCHAR_t,PCHAR_i,PCHAR_o,PCHAR_n,0xff,0,0,0,0},
	// ATTACK_WERTWECHSEL
	{PCHAR_W,PCHAR_e,PCHAR_r,PCHAR_t,PCHAR_w,PCHAR_e,PCHAR_c,PCHAR_h,PCHAR_s,PCHAR_e,PCHAR_l,0xff,0},
	// ATTACK_BEGRENZER
	{PCHAR_B,PCHAR_e,PCHAR_g,PCHAR_r,PCHAR_e,PCHAR_n,PCHAR_z,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_HEILUNG
	{PCHAR_H,PCHAR_e,PCHAR_i,PCHAR_l,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0,0,0,0,0},
	// ATTACK_NACHSPIEL
	{PCHAR_N,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_s,PCHAR_p,PCHAR_i,PCHAR_e,PCHAR_l,0xff,0,0,0},
	// ATTACK_UEBERNAHME
	{PCHAR_UE,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_n,PCHAR_a,PCHAR_h,PCHAR_m,PCHAR_e,0xff,0,0,0},
	// ATTACK_GEHEIMPOWER
	{PCHAR_G,PCHAR_e,PCHAR_h,PCHAR_e,PCHAR_i,PCHAR_m,PCHAR_p,PCHAR_o,PCHAR_w,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_TAUCHER
	{PCHAR_T,PCHAR_a,PCHAR_u,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_ARMSTOSS
	{PCHAR_A,PCHAR_r,PCHAR_m,PCHAR_s,PCHAR_t,PCHAR_o,0x15,0xff,0,0,0,0,0},
	// ATTACK_TARNUNG
	{PCHAR_T,PCHAR_a,PCHAR_r,PCHAR_n,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0,0,0,0,0},
	// ATTACK_SCHWEIFGLANZ
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_w,PCHAR_e,PCHAR_i,PCHAR_f,PCHAR_g,PCHAR_l,PCHAR_a,PCHAR_n,PCHAR_z,0xff},
	// ATTACK_SCHEINWERFER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_i,PCHAR_n,PCHAR_w,PCHAR_e,PCHAR_r,PCHAR_f,PCHAR_e,PCHAR_r,0xff},
	// ATTACK_NEBELBALL
	{PCHAR_N,PCHAR_e,PCHAR_b,PCHAR_e,PCHAR_l,PCHAR_b,PCHAR_a,PCHAR_l,PCHAR_l,0xff,0,0,0},
	// ATTACK_DAUNENREIGEN
	{PCHAR_D,PCHAR_a,PCHAR_u,PCHAR_n,PCHAR_e,PCHAR_n,PCHAR_r,PCHAR_e,PCHAR_i,PCHAR_g,PCHAR_e,PCHAR_n,0xff},
	// ATTACK_TAUMELTANZ
	{PCHAR_T,PCHAR_a,PCHAR_u,PCHAR_m,PCHAR_e,PCHAR_l,PCHAR_t,PCHAR_a,PCHAR_n,PCHAR_z,0xff,0,0},
	// ATTACK_FEUERFEGER
	{PCHAR_F,PCHAR_e,PCHAR_u,PCHAR_e,PCHAR_r,PCHAR_f,PCHAR_e,PCHAR_g,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_LEHMSUHLER
	{PCHAR_L,PCHAR_e,PCHAR_h,PCHAR_m,PCHAR_s,PCHAR_u,PCHAR_h,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_FROSTBEULE
	{PCHAR_F,PCHAR_r,PCHAR_o,PCHAR_s,PCHAR_t,PCHAR_b,PCHAR_e,PCHAR_u,PCHAR_l,PCHAR_e,0xff,0,0},
	// ATTACK_NIETENRANKE
	{PCHAR_N,PCHAR_i,PCHAR_e,PCHAR_t,PCHAR_e,PCHAR_n,PCHAR_r,PCHAR_a,PCHAR_n,PCHAR_k,PCHAR_e,0xff,0},
	// ATTACK_TAGEDIEB
	{PCHAR_T,PCHAR_a,PCHAR_g,PCHAR_e,PCHAR_d,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0,0},
	// ATTACK_SCHALLWELLE
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_a,PCHAR_l,PCHAR_l,PCHAR_w,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff,0},
	// ATTACK_GIFTZAHN
	{PCHAR_G,PCHAR_i,PCHAR_f,PCHAR_t,PCHAR_z,PCHAR_a,PCHAR_h,PCHAR_n,0xff,0,0,0,0},
	// ATTACK_ZERMALMKLAUE
	{PCHAR_Z,PCHAR_e,PCHAR_r,PCHAR_m,PCHAR_a,PCHAR_l,PCHAR_m,PCHAR_k,PCHAR_l,PCHAR_a,PCHAR_u,PCHAR_e,0xff},
	// ATTACK_LOHEKANONADE
	{PCHAR_L,PCHAR_o,PCHAR_h,PCHAR_e,PCHAR_k,PCHAR_a,PCHAR_n,PCHAR_o,PCHAR_n,PCHAR_a,PCHAR_d,PCHAR_e,0xff},
	// ATTACK_AQUAHAUBITZE
	{PCHAR_A,PCHAR_q,PCHAR_u,PCHAR_a,PCHAR_h,PCHAR_a,PCHAR_u,PCHAR_b,PCHAR_i,PCHAR_t,PCHAR_z,PCHAR_e,0xff},
	// ATTACK_STERNHIEB
	{PCHAR_S,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_n,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0},
	// ATTACK_ERSTAUNER
	{PCHAR_E,PCHAR_r,PCHAR_s,PCHAR_t,PCHAR_a,PCHAR_u,PCHAR_n,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_METEOROLOGE
	{PCHAR_M,PCHAR_e,PCHAR_t,PCHAR_e,PCHAR_o,PCHAR_r,PCHAR_o,PCHAR_l,PCHAR_o,PCHAR_g,PCHAR_e,0xff,0},
	// ATTACK_AROMAKUR
	{PCHAR_A,PCHAR_r,PCHAR_o,PCHAR_m,PCHAR_a,PCHAR_k,PCHAR_u,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_TRUGTRAENE
	{PCHAR_T,PCHAR_r,PCHAR_u,PCHAR_g,PCHAR_t,PCHAR_r,PCHAR_ae,PCHAR_n,PCHAR_e,0xff,0,0,0},
	// ATTACK_WINDSCHNITT
	{PCHAR_W,PCHAR_i,PCHAR_n,PCHAR_d,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_n,PCHAR_i,PCHAR_t,PCHAR_t,0xff,0},
	// ATTACK_HITZEKOLLER
	{PCHAR_H,PCHAR_i,PCHAR_t,PCHAR_z,PCHAR_e,PCHAR_k,PCHAR_o,PCHAR_l,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_SCHNUEFFLER
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_n,PCHAR_ue,PCHAR_f,PCHAR_f,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_FELSGRAB
	{PCHAR_F,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_g,PCHAR_r,PCHAR_a,PCHAR_b,0xff,0,0,0,0},
	// ATTACK_SILBERHAUCH
	{PCHAR_S,PCHAR_i,PCHAR_l,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_h,PCHAR_a,PCHAR_u,PCHAR_c,PCHAR_h,0xff,0},
	// ATTACK_METALLSOUND
	{PCHAR_M,PCHAR_e,PCHAR_t,PCHAR_a,PCHAR_l,PCHAR_l,PCHAR_s,PCHAR_o,PCHAR_u,PCHAR_n,PCHAR_d,0xff,0},
	// ATTACK_GRASFLOETE
	{PCHAR_G,PCHAR_r,PCHAR_a,PCHAR_s,PCHAR_f,PCHAR_l,PCHAR_oe,PCHAR_t,PCHAR_e,0xff,0,0,0},
	// ATTACK_SPASSKANONE
	{PCHAR_S,PCHAR_p,PCHAR_a,0x15,PCHAR_k,PCHAR_a,PCHAR_n,PCHAR_o,PCHAR_n,PCHAR_e,0xff,0,0},
	// ATTACK_KOSMIK_KRAFT
	{PCHAR_K,PCHAR_o,PCHAR_s,PCHAR_m,PCHAR_i,PCHAR_k,PCHAR_MINUS,PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_f,PCHAR_t,0xff},
	// ATTACK_FONTRAENEN
	{PCHAR_F,PCHAR_o,PCHAR_n,PCHAR_t,PCHAR_r,PCHAR_ae,PCHAR_n,PCHAR_e,PCHAR_n,0xff,0,0,0},
	// ATTACK_AMPELLEUCHTE
	{PCHAR_A,PCHAR_m,PCHAR_p,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,PCHAR_u,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_e,0xff},
	// ATTACK_FINSTERFAUST
	{PCHAR_F,PCHAR_i,PCHAR_n,PCHAR_s,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_f,PCHAR_a,PCHAR_u,PCHAR_s,PCHAR_t,0xff},
	// ATTACK_SONDERSENSOR
	{PCHAR_S,PCHAR_o,PCHAR_n,PCHAR_d,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_o,PCHAR_r,0xff},
	// ATTACK_HIMMELHIEB
	{PCHAR_H,PCHAR_i,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_l,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0},
	// ATTACK_SANDGRAB
	{PCHAR_S,PCHAR_a,PCHAR_n,PCHAR_d,PCHAR_g,PCHAR_r,PCHAR_a,PCHAR_b,0xff,0,0,0,0},
	// ATTACK_EISESKAELTE
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_e,PCHAR_s,PCHAR_k,PCHAR_ae,PCHAR_l,PCHAR_t,PCHAR_e,0xff,0,0},
	// ATTACK_LEHMBRUEHE
	{PCHAR_L,PCHAR_e,PCHAR_h,PCHAR_m,PCHAR_b,PCHAR_r,PCHAR_ue,PCHAR_h,PCHAR_e,0xff,0,0,0},
	// ATTACK_KUGELSAAT
	{PCHAR_K,PCHAR_u,PCHAR_g,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_a,PCHAR_a,PCHAR_t,0xff,0,0,0},
	// ATTACK_AERO_ASS
	{PCHAR_A,PCHAR_e,PCHAR_r,PCHAR_o,PCHAR_MINUS,PCHAR_A,PCHAR_s,PCHAR_s,0xff,0,0,0,0},
	// ATTACK_EISSPEER
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_s,PCHAR_p,PCHAR_e,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_EISENABWEHR
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_e,PCHAR_n,PCHAR_a,PCHAR_b,PCHAR_w,PCHAR_e,PCHAR_h,PCHAR_r,0xff,0},
	// ATTACK_RUECKENTZUG
	{PCHAR_R,PCHAR_ue,PCHAR_c,PCHAR_k,PCHAR_e,PCHAR_n,PCHAR_t,PCHAR_z,PCHAR_u,PCHAR_g,0xff,0,0},
	// ATTACK_JAULER
	{PCHAR_J,PCHAR_a,PCHAR_u,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0,0},
	// ATTACK_DRACHENKLAUE
	{PCHAR_D,PCHAR_r,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_n,PCHAR_k,PCHAR_l,PCHAR_a,PCHAR_u,PCHAR_e,0xff},
	// ATTACK_FAUNA_STATUE
	{PCHAR_F,PCHAR_a,PCHAR_u,PCHAR_n,PCHAR_a,PCHAR_MINUS,PCHAR_S,PCHAR_t,PCHAR_a,PCHAR_t,PCHAR_u,PCHAR_e,0xff},
	// ATTACK_PROTZER
	{PCHAR_P,PCHAR_r,PCHAR_o,PCHAR_t,PCHAR_z,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_SPRUNGFEDER
	{PCHAR_S,PCHAR_p,PCHAR_r,PCHAR_u,PCHAR_n,PCHAR_g,PCHAR_f,PCHAR_e,PCHAR_d,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_LEHMSCHUSS
	{PCHAR_L,PCHAR_e,PCHAR_h,PCHAR_m,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_u,PCHAR_s,PCHAR_s,0xff,0,0},
	// ATTACK_GIFTSCHWEIF
	{PCHAR_G,PCHAR_i,PCHAR_f,PCHAR_t,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_w,PCHAR_e,PCHAR_i,PCHAR_f,0xff,0},
	// ATTACK_BEZIRZER
	{PCHAR_B,PCHAR_e,PCHAR_z,PCHAR_i,PCHAR_r,PCHAR_z,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_VOLTTACKLE
	{PCHAR_V,PCHAR_o,PCHAR_l,PCHAR_t,PCHAR_t,PCHAR_a,PCHAR_c,PCHAR_k,PCHAR_l,PCHAR_e,0xff,0,0},
	// ATTACK_ZAUBERBLATT
	{PCHAR_Z,PCHAR_a,PCHAR_u,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_b,PCHAR_l,PCHAR_a,PCHAR_t,PCHAR_t,0xff,0},
	// ATTACK_NASSMACHER
	{PCHAR_N,PCHAR_a,PCHAR_s,PCHAR_s,PCHAR_m,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_r,0xff,0,0},
	// ATTACK_GEDANKENGUT
	{PCHAR_G,PCHAR_e,PCHAR_d,PCHAR_a,PCHAR_n,PCHAR_k,PCHAR_e,PCHAR_n,PCHAR_g,PCHAR_u,PCHAR_t,0xff,0},
	// ATTACK_LAUBKLINGE
	{PCHAR_L,PCHAR_a,PCHAR_u,PCHAR_b,PCHAR_k,PCHAR_l,PCHAR_i,PCHAR_n,PCHAR_g,PCHAR_e,0xff,0,0},
	// ATTACK_DRACHENTANZ
	{PCHAR_D,PCHAR_r,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_n,PCHAR_t,PCHAR_a,PCHAR_n,PCHAR_z,0xff,0},
	// ATTACK_FELSWURF
	{PCHAR_F,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_w,PCHAR_u,PCHAR_r,PCHAR_f,0xff,0,0,0,0},
	// ATTACK_SCHOCKWELLE
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_o,PCHAR_c,PCHAR_k,PCHAR_w,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff,0},
	// ATTACK_AQUAWELLE
	{PCHAR_A,PCHAR_q,PCHAR_u,PCHAR_a,PCHAR_w,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff,0,0,0},
	// ATTACK_KISMETWUNSCH
	{PCHAR_K,PCHAR_i,PCHAR_s,PCHAR_m,PCHAR_e,PCHAR_t,PCHAR_w,PCHAR_u,PCHAR_n,PCHAR_s,PCHAR_c,PCHAR_h,0xff},
	// ATTACK_PSYSCHUB
	{PCHAR_P,PCHAR_s,PCHAR_y,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_u,PCHAR_b,0xff,0,0,0,0},
	// ATTACK_FILLER
	{PCHAR_MINUS,0xff,0,0,0,0,0,0,0,0,0,0,0},
	// ATTACK_HAMMERARM
	{PCHAR_H,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_r,PCHAR_a,PCHAR_r,PCHAR_m,0xff,0,0,0},
	// ATTACK_AURASPHAERE
	{PCHAR_A,PCHAR_u,PCHAR_r,PCHAR_a,PCHAR_s,PCHAR_p,PCHAR_h,PCHAR_ae,PCHAR_r,PCHAR_e,0xff,0,0},
	// ATTACK_GIFTHIEB
	{PCHAR_G,PCHAR_i,PCHAR_f,PCHAR_t,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0,0},
	// ATTACK_FOKUSSTOSS
	{PCHAR_F,PCHAR_o,PCHAR_k,PCHAR_u,PCHAR_s,PCHAR_s,PCHAR_t,PCHAR_o,0x15,0xff,0,0,0},
	// ATTACK_PATRONENHIEB
	{PCHAR_P,PCHAR_a,PCHAR_t,PCHAR_r,PCHAR_o,PCHAR_n,PCHAR_e,PCHAR_n,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff},
	// ATTACK_FINSTERAURA
	{PCHAR_F,PCHAR_i,PCHAR_n,PCHAR_s,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_a,PCHAR_u,PCHAR_r,PCHAR_a,0xff,0},
	// ATTACK_FLAMMENBLITZ
	{PCHAR_F,PCHAR_l,PCHAR_a,PCHAR_m,PCHAR_m,PCHAR_e,PCHAR_n,PCHAR_b,PCHAR_l,PCHAR_i,PCHAR_t,PCHAR_z,0xff},
	// ATTACK_EISZAHN
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_z,PCHAR_a,PCHAR_h,PCHAR_n,0xff,0,0,0,0,0},
	// ATTACK_DONNERZAHN
	{PCHAR_D,PCHAR_o,PCHAR_n,PCHAR_n,PCHAR_e,PCHAR_r,PCHAR_z,PCHAR_a,PCHAR_h,PCHAR_n,0xff,0,0},
	// ATTACK_DUNKELKLAUE
	{PCHAR_D,PCHAR_u,PCHAR_n,PCHAR_k,PCHAR_e,PCHAR_l,PCHAR_k,PCHAR_l,PCHAR_a,PCHAR_u,PCHAR_e,0xff,0},
	// ATTACK_KREUZSCHERE
	{PCHAR_K,PCHAR_r,PCHAR_e,PCHAR_u,PCHAR_z,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_r,PCHAR_e,0xff,0},
	// ATTACK_STEINKANTE
	{PCHAR_S,PCHAR_t,PCHAR_e,PCHAR_i,PCHAR_n,PCHAR_k,PCHAR_a,PCHAR_n,PCHAR_t,PCHAR_e,0xff,0,0},
	// ATTACK_STURZFLUG
	{PCHAR_S,PCHAR_t,PCHAR_u,PCHAR_r,PCHAR_z,PCHAR_f,PCHAR_l,PCHAR_u,PCHAR_g,0xff,0,0,0},
	// ATTACK_STEINPOLITUR
	{PCHAR_S,PCHAR_t,PCHAR_e,PCHAR_i,PCHAR_n,PCHAR_p,PCHAR_o,PCHAR_l,PCHAR_i,PCHAR_t,PCHAR_u,PCHAR_r,0xff},
	// ATTACK_KRAXLER
	{PCHAR_K,PCHAR_r,PCHAR_a,PCHAR_x,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0,0},
	// ATTACK_BLAETTERSTURM
	{PCHAR_B,PCHAR_l,PCHAR_ae,PCHAR_t,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_t,PCHAR_u,PCHAR_r,PCHAR_m,0xff},
	// ATTACK_NAHKAMPF
	{PCHAR_N,PCHAR_a,PCHAR_h,PCHAR_k,PCHAR_a,PCHAR_m,PCHAR_p,PCHAR_f,0xff,0,0,0,0},
	// ATTACK_LICHTKANONE
	{PCHAR_L,PCHAR_i,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_k,PCHAR_a,PCHAR_n,PCHAR_o,PCHAR_n,PCHAR_e,0xff,0},
	// ATTACK_DRACO_METEOR
	{PCHAR_D,PCHAR_r,PCHAR_a,PCHAR_c,PCHAR_o,PCHAR_MINUS,PCHAR_M,PCHAR_e,PCHAR_t,PCHAR_e,PCHAR_o,PCHAR_r,0xff},
	// ATTACK_NASSCHWEIF
	{PCHAR_N,PCHAR_a,PCHAR_s,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_w,PCHAR_e,PCHAR_i,PCHAR_f,0xff,0,0},
	// ATTACK_ZEN_KOPFSTOSS
	{PCHAR_Z,PCHAR_e,PCHAR_n,PCHAR_MINUS,PCHAR_K,PCHAR_o,PCHAR_p,PCHAR_f,PCHAR_s,PCHAR_t,PCHAR_o,0x15,0xff},
	// ATTACK_ENERGIEBALL
	{PCHAR_E,PCHAR_n,PCHAR_e,PCHAR_r,PCHAR_g,PCHAR_i,PCHAR_e,PCHAR_b,PCHAR_a,PCHAR_l,PCHAR_l,0xff,0},
	// ATTACK_SCHATTENSTOSS
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_a,PCHAR_t,PCHAR_t,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_t,PCHAR_o,0x15,0xff},
	// ATTACK_DOPPELSCHLAG
	{PCHAR_D,PCHAR_o,PCHAR_p,PCHAR_p,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff},
	// ATTACK_TIEFSCHLAG
	{PCHAR_T,PCHAR_i,PCHAR_e,PCHAR_f,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_l,PCHAR_a,PCHAR_g,0xff,0,0},
	// ATTACK_NACHTHIEB
	{PCHAR_N,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_t,PCHAR_h,PCHAR_i,PCHAR_e,PCHAR_b,0xff,0,0,0},
	// ATTACK_SAMENBOMBE
	{PCHAR_S,PCHAR_a,PCHAR_m,PCHAR_e,PCHAR_n,PCHAR_b,PCHAR_o,PCHAR_m,PCHAR_b,PCHAR_e,0xff,0,0},
	// ATTACK_ERDKRAEFTE
	{PCHAR_E,PCHAR_r,PCHAR_d,PCHAR_k,PCHAR_r,PCHAR_ae,PCHAR_f,PCHAR_t,PCHAR_e,0xff,0,0,0},
	// ATTACK_DRACHENPULS
	{PCHAR_D,PCHAR_r,PCHAR_a,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_n,PCHAR_p,PCHAR_u,PCHAR_l,PCHAR_s,0xff,0},
	// ATTACK_EISSPLITTER
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_s,PCHAR_p,PCHAR_l,PCHAR_i,PCHAR_t,PCHAR_t,PCHAR_e,PCHAR_r,0xff,0},
	// ATTACK_FEUERZAHN
	{PCHAR_F,PCHAR_e,PCHAR_u,PCHAR_e,PCHAR_r,PCHAR_z,PCHAR_a,PCHAR_h,PCHAR_n,0xff,0,0,0},
	// ATTACK_WASSERDUESE
	{PCHAR_W,PCHAR_a,PCHAR_s,PCHAR_s,PCHAR_e,PCHAR_r,PCHAR_d,PCHAR_ue,PCHAR_s,PCHAR_e,0xff,0,0},
	// ATTACK_ZORNFEUER
	{PCHAR_Z,PCHAR_o,PCHAR_r,PCHAR_n,PCHAR_f,PCHAR_e,PCHAR_u,PCHAR_e,PCHAR_r,0xff,0,0,0},
	// ATTACK_TSUNAMI
	{PCHAR_T,PCHAR_s,PCHAR_u,PCHAR_n,PCHAR_a,PCHAR_m,PCHAR_i,0xff,0,0,0,0,0},
	// ATTACK_STAHLSTREICH
	{PCHAR_S,PCHAR_t,PCHAR_a,PCHAR_h,PCHAR_l,PCHAR_s,PCHAR_t,PCHAR_r,PCHAR_e,PCHAR_i,PCHAR_c,PCHAR_h,0xff},
	// ATTACK_KINESISWELLE
	{PCHAR_K,PCHAR_i,PCHAR_n,PCHAR_e,PCHAR_s,PCHAR_i,PCHAR_s,PCHAR_w,PCHAR_e,PCHAR_l,PCHAR_l,PCHAR_e,0xff},
	// ATTACK_SUPERNOVA
	{PCHAR_S,PCHAR_u,PCHAR_p,PCHAR_e,PCHAR_r,PCHAR_n,PCHAR_o,PCHAR_v,PCHAR_a,0xff,0,0,0},
	// ATTACK_WASSERSPALT
	{PCHAR_W,PCHAR_a,PCHAR_s,PCHAR_s,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_p,PCHAR_a,PCHAR_l,PCHAR_t,0xff,0},
	// ATTACK_SCHALLSTICH
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_a,PCHAR_l,PCHAR_l,PCHAR_s,PCHAR_t,PCHAR_i,PCHAR_c,PCHAR_h,0xff,0},
	// ATTACK_DIEBESKUSS
	{PCHAR_D,PCHAR_i,PCHAR_e,PCHAR_b,PCHAR_e,PCHAR_s,PCHAR_k,PCHAR_u,PCHAR_s,PCHAR_s,0xff,0,0},
	// ATTACK_KNUDDLER
	{PCHAR_K,PCHAR_n,PCHAR_u,PCHAR_d,PCHAR_d,PCHAR_l,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_MONDGEWALT
	{PCHAR_M,PCHAR_o,PCHAR_n,PCHAR_d,PCHAR_g,PCHAR_e,PCHAR_w,PCHAR_a,PCHAR_l,PCHAR_t,0xff,0,0},
	// ATTACK_ZAUBERSCHEIN
	{PCHAR_Z,PCHAR_a,PCHAR_u,PCHAR_b,PCHAR_e,PCHAR_r,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_e,PCHAR_i,PCHAR_n,0xff},
	// ATTACK_SAEUSELSTIMME
	{PCHAR_S,PCHAR_ae,PCHAR_u,PCHAR_s,PCHAR_e,PCHAR_l,PCHAR_s,PCHAR_t,PCHAR_i,PCHAR_m,PCHAR_m,PCHAR_e,0xff},
	// ATTACK_BIENENSTICH
	{PCHAR_B,PCHAR_i,PCHAR_e,PCHAR_n,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_t,PCHAR_i,PCHAR_c,PCHAR_h,0xff,0},
	// ATTACK_SCHWARMSTICH
	{PCHAR_S,PCHAR_c,PCHAR_h,PCHAR_w,PCHAR_a,PCHAR_r,PCHAR_m,PCHAR_s,PCHAR_t,PCHAR_i,PCHAR_c,PCHAR_h,0xff},
	// ATTACK_GESANG_2
	{PCHAR_G,PCHAR_E,PCHAR_S,PCHAR_A,PCHAR_N,PCHAR_G,0xff,0,0,0,0,0,0},
	// ATTACK_HEISSSTEIN
	{PCHAR_H,PCHAR_e,PCHAR_i,0x15,PCHAR_s,PCHAR_t,PCHAR_e,PCHAR_i,PCHAR_n,0xff,0,0,0},
	// ATTACK_GEWITTER
	{PCHAR_G,PCHAR_e,PCHAR_w,PCHAR_i,PCHAR_t,PCHAR_t,PCHAR_e,PCHAR_r,0xff,0,0,0,0},
	// ATTACK_EISENSLAM
	{PCHAR_E,PCHAR_i,PCHAR_s,PCHAR_e,PCHAR_n,PCHAR_s,PCHAR_l,PCHAR_a,PCHAR_m,0xff,0,0,0},
	// ATTACK_HOLZGEWEIH
	{PCHAR_H,PCHAR_o,PCHAR_l,PCHAR_z,PCHAR_g,PCHAR_e,PCHAR_w,PCHAR_e,PCHAR_i,PCHAR_h,0xff,0,0},
	// ATTACK_KAEFERBISS
	{PCHAR_K,PCHAR_ae,PCHAR_f,PCHAR_e,PCHAR_r,PCHAR_b,PCHAR_i,PCHAR_s,PCHAR_s,0xff,0,0,0},
	// ATTACK_FALTERREIGEN
	{PCHAR_F,PCHAR_a,PCHAR_l,PCHAR_t,PCHAR_e,PCHAR_r,PCHAR_r,PCHAR_e,PCHAR_i,PCHAR_g,PCHAR_e,PCHAR_n,0xff},
	// ATTACK_NITROLADUNG
	{PCHAR_N,PCHAR_i,PCHAR_t,PCHAR_r,PCHAR_o,PCHAR_l,PCHAR_a,PCHAR_d,PCHAR_u,PCHAR_n,PCHAR_g,0xff,0},
	// ATTACK_KAEFERGEBRUMM
	{PCHAR_K,PCHAR_ae,PCHAR_f,PCHAR_e,PCHAR_r,PCHAR_g,PCHAR_e,PCHAR_b,PCHAR_r,PCHAR_u,PCHAR_m,PCHAR_m,0xff},
	// ATTACK_TORNADO
	{PCHAR_T,PCHAR_o,PCHAR_r,PCHAR_n,PCHAR_a,PCHAR_d,PCHAR_o,0xff,0,0,0,0,0},
	// ATTACK_KOENIGSSCHILD
	{PCHAR_K,PCHAR_oe,PCHAR_n,PCHAR_i,PCHAR_g,PCHAR_s,PCHAR_s,PCHAR_c,PCHAR_h,PCHAR_i,PCHAR_l,PCHAR_d,0xff}
};
