.align 4
.global map_namespaces

map_namespaces:
	.word str_mapnamespace_88
	.word str_mapnamespace_89
	.word str_mapnamespace_90
	.word str_mapnamespace_91
	.word str_mapnamespace_92
	.word str_mapnamespace_93
	.word str_mapnamespace_94
	.word str_mapnamespace_95
	.word str_mapnamespace_96
	.word str_mapnamespace_97
	.word str_mapnamespace_98
	.word str_mapnamespace_99
	.word str_mapnamespace_100
	.word str_mapnamespace_101
	.word str_mapnamespace_102
	.word str_mapnamespace_103
	.word str_mapnamespace_104
	.word str_mapnamespace_105
	.word str_mapnamespace_106
	.word str_mapnamespace_107
	.word str_mapnamespace_108
	.word str_mapnamespace_109
	.word str_mapnamespace_110
	.word str_mapnamespace_111
	.word str_mapnamespace_112
	.word str_mapnamespace_113
	.word str_mapnamespace_114
	.word str_mapnamespace_115
	.word str_mapnamespace_116
	.word str_mapnamespace_117
	.word str_mapnamespace_118
	.word str_mapnamespace_119
	.word str_mapnamespace_120
	.word str_mapnamespace_121
	.word str_mapnamespace_122
	.word str_mapnamespace_123
	.word str_mapnamespace_124
	.word str_mapnamespace_125
	.word str_mapnamespace_126
	.word str_mapnamespace_127
	.word str_mapnamespace_128
	.word str_mapnamespace_129
	.word str_mapnamespace_130
	.word str_mapnamespace_131
	.word str_mapnamespace_132
	.word str_mapnamespace_133
	.word str_mapnamespace_134
	.word str_mapnamespace_135
	.word str_mapnamespace_136
	.word str_mapnamespace_137
	.word str_mapnamespace_138
	.word str_mapnamespace_139
	.word str_mapnamespace_140
	.word str_mapnamespace_141
	.word str_mapnamespace_142
	.word str_mapnamespace_143
	.word str_mapnamespace_144
	.word str_mapnamespace_145
	.word str_mapnamespace_146
	.word str_mapnamespace_147
	.word str_mapnamespace_148
	.word str_mapnamespace_149
	.word str_mapnamespace_150
	.word str_mapnamespace_151
	.word str_mapnamespace_152
	.word str_mapnamespace_153
	.word str_mapnamespace_154
	.word str_mapnamespace_155
	.word str_mapnamespace_156
	.word str_mapnamespace_157
	.word str_mapnamespace_158
	.word str_mapnamespace_159
	.word str_mapnamespace_160
	.word str_mapnamespace_161
	.word str_mapnamespace_162
	.word str_mapnamespace_163
	.word str_mapnamespace_164
	.word str_mapnamespace_165
	.word str_mapnamespace_166
	.word str_mapnamespace_167
	.word str_mapnamespace_168
	.word str_mapnamespace_169
	.word str_mapnamespace_170
	.word str_mapnamespace_171
	.word str_mapnamespace_172
	.word str_mapnamespace_173
	.word str_mapnamespace_174
	.word str_mapnamespace_175
	.word str_mapnamespace_176
	.word str_mapnamespace_177
	.word str_mapnamespace_178
	.word str_mapnamespace_179
	.word str_mapnamespace_180
	.word str_mapnamespace_181
	.word str_mapnamespace_182
	.word str_mapnamespace_183
	.word str_mapnamespace_184
	.word str_mapnamespace_185
	.word str_mapnamespace_186
	.word str_mapnamespace_187
	.word str_mapnamespace_188
	.word str_mapnamespace_189
	.word str_mapnamespace_190
	.word str_mapnamespace_191
	.word str_mapnamespace_192
	.word str_mapnamespace_193
	.word str_mapnamespace_194
	.word str_mapnamespace_195
	.word str_mapnamespace_196

