#define TARGET_DEPENDS_ON_ATTACK 0x0
#define TARGET_UNUSED 0x1
#define RANDOM_TARGET 0x2
#define TARGET_BOTH_FOES 0x3
#define TARGET_USER 0x4
#define TARGET_BOTH_FOES_AND_PARTNER 0x5
#define TARGET_OPPONENT_FIELD 0x6
