#define SELECTED_TARGET 0x0
#define TARGET_DEPENDS_ON_ATTACK 0x1
#define TARGET_UNUSED 0x2
#define RANDOM_TARGET 0x4
#define TARGET_BOTH_FOES 0x8
#define TARGET_USER 0x10
#define TARGET_BOTH_FOES_AND_PARTNER 0x20
#define TARGET_OPPONENT_FIELD 0x40
