#define BATTLE_WEATHER_RAIN 0x1
#define BATTLE_WEATHER_WOLKENBRUCH 0x2
#define BATTLE_WEATHER_RAIN_DRIZZLE 0x4
#define BATTLE_WEATHER_SANDSTORM 0x8
#define BATTLE_WEATHER_SANDSTORM_ABILITY 0x10
#define BATTLE_WEATHER_SUN 0x20
#define BATTLE_WEATHER_SUN_DROUGHT 0x40
#define BATTLE_WEATHER_HAIL 0x80
