#define TYPE_NORMAL 0x0
#define TYPE_FIGHTING 0x1
#define TYPE_FLYING 0x2
#define TYPE_POISON 0x3
#define TYPE_GROUND 0x4
#define TYPE_ROCK 0x5
#define TYPE_BUG 0x6
#define TYPE_GHOST 0x7
#define TYPE_STEEL 0x8
#define TYPE_FAIRY 0x9
#define TYPE_FIRE 0xa
#define TYPE_WATER 0xb
#define TYPE_GRASS 0xc
#define TYPE_ELECTRIC 0xd
#define TYPE_PSYCHIC 0xe
#define TYPE_ICE 0xf
#define TYPE_DRAGON 0x10
#define TYPE_DARK 0x11
