#include "types.h"
#include "pokemon.h"
#include "move_tutor.h"
#include "attack.h"


bool move_tutor_is_compatible(u16 species, u8 move_tutor){
    u32 mask = (u32)(1 << move_tutor);
    if(pokemon_tutor_compatibility[species] & mask)
        return true;
    return false;
}

u16 move_tutor_attacks[] = {
    ATTACK_FOKUSSTOSS,
    ATTACK_GIFTHIEB,
    ATTACK_FINSTERAURA,
    ATTACK_EISZAHN,
    
    ATTACK_DONNERZAHN,
    ATTACK_KREUZSCHERE,
    ATTACK_STEINKANTE,
    ATTACK_LICHTKANONE,
    ATTACK_DRACO_METEOR,
    ATTACK_ENERGIEBALL,
    ATTACK_DRACHENPULS,
    ATTACK_FEUERZAHN,
    ATTACK_EXPLOSION,
    ATTACK_STEINHAGEL,
    ATTACK_DELEGATOR,
    ATTACK_FAUNA_STATUE,
    ATTACK_LOHEKANONADE,
    ATTACK_AQUAHAUBITZE,
    ATTACK_DONNERWELLE,
};

u16 move_tutor_get_attack_id(u8 move_tutor){
    return move_tutor_attacks[move_tutor];
}



u32 pokemon_tutor_compatibility [POKEMON_CNT] = {
    // POKEMON_POKEMON_0
    0,
    // POKEMON_BISASAM
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_BISAKNOSP
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_BISAFLOR
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GLUMANDA
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GLUTEXO
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GLURAK
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHIGGY
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHILLOK
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_TURTOK
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_DARTIRI
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_DARTIGNIS
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_FIARO
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_HORNLIU
    0,
    // POKEMON_KOKUNA
    0,
    // POKEMON_BIBOR
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_STARALILI
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_STARAVIA
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_STARAPTOR
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_BRONZEL
    MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_BRONZONG
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MAEHIKEL
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_CHEVRUMM
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PARAGONI
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TROMBORK
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PIKACHU
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_RAICHU
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_SANDAN
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SANDAMER
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NIDORANW
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NIDORINA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NIDOQUEEN
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NIDORANM
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NIDORINO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NIDOKING
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FLOETTE
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FLORGES
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_VULPIX
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_VULNONA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PUMMELUFF
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_KNUDDELUFF
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ZUBAT
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GOLBAT
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MYRAPLA
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DUFLOR
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GIFLOR
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FOLIPURBA
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FEELINARA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_WATTZAPF
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_VOLTULA
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_DIGDA
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DIGDRI
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KASTADUR
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_TENTANTEL
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ENTON
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ENTORON
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MENKI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RASAFF
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FUKANO
    MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ARKANI
    MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GRAMOKLES
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DUOKLES
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DURENGARD
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ABRA
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_KADABRA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_SIMSALA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MACHOLLO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MASCHOCK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MACHOMEI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KNOFENSA
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ULTRIGARIA
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SARZENIA
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TENTACHA
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TENTOXA
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KLEINSTEIN
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GEOROK
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GEOWAZ
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PONITA
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_GALLOPA
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_FLEGMON
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_LAHMUS
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MAGNETILO
    MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MAGNETON
    MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_PORENTA
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DODU
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_DODRI
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_JURBO
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_JUGONG
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SLEIMA
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SLEIMOK
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MUSCHAS
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_AUSTOS
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NEBULAK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ALPOLLO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GENGAR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ONIX
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TRAUMATO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_HYPNO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_KRABBY
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_KINGLER
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_VOLTOBAL
    MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_LEKTROBAL
    MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_OWEI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KOKOWEI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TRAGOSSO
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KNOGGA
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KICKLEE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NOCKCHAN
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHLURP
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SMOGON
    MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SMOGMOG
    MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RIHORN
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RIZEROS
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_CHANEIRA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ZOBIRIS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KANGAMA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SEEPER
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_SEEMON
    MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_QUABBEL
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_APOQUALLYP
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_STERNDU
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_STARMIE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_TRAUNFUGIL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SICHLOR
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GALAGLADI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ELEKTEK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MAGMAR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PINSIR
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TAUROS
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KARPADOR
    0,
    // POKEMON_GARADOS
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_LAPRAS
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_DITTO
    0,
    // POKEMON_EVOLI
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_AQUANA
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_BLITZA
    MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_FLAMARA
    MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PORYGON
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_AMONITAS
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_AMOROSO
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KABUTO
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KABUTOPS
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_AERODACTYL
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RELAXO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ARKTOS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ZAPDOS
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_LAVADOS
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_DRATINI
    MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_DRAGONIR
    MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_DRAGORAN
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MEWTU
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MEW
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ENDIVIE
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_LORBLATT
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_MEGANIE
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_FEURIGEL
    MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_IGELAVAR
    MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TORNUPTO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KARNIMANI
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TYRACROC
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_IMPERGATOR
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_IGNIVOR
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_RAMOTH
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_GLAZIOLA
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RESLADERO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LEDYBA
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LEDIAN
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_WEBARAK
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ARIADOS
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_IKSBAT
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LAMPI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_LANTURN
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MAGNEZONE
    MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_TOGEKISS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_FLABEBE
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TOGEPI
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_TOGETIC
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_NATU
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_XATU
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_VOLTILAMM
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_WAATY
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_AMPHAROS
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_BLUBELLA
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MARILL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_AZUMARILL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MOGELBAUM
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_CLAVION
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LICHTEL
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LATERNECTO
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SKLELABRA
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GRIFFEL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_SHNEBEDECK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_REXBLISAR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_DELEGATOR,
    // POKEMON_AMBIDIFFEL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_FELINO
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_MORLORD
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_PSIANA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NACHTARA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KRAMURX
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_LASCHOKING
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_KRAMSHEF
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ICOGNITO
    0,
    // POKEMON_FROSDEDJE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SKORGRO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TANNZA
    MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FORSTELLKA
    MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ELEVOLTEK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_SKORGLA
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_STAHLOS
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SNUBBULL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_GRANBULL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MAMUTEL
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHEROX
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_POTTROTT
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SKARABORN
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KRYPPUK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TEDDIURSA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_URSARING
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHNECKMAG
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MAGCARGO
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_QUIEKEL
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KEIFEL
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_CORASONN
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_REMORAID
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_OCTILLERY
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_BOTOGEL
    MOVE_TUTOR_DELEGATOR,
     // POKEMON_SCHLURPLEK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PANZAERON
    MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_HUNDUSTER
    MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_HUNDEMON
    MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SEEDRAKING
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PHANPY
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DONPHAN
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PORYGON2
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_VOLUMINAS
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_TRAUNMAGIL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RABAUZ
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KAPOERA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KUSSILLA
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ELEKID
    MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MAGBY
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_MILTANK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_HEITEIRA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_RAIKOU
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ENTEI
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SUICUNE
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LARVITAR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PUPITAR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DESPOTAR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_LUGIA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_HO_OH
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_CELEBI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_BISAFLORM
    0,
    // POKEMON_GLURAKM
    0,
    // POKEMON_AQUANAM
    0,
    // POKEMON_BLITZAM
    0,
    // POKEMON_FLAMARM
    0,
    // POKEMON_DURENGARDA
    0,
    // POKEMON_IN
    0,
    // POKEMON_GAME
    0,
    // POKEMON_TURTOKM
    0,
    // POKEMON_AMPHARAOSM
    0,
    // POKEMON_GENGARM
    0,
    // POKEMON_BIBORM
    0,
    // POKEMON_ALTARIAM
    0,
    // POKEMON_GEOWAZM
    0,
    // POKEMON_SENGOM
    0,
    // POKEMON_VIPITISM
    0,
    // POKEMON_ZOBIRISM
    0,
    // POKEMON_10d
    0,
    // POKEMON_10e
    0,
    // POKEMON_10f
    0,
    // POKEMON_110
    0,
    // POKEMON_111
    0,
    // POKEMON_112
    0,
    // POKEMON_113
    0,
    // POKEMON_114
    0,
    // POKEMON_LOCKSCHAL
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_STICHSCHAL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_STAHLSTICH
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_WELUNO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ORTHODOS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ZERBERTRES
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SEEKID
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SEESKULL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SKULLYDRA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FIFFYEN
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MAGNAYEN
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ZIGZACHS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_GERADAKS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_WAUMPEL
    0,
    // POKEMON_SCHALOKO
    0,
    // POKEMON_PAPINELLA
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PANEKON
    0,
    // POKEMON_PUDOX
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LOTURZEL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LOMBRERO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KAPPALORES
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SAMURZEL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_BLANAS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TENGULIST
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NINCADA
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NINJASK
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NINJATOM
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHWALBINI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHWALBOSS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KNILZ
    MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KAPILZ
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PANDIR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_WINGULL
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_PELIPPER
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_GEHWEIHER
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MASKEREGEN
    MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_WAILMER
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_WAILORD
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ENECO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ENEKORO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_KECLEON
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_PUPPANCE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LEPUMENTAS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NASGNET
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MAGBRANT
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ZWIRRFINST
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHMERBE
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_WELSAR
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LIEBISKUS
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_KREBSCORPS
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KREBUTACK
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_BARSCHWA
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_MILOTIC
    MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KANIVANHA
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TOHAIDO
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KNACKLION
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_VIBRAVA
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LIBELLDRA
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RIOLU
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LUCARIO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FRIZELBLIZ
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_VOLTENSO
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_CAMAUB
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_CAMERUPT
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SEEMOPS
    MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SEEJONG
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_WALRAISA
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TUSKA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_NOKTUSKA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHNEPPKE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FIRNONTOR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LUNASTEIN
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SONNFEL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_AZURILL
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_SPOINK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_GROINK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_PLUSLE
    MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_MINUN
    MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_FLUNKIFER
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MEDITIE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MEDITALIS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_WABLU
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ALTARIA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ISSO
    0,
    // POKEMON_ZWIRRLICHT
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ZWIRRKLOP
    MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ROSELIA
    MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_BUMMELZ
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_MUNTIER
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LETARKING
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHLUPPUCK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SCHLUKWECH
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TROPIUS
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KAUMALAT
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KNARKSEL
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KNAKRACK
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PERLU
    MOVE_TUTOR_DELEGATOR,
    // POKEMON_AALABYSS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SAGANABYSS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ABSOL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_SHUPPET
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_BANETTE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_VIPITIS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_DELEGATOR,
    // POKEMON_SENGO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_GIFTHIEB | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RELICANTH
    MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_STOLLUNIOR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_STOLLRAK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_STOLLOSS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_FORMEO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_VOLBEAT
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_ILLUMISE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_LILIEP
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_WIELIE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ANORITH
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_ARMALDO
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_KREUZSCHERE | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TRASLA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_KIRLIA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_GUARDEVOIR
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DELEGATOR | MOVE_TUTOR_DONNERWELLE,
    // POKEMON_KINDWURM
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DRASCHEL
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_BRUTALANDA
    MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_TANHEL
    0,
    // POKEMON_METANG
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_METAGROSS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_REGIROCK
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_REGICE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_REGISTEEL
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_EXPLOSION | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_KYOGRE
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_GROUDON
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_RAYQUAZA
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_EISZAHN | MOVE_TUTOR_DONNERZAHN | MOVE_TUTOR_STEINKANTE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_FEUERZAHN | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LATIAS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_LATIOS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_DRACO_METEOR | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_JIRACHI
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DELEGATOR,
    // POKEMON_DEOXYS
    MOVE_TUTOR_FOKUSSTOSS | MOVE_TUTOR_FINSTERAURA | MOVE_TUTOR_ENERGIEBALL | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_STEINHAGEL | MOVE_TUTOR_DELEGATOR,
    // POKEMON_PALIMPALIM
    MOVE_TUTOR_DONNERWELLE | MOVE_TUTOR_LICHTKANONE | MOVE_TUTOR_DRACHENPULS | MOVE_TUTOR_DELEGATOR,
    // POKEMON_EGG
    0,
    // POKEMON_ICOGNITO_B
    0,
    // POKEMON_ICOGNITO_C
    0,
    // POKEMON_ICOGNITO_D
    0,
    // POKEMON_ICOGNITO_E
    0,
    // POKEMON_ICOGNITO_F
    0,
    // POKEMON_ICOGNITO_G
    0,
    // POKEMON_ICOGNITO_H
    0,
    // POKEMON_ICOGNITO_I
    0,
    // POKEMON_ICOGNITO_J
    0,
    // POKEMON_ICOGNITO_K
    0,
    // POKEMON_ICOGNITO_L
    0,
    // POKEMON_ICOGNITO_M
    0,
    // POKEMON_ICOGNITO_N
    0,
    // POKEMON_ICOGNITO_O
    0,
    // POKEMON_ICOGNITO_P
    0,
    // POKEMON_ICOGNITO_Q
    0,
    // POKEMON_ICOGNITO_R
    0,
    // POKEMON_ICOGNITO_S
    0,
    // POKEMON_ICOGNITO_T
    0,
    // POKEMON_ICOGNITO_U
    0,
    // POKEMON_ICOGNITO_V
    0,
    // POKEMON_ICOGNITO_W
    0,
    // POKEMON_ICOGNITO_X
    0,
    // POKEMON_ICOGNITO_Y
    0,
    // POKEMON_ICOGNITO_Z
    0,
    // POKEMON_ICOGNITO_EXCLAMATION
    0,
    // POKEMON_ICOGNITO_QUESTION
    0,

};
