/*
 * pokemon_cry.h
 *
 *  Created on: Mar 28, 2018
 *      Author: dominik
 */

#ifndef INCLUDE_C_POKEMON_CRY_H_
#define INCLUDE_C_POKEMON_CRY_H_

#include "types.h"
#include "pokemon/count.h"

typedef struct {
    u8 header[4];
    const void *data;
    u8 vol_curve[4];
} pokemon_cry;

extern const pokemon_cry pokemon_cries_forward[POKEMON_CNT];
extern const pokemon_cry pokemon_cries_backward[POKEMON_CNT];

/**
 * Checks if a cry is playing and clears the cry songs.
 * @return if a cry is playing.
 **/
bool cry_is_playing_or_clear_cry_songs();

/**
 * Plays the cry of a pokemon
 * @param species The species to play the cry of
 * @param feature Feature for the cry
 */
void pokemon_play_cry(u16 species, u8 feature);

/**
 * Big callback to proceed the cry delay and return the volume to normal once the cry has finished.
 * @param self self-reference in the big_callback list
 */
void cry_proceed(u8 self);

/**
 * Checks if a cry has finished and if so, clears something (maybe volume related?). This
 * function is recommended to be checked in each frame after a cry has been launched.
 * @return if any cry has finished (i.e. cry_proceed is not an active big_callback)
 */
bool cry_has_finished();

// Extern cries from wav2agb

extern const u8 cry_661[];
extern const u8 cry_662[];
extern const u8 cry_663[];
extern const u8 cry_396[];
extern const u8 cry_397[];
extern const u8 cry_398[];
extern const u8 cry_436[];
extern const u8 cry_437[];
extern const u8 cry_672[];
extern const u8 cry_673[];
extern const u8 cry_708[];
extern const u8 cry_709[];
extern const u8 cry_669[];
extern const u8 cry_670[];
extern const u8 cry_671[];
extern const u8 cry_470[];
extern const u8 cry_700[];
extern const u8 cry_595[];
extern const u8 cry_596[];
extern const u8 cry_597[];
extern const u8 cry_598[];
extern const u8 cry_679[];
extern const u8 cry_680[];
extern const u8 cry_681[];
extern const u8 cry_302[];
extern const u8 cry_592[];
extern const u8 cry_593[];
extern const u8 cry_200[];
extern const u8 cry_475[];
extern const u8 cry_636[];
extern const u8 cry_637[];
extern const u8 cry_471[];
extern const u8 cry_701[];
extern const u8 cry_462[];
extern const u8 cry_468[];
extern const u8 cry_707[];
extern const u8 cry_607[];
extern const u8 cry_608[];
extern const u8 cry_609[];
extern const u8 cry_459[];
extern const u8 cry_460[];
extern const u8 cry_424[];
extern const u8 cry_430[];
extern const u8 cry_478[];
extern const u8 cry_472[];
extern const u8 cry_466[];
extern const u8 cry_473[];
extern const u8 cry_442[];
extern const u8 cry_463[];
extern const u8 cry_476[];
extern const u8 cry_429[];
extern const u8 cry_467[];
extern const u8 cry_477[];
extern const u8 cry_447[];
extern const u8 cry_448[];
extern const u8 cry_443[];
extern const u8 cry_444[];
extern const u8 cry_445[];
extern const u8 cry_115[];
extern const u8 cry_474[];
extern const u8 cry_464[];
extern const u8 cry_446[];
extern const u8 cry_780[];
extern const u8 cry_440[];
extern const u8 cry_438[];
extern const u8 cry_433[];
extern const u8 cry_172[];
extern const u8 cry_479[];
extern const u8 cry_757[];
extern const u8 cry_758[];
extern const u8 cry_icognito[];
extern const u8 cry_bisasam[];
extern const u8 cry_bisaknosp[];
extern const u8 cry_bisaflor[];
extern const u8 cry_glumanda[];
extern const u8 cry_glutexo[];
extern const u8 cry_glurak[];
extern const u8 cry_schiggy[];
extern const u8 cry_schillok[];
extern const u8 cry_turtok[];
extern const u8 cry_hornliu[];
extern const u8 cry_kokuna[];
extern const u8 cry_bibor[];
extern const u8 cry_pikachu[];
extern const u8 cry_raichu[];
extern const u8 cry_sandan[];
extern const u8 cry_sandamer[];
extern const u8 cry_nidoranw[];
extern const u8 cry_nidorina[];
extern const u8 cry_nidoqueen[];
extern const u8 cry_nidoranm[];
extern const u8 cry_nidorino[];
extern const u8 cry_nidoking[];
extern const u8 cry_vulpix[];
extern const u8 cry_vulnona[];
extern const u8 cry_pummeluff[];
extern const u8 cry_knuddeluff[];
extern const u8 cry_zubat[];
extern const u8 cry_golbat[];
extern const u8 cry_myrapla[];
extern const u8 cry_duflor[];
extern const u8 cry_giflor[];
extern const u8 cry_digda[];
extern const u8 cry_digdri[];
extern const u8 cry_enton[];
extern const u8 cry_entoron[];
extern const u8 cry_menki[];
extern const u8 cry_rasaff[];
extern const u8 cry_fukano[];
extern const u8 cry_arkani[];
extern const u8 cry_abra[];
extern const u8 cry_kadabra[];
extern const u8 cry_simsala[];
extern const u8 cry_machollo[];
extern const u8 cry_maschock[];
extern const u8 cry_machomei[];
extern const u8 cry_knofensa[];
extern const u8 cry_ultrigaria[];
extern const u8 cry_sarzenia[];
extern const u8 cry_tentacha[];
extern const u8 cry_tentoxa[];
extern const u8 cry_kleinstein[];
extern const u8 cry_georok[];
extern const u8 cry_geowaz[];
extern const u8 cry_ponita[];
extern const u8 cry_gallopa[];
extern const u8 cry_flegmon[];
extern const u8 cry_lahmus[];
extern const u8 cry_magnetilo[];
extern const u8 cry_magneton[];
extern const u8 cry_porenta[];
extern const u8 cry_dodu[];
extern const u8 cry_dodri[];
extern const u8 cry_jurob[];
extern const u8 cry_jugong[];
extern const u8 cry_sleima[];
extern const u8 cry_sleimok[];
extern const u8 cry_muschas[];
extern const u8 cry_austos[];
extern const u8 cry_nebulak[];
extern const u8 cry_alpollo[];
extern const u8 cry_gengar[];
extern const u8 cry_onix[];
extern const u8 cry_traumato[];
extern const u8 cry_hypno[];
extern const u8 cry_krabby[];
extern const u8 cry_kingler[];
extern const u8 cry_voltobal[];
extern const u8 cry_lektrobal[];
extern const u8 cry_owei[];
extern const u8 cry_kokowei[];
extern const u8 cry_tragosso[];
extern const u8 cry_knogga[];
extern const u8 cry_kicklee[];
extern const u8 cry_nockchan[];
extern const u8 cry_schlurp[];
extern const u8 cry_smogon[];
extern const u8 cry_smogmog[];
extern const u8 cry_rihorn[];
extern const u8 cry_rizeros[];
extern const u8 cry_chaneira[];
extern const u8 cry_seeper[];
extern const u8 cry_seemon[];
extern const u8 cry_sterndu[];
extern const u8 cry_starmie[];
extern const u8 cry_sichlor[];
extern const u8 cry_elektek[];
extern const u8 cry_magmar[];
extern const u8 cry_pinsir[];
extern const u8 cry_tauros[];
extern const u8 cry_karpador[];
extern const u8 cry_garados[];
extern const u8 cry_lapras[];
extern const u8 cry_ditto[];
extern const u8 cry_evoli[];
extern const u8 cry_aquana[];
extern const u8 cry_blitza[];
extern const u8 cry_flamara[];
extern const u8 cry_porygon[];
extern const u8 cry_amonitas[];
extern const u8 cry_amoroso[];
extern const u8 cry_kabuto[];
extern const u8 cry_kabutops[];
extern const u8 cry_aerodactyl[];
extern const u8 cry_relaxo[];
extern const u8 cry_arktos[];
extern const u8 cry_zapdos[];
extern const u8 cry_lavados[];
extern const u8 cry_dratini[];
extern const u8 cry_dragonir[];
extern const u8 cry_dragoran[];
extern const u8 cry_mewtu[];
extern const u8 cry_mew[];
extern const u8 cry_endivie[];
extern const u8 cry_lorblatt[];
extern const u8 cry_meganie[];
extern const u8 cry_feurigel[];
extern const u8 cry_igelavar[];
extern const u8 cry_tornupto[];
extern const u8 cry_karnimani[];
extern const u8 cry_tyracroc[];
extern const u8 cry_impergator[];
extern const u8 cry_ledyba[];
extern const u8 cry_ledian[];
extern const u8 cry_webarak[];
extern const u8 cry_ariados[];
extern const u8 cry_iksbat[];
extern const u8 cry_lampi[];
extern const u8 cry_lanturn[];
extern const u8 cry_togepi[];
extern const u8 cry_togetic[];
extern const u8 cry_natu[];
extern const u8 cry_xatu[];
extern const u8 cry_voltilamm[];
extern const u8 cry_waaty[];
extern const u8 cry_ampharos[];
extern const u8 cry_blubella[];
extern const u8 cry_marill[];
extern const u8 cry_azumarill[];
extern const u8 cry_mogelbaum[];
extern const u8 cry_griffel[];
extern const u8 cry_felino[];
extern const u8 cry_morlord[];
extern const u8 cry_psiana[];
extern const u8 cry_nachtara[];
extern const u8 cry_kramurx[];
extern const u8 cry_laschoking[];
extern const u8 cry_tannza[];
extern const u8 cry_forstellka[];
extern const u8 cry_skorgla[];
extern const u8 cry_stahlos[];
extern const u8 cry_snubbull[];
extern const u8 cry_granbull[];
extern const u8 cry_scherox[];
extern const u8 cry_fluffeluff[];
extern const u8 cry_skaraborn[];
extern const u8 cry_teddiursa[];
extern const u8 cry_ursaring[];
extern const u8 cry_schneckmag[];
extern const u8 cry_magcargo[];
extern const u8 cry_quiekel[];
extern const u8 cry_keifel[];
extern const u8 cry_remoraid[];
extern const u8 cry_octillery[];
extern const u8 cry_botogel[];
extern const u8 cry_panzaeron[];
extern const u8 cry_hunduster[];
extern const u8 cry_hundemon[];
extern const u8 cry_seedraking[];
extern const u8 cry_phanpy[];
extern const u8 cry_donphan[];
extern const u8 cry_porygon2[];
extern const u8 cry_rabauz[];
extern const u8 cry_kapoera[];
extern const u8 cry_elekid[];
extern const u8 cry_magby[];
extern const u8 cry_miltank[];
extern const u8 cry_heiteira[];
extern const u8 cry_raikou[];
extern const u8 cry_entei[];
extern const u8 cry_suicune[];
extern const u8 cry_larvitar[];
extern const u8 cry_pupitar[];
extern const u8 cry_despotar[];
extern const u8 cry_lugia[];
extern const u8 cry_ho_oh[];
extern const u8 cry_celebi[];
extern const u8 cry_tropius[];
extern const u8 cry_firnontor[];
extern const u8 cry_lockschal[];
extern const u8 cry_stichschal[];
extern const u8 cry_stahlstich[];
extern const u8 cry_weluno[];
extern const u8 cry_orthodos[];
extern const u8 cry_zerbertres[];
extern const u8 cry_seekid[];
extern const u8 cry_seeskull[];
extern const u8 cry_skullydra[];
extern const u8 cry_fiffyen[];
extern const u8 cry_magnayen[];
extern const u8 cry_zigzachs[];
extern const u8 cry_geradaks[];
extern const u8 cry_waumpel[];
extern const u8 cry_schaloko[];
extern const u8 cry_papinella[];
extern const u8 cry_panekon[];
extern const u8 cry_pudox[];
extern const u8 cry_loturzel[];
extern const u8 cry_lombrero[];
extern const u8 cry_kappalores[];
extern const u8 cry_samurzel[];
extern const u8 cry_blanas[];
extern const u8 cry_tengulist[];
extern const u8 cry_nincada[];
extern const u8 cry_ninjask[];
extern const u8 cry_ninjatom[];
extern const u8 cry_schwalbini[];
extern const u8 cry_schwalboss[];
extern const u8 cry_knilz[];
extern const u8 cry_kapilz[];
extern const u8 cry_pandir[];
extern const u8 cry_wingull[];
extern const u8 cry_pelipper[];
extern const u8 cry_gehweiher[];
extern const u8 cry_maskeregen[];
extern const u8 cry_wailmer[];
extern const u8 cry_wailord[];
extern const u8 cry_eneco[];
extern const u8 cry_enekoro[];
extern const u8 cry_kecleon[];
extern const u8 cry_puppance[];
extern const u8 cry_lepumentas[];
extern const u8 cry_nasgnet[];
extern const u8 cry_schmerbe[];
extern const u8 cry_welsar[];
extern const u8 cry_krebscorps[];
extern const u8 cry_krebutack[];
extern const u8 cry_barschwa[];
extern const u8 cry_milotic[];
extern const u8 cry_kanivanha[];
extern const u8 cry_tohaido[];
extern const u8 cry_knacklion[];
extern const u8 cry_vibrava[];
extern const u8 cry_libelldra[];
extern const u8 cry_frizelbliz[];
extern const u8 cry_voltenso[];
extern const u8 cry_camaub[];
extern const u8 cry_camerupt[];
extern const u8 cry_seemops[];
extern const u8 cry_seejong[];
extern const u8 cry_walraisa[];
extern const u8 cry_tuska[];
extern const u8 cry_noktuska[];
extern const u8 cry_schneppke[];
extern const u8 cry_lunastein[];
extern const u8 cry_sonnfel[];
extern const u8 cry_azurill[];
extern const u8 cry_spoink[];
extern const u8 cry_groink[];
extern const u8 cry_flunkifer[];
extern const u8 cry_meditie[];
extern const u8 cry_meditalis[];
extern const u8 cry_wablu[];
extern const u8 cry_altaria[];
extern const u8 cry_zwirrlicht[];
extern const u8 cry_zwirrklop[];
extern const u8 cry_bummelz[];
extern const u8 cry_muntier[];
extern const u8 cry_letarking[];
extern const u8 cry_perlu[];
extern const u8 cry_aalabyss[];
extern const u8 cry_saganabyss[];
extern const u8 cry_absol[];
extern const u8 cry_shuppet[];
extern const u8 cry_banette[];
extern const u8 cry_vipitis[];
extern const u8 cry_sengo[];
extern const u8 cry_relicanth[];
extern const u8 cry_stollunior[];
extern const u8 cry_stollrak[];
extern const u8 cry_stolloss[];
extern const u8 cry_formeo[];
extern const u8 cry_liliep[];
extern const u8 cry_wielie[];
extern const u8 cry_anorith[];
extern const u8 cry_armaldo[];
extern const u8 cry_trasla[];
extern const u8 cry_kirlia[];
extern const u8 cry_guardevoir[];
extern const u8 cry_kindwurm[];
extern const u8 cry_draschel[];
extern const u8 cry_brutalanda[];
extern const u8 cry_tanhel[];
extern const u8 cry_metang[];
extern const u8 cry_metagross[];
extern const u8 cry_regirock[];
extern const u8 cry_regice[];
extern const u8 cry_registeel[];
extern const u8 cry_kyogre[];
extern const u8 cry_groudon[];
extern const u8 cry_rayquaza[];
extern const u8 cry_latias[];
extern const u8 cry_latios[];
extern const u8 cry_jirachi[];
extern const u8 cry_deoxys[];
extern const u8 cry_palimpalim[];

#endif /* INCLUDE_C_POKEMON_CRY_H_ */
