#include "types.h"
#include "basestats.h"
#include "attack.h"
#include "debug.h"

u16 egg_moves[] = {
	// Bisasam
	20000 + POKEMON_BISASAM, ATTACK_CHARME, ATTACK_SCHAEDELWUMME, ATTACK_NATUR_KRAFT, ATTACK_AUSDAUER, ATTACK_VERWURZLER, ATTACK_GRASFLOETE, ATTACK_BLAETTERSTURM, ATTACK_BLAETTERTANZ, ATTACK_GIGASAUGER, ATTACK_ZAUBERBLATT, ATTACK_FLUCH, ATTACK_AMNESIE, ATTACK_SCHLAMMBAD, 
	// Glumanda
	20000 + POKEMON_GLUMANDA, ATTACK_DRACHENTANZ, ATTACK_KNIRSCHER, ATTACK_WINDSCHNITT, ATTACK_FLAMMENBLITZ, ATTACK_WUTANFALL, ATTACK_KONTER, ATTACK_ANTIK_KRAFT, ATTACK_PRUEGLER, ATTACK_METALLKLAUE, ATTACK_POWER_PUNCH, ATTACK_BAUCHTROMMEL, ATTACK_BISS, ATTACK_DRACHENPULS, 
	// Schiggy
	20000 + POKEMON_SCHIGGY, ATTACK_AURASPHAERE, ATTACK_SPIEGELCAPE, ATTACK_GESICHTE, ATTACK_WEISSNEBEL, ATTACK_FONTRAENEN, ATTACK_DUNKELNEBEL, ATTACK_LEHMSUHLER, ATTACK_LEHMBRUEHE, ATTACK_MOGELHIEB, ATTACK_GAEHNER, ATTACK_DRESCHFLEGEL, ATTACK_WASSERDUESE, ATTACK_HEILUNG, ATTACK_DRACHENPULS, 
	// Dartiri
	20000 + POKEMON_DARTIRI, ATTACK_UEBERNAHME, 
	// Staralili
	20000 + POKEMON_STARALILI, ATTACK_AUFRUHR, ATTACK_DAUNENREIGEN, ATTACK_SANDWIRBEL, ATTACK_GESICHTE, ATTACK_SPIEGELTRICK, ATTACK_VERFOLGUNG, ATTACK_FURIENSCHLAG, ATTACK_ERSTAUNER, ATTACK_STAHLFLUEGEL, ATTACK_SCANNER, ATTACK_VERGELTUNG, ATTACK_RISIKOTACKLE, 
	// Maehikel
	20000 + POKEMON_MAEHIKEL, ATTACK_EINIGLER, 
	// Paragoni
	20000 + POKEMON_PARAGONI, ATTACK_NACHSPIEL, ATTACK_BEGRENZER, 
	// Pikachu
	20000 + POKEMON_PIKACHU, ATTACK_DUPLEXHIEB, ATTACK_DONNER, ATTACK_GESCHENK, ATTACK_ZUGABE, ATTACK_AUSDAUER, ATTACK_GEDULD, ATTACK_LADEVORGANG, ATTACK_MOGELHIEB, ATTACK_SAEUSELSTIMME, ATTACK_SPASSKANONE, ATTACK_GEGENSCHLAG, ATTACK_DRESCHFLEGEL, ATTACK_WUNSCHTRAUM, 
	// Sandan
	20000 + POKEMON_SANDAN, ATTACK_AUSDAUER, ATTACK_KRAXLER, ATTACK_KONTER, ATTACK_NACHTHIEB, ATTACK_METALLKLAUE, ATTACK_LEHMSCHUSS, ATTACK_ZERMALMKLAUE, ATTACK_DRESCHFLEGEL, ATTACK_TURBODREHER, 
	// Nidoranw
	20000 + POKEMON_NIDORANW, ATTACK_ENERGIEFOKUS, ATTACK_EISENSCHWEIF, ATTACK_CHARME, ATTACK_SCHAEDELWUMME, ATTACK_BODYCHECK, ATTACK_AUSDAUER, ATTACK_VERFOLGUNG, ATTACK_KONTER, ATTACK_PRUEGLER, ATTACK_AUSSETZER, ATTACK_SUPERSCHALL, ATTACK_GIFTSCHWEIF, 
	// Nidoranm
	20000 + POKEMON_NIDORANM, ATTACK_EISENSCHWEIF, ATTACK_BODYCHECK, ATTACK_AUSDAUER, ATTACK_KONFUSION, ATTACK_KONTER, ATTACK_PRUEGLER, ATTACK_TIEFSCHLAG, ATTACK_AUSSETZER, ATTACK_AMNESIE, ATTACK_SUPERSCHALL, ATTACK_GIFTSCHWEIF, 
	// Vulpix
	20000 + POKEMON_VULPIX, ATTACK_HYPNOSE, ATTACK_GROLL, ATTACK_FINTE, ATTACK_FLAMMENBLITZ, ATTACK_GEHEIMPOWER, ATTACK_HITZEWELLE, ATTACK_SONDERSENSOR, ATTACK_JAULER, ATTACK_AUSSETZER, ATTACK_DRESCHFLEGEL, 
	// Pummeluff
	20000 + POKEMON_PUMMELUFF, ATTACK_ABGESANG, ATTACK_FINTE, ATTACK_GESCHENK, ATTACK_SCHLAFREDE, ATTACK_TRUGTRAENE, ATTACK_WUNSCHTRAUM, ATTACK_BEZIRZER, 
	// Zubat
	20000 + POKEMON_ZUBAT, ATTACK_WINDSTOSS, ATTACK_HYPNOSE, ATTACK_FINTE, ATTACK_WIRBELWIND, ATTACK_VERFOLGUNG, ATTACK_RUCKZUCKHIEB, ATTACK_STAHLFLUEGEL, ATTACK_ZEN_KOPFSTOSS, ATTACK_GIGASAUGER, ATTACK_STURZFLUG, ATTACK_FLUCH, 
	// Myrapla
	20000 + POKEMON_MYRAPLA, ATTACK_GEHEIMPOWER, ATTACK_CHARME, ATTACK_DRESCHFLEGEL, 
	// Folipurba
	20000 + POKEMON_FOLIPURBA, ATTACK_CHARME, ATTACK_AUSDAUER, ATTACK_SCANNER, ATTACK_TRUGTRAENE, ATTACK_SPASSKANONE, ATTACK_FLUCH, ATTACK_GAEHNER, ATTACK_DRESCHFLEGEL, ATTACK_WUNSCHTRAUM, ATTACK_BEZIRZER, 
	// Feelinara
	20000 + POKEMON_FEELINARA, ATTACK_CHARME, ATTACK_AUSDAUER, ATTACK_SCANNER, ATTACK_TRUGTRAENE, ATTACK_SPASSKANONE, ATTACK_FLUCH, ATTACK_GAEHNER, ATTACK_DRESCHFLEGEL, ATTACK_WUNSCHTRAUM, ATTACK_BEZIRZER, 
	// Digda
	20000 + POKEMON_DIGDA, ATTACK_MEMENTO_MORI, ATTACK_AUFRUHR, ATTACK_KOPFNUSS, ATTACK_FINTE, ATTACK_FUCHTLER, ATTACK_AUSDAUER, ATTACK_VERFOLGUNG, ATTACK_ANTIK_KRAFT, ATTACK_ERSTAUNER, ATTACK_KREIDESCHREI, ATTACK_PRUEGLER, ATTACK_GEGENSCHLAG, ATTACK_METALLSOUND, 
	// Kastadur
	20000 + POKEMON_KASTADUR, ATTACK_STACHLER, ATTACK_KUGELSAAT, ATTACK_EGELSAMEN, ATTACK_KRAXLER, 
	// Enton
	20000 + POKEMON_ENTON, ATTACK_HYPNOSE, ATTACK_PSYSTRAHL, ATTACK_SEHER, ATTACK_GESICHTE, ATTACK_ZUGABE, ATTACK_GEHEIMPOWER, ATTACK_SCHLAFREDE, ATTACK_KREUZHIEB, ATTACK_GAEHNER, ATTACK_HEILUNG, ATTACK_KONFUSTRAHL, 
	// Menki
	20000 + POKEMON_MENKI, ATTACK_NAHKAMPF, ATTACK_MEDITATION, ATTACK_GESICHTE, ATTACK_ZUGABE, ATTACK_SCHLAFREDE, ATTACK_KONTER, ATTACK_RIECHSALZ, ATTACK_NACHTHIEB, ATTACK_PRUEGLER, ATTACK_VERGELTUNG, ATTACK_GEGENSCHLAG, ATTACK_POWER_PUNCH, 
	// Fukano
	20000 + POKEMON_FUKANO, ATTACK_EISENSCHWEIF, ATTACK_NAHKAMPF, ATTACK_KNIRSCHER, ATTACK_BODYSLAM, ATTACK_FLAMMENBLITZ, ATTACK_FUCHTLER, ATTACK_DOPPELKICK, ATTACK_HITZEWELLE, ATTACK_MORGENGRAUEN, ATTACK_FEUERWIRBEL, ATTACK_JAULER, ATTACK_BEZIRZER, ATTACK_RISIKOTACKLE, 
	// Gramokles
	20000 + POKEMON_GRAMOKLES, ATTACK_ABGANGSBUND, ATTACK_SCHATTENSTOSS, ATTACK_METALLSOUND, 
	// Abra
	20000 + POKEMON_ABRA, ATTACK_DONNER, ATTACK_BARRIERE, ATTACK_FEUERSCHLAG, ATTACK_EISHIEB, ATTACK_ABSCHLAG, 
	// Machollo
	20000 + POKEMON_MACHOLLO, ATTACK_NAHKAMPF, ATTACK_MEDITATION, ATTACK_DONNER, ATTACK_ZUGABE, ATTACK_KONTER, ATTACK_RIECHSALZ, ATTACK_ABSCHLAG, ATTACK_PATRONENHIEB, ATTACK_FEUERSCHLAG, ATTACK_SPASSKANONE, ATTACK_FEGEKICK, ATTACK_EISHIEB, 
	// Knofensa
	20000 + POKEMON_KNOFENSA, ATTACK_GIGASAUGER, ATTACK_BLUTSAUGER, 
	// Tentacha
	20000 + POKEMON_TENTACHA, ATTACK_AURORASTRAHL, ATTACK_SPIEGELCAPE, ATTACK_BLUBBER, ATTACK_DUNKELNEBEL, ATTACK_ABSCHLAG, ATTACK_LEHMBRUEHE, ATTACK_SPASSKANONE, ATTACK_KONFUSTRAHL, ATTACK_TURBODREHER, 
	// Kleinstein
	20000 + POKEMON_KLEINSTEIN, ATTACK_AUSDAUER, ATTACK_KRAXLER, ATTACK_RUECKENTZUG, ATTACK_HAMMERARM, ATTACK_POWER_PUNCH, ATTACK_FLUCH, ATTACK_MEGAHIEB, ATTACK_DRESCHFLEGEL, 
	// Ponita
	20000 + POKEMON_PONITA, ATTACK_HYPNOSE, ATTACK_CHARME, ATTACK_FUSSKICK, ATTACK_FUCHTLER, ATTACK_FLAMMENRAD, ATTACK_DOPPELKICK, ATTACK_MORGENGRAUEN, ATTACK_RISIKOTACKLE, ATTACK_HORNBOHRER, 
	// Flegmon
	20000 + POKEMON_FLEGMON, ATTACK_SEHER, ATTACK_STAMPFER, ATTACK_SCHLAFREDE, ATTACK_SCHNARCHER, ATTACK_LEHMSUHLER, ATTACK_RUECKENTZUG, ATTACK_ZEN_KOPFSTOSS, ATTACK_BAUCHTROMMEL, 
	// Porenta
	20000 + POKEMON_PORENTA, ATTACK_WINDSTOSS, ATTACK_DAUNENREIGEN, ATTACK_GESICHTE, ATTACK_SPIEGELTRICK, ATTACK_LEHMSCHELLE, ATTACK_RUCKZUCKHIEB, ATTACK_NACHTHIEB, ATTACK_LAUBKLINGE, ATTACK_STAHLFLUEGEL, ATTACK_VERGELTUNG, ATTACK_FLUCH, ATTACK_DRESCHFLEGEL, ATTACK_BEZIRZER, 
	// Dodu
	20000 + POKEMON_DODU, ATTACK_FINTE, ATTACK_SPIEGELTRICK, ATTACK_RUCKZUCKHIEB, ATTACK_DUNKELNEBEL, ATTACK_STURZFLUG, ATTACK_DRESCHFLEGEL, ATTACK_SUPERSCHALL, ATTACK_NOTSITUATION, 
	// Jurob
	20000 + POKEMON_JUROB, ATTACK_EISENSCHWEIF, ATTACK_ABGESANG, ATTACK_VERZEHRER, ATTACK_ZUGABE, ATTACK_SCHLAFREDE, ATTACK_HORTER, ATTACK_SCHLECKER, ATTACK_AQUAWELLE, ATTACK_ENTFESSLER, ATTACK_MOGELHIEB, ATTACK_AMPELLEUCHTE, ATTACK_EISSPEER, ATTACK_SLAM, ATTACK_AUSSETZER, ATTACK_HORNBOHRER, 
	// Sleima
	20000 + POKEMON_SLEIMA, ATTACK_HORRORBLICK, ATTACK_HORTER, ATTACK_DUNKELNEBEL, ATTACK_GRIMASSE, ATTACK_SCHLECKER, ATTACK_ENTFESSLER, ATTACK_SCHATTENSTOSS, ATTACK_BEGRENZER, ATTACK_FLUCH, ATTACK_FINSTERFAUST, 
	// Muschas
	20000 + POKEMON_MUSCHAS, ATTACK_DUONADEL, ATTACK_BLUBBSTRAHL, ATTACK_BODYCHECK, ATTACK_BARRIERE, ATTACK_AQUAWELLE, ATTACK_FELSWURF, ATTACK_KREIDESCHREI, ATTACK_EISSPEER, ATTACK_LEHMSCHUSS, ATTACK_TURBODREHER, 
	// Nebulak
	20000 + POKEMON_NEBULAK, ATTACK_PSYWELLE, ATTACK_ABGESANG, ATTACK_DONNER, ATTACK_NACHSPIEL, ATTACK_ERSTAUNER, ATTACK_DUNKELNEBEL, ATTACK_GRIMASSE, ATTACK_SMOG, ATTACK_FEUERSCHLAG, ATTACK_AUSSETZER, ATTACK_EISHIEB, 
	// Onix
	20000 + POKEMON_ONIX, ATTACK_FELSWURF, ATTACK_DRESCHFLEGEL, ATTACK_KRAXLER, ATTACK_EINIGLER, ATTACK_RUECKENTZUG, 
	// Traumato
	20000 + POKEMON_TRAUMATO, ATTACK_DONNER, ATTACK_GEHEIMPOWER, ATTACK_BARRIERE, ATTACK_FEUERSCHLAG, ATTACK_EISHIEB, 
	// Krabby
	20000 + POKEMON_KRABBY, ATTACK_AUSDAUER, ATTACK_DUNKELNEBEL, ATTACK_AGILITAET, ATTACK_ANTIK_KRAFT, ATTACK_GEDULD, ATTACK_ABSCHLAG, ATTACK_SPASSKANONE, ATTACK_SLAM, ATTACK_AMNESIE, ATTACK_DRESCHFLEGEL, 
	// Owei
	20000 + POKEMON_OWEI, ATTACK_MONDSCHEIN, ATTACK_NATUR_KRAFT, ATTACK_ANTIK_KRAFT, ATTACK_RUECKENTZUG, ATTACK_VERWURZLER, ATTACK_BLAETTERSTURM, ATTACK_GIGASAUGER, ATTACK_FLUCH, ATTACK_SYNTHESE, 
	// Tragosso
	20000 + POKEMON_TRAGOSSO, ATTACK_ABGESANG, ATTACK_AUSDAUER, ATTACK_DOPPELKICK, ATTACK_ANTIK_KRAFT, ATTACK_FLUCH, ATTACK_BAUCHTROMMEL, 
	// Schlurp
	20000 + POKEMON_SCHLURP, ATTACK_FLUCH, ATTACK_BODYSLAM, ATTACK_BAUCHTROMMEL, ATTACK_AMNESIE, ATTACK_FUCHTLER, 
	// Smogon
	20000 + POKEMON_SMOGON, ATTACK_ENTFESSLER, ATTACK_FLUCH, ATTACK_ABGANGSBUND, 
	// Rihorn
	20000 + POKEMON_RIHORN, ATTACK_EISZAHN, ATTACK_EISENSCHWEIF, ATTACK_KNIRSCHER, ATTACK_SCHAEDELWUMME, ATTACK_DONNER, ATTACK_KONTER, ATTACK_KRAXLER, ATTACK_FEUERZAHN, ATTACK_INTENSITAET, ATTACK_GEGENSCHLAG, ATTACK_FLUCH, ATTACK_ZERMALMKLAUE, 
	// Chaneira
	20000 + POKEMON_CHANEIRA, ATTACK_AROMAKUR, ATTACK_GESCHENK, ATTACK_AUSDAUER, ATTACK_KONTER, ATTACK_VITALGLOCKE, ATTACK_RECHTE_HAND, ATTACK_GEOWURF, ATTACK_METRONOM, 
	// Zobiris
	20000 + POKEMON_ZOBIRIS, ATTACK_SCHMEICHLER, ATTACK_MONDSCHEIN, ATTACK_HORRORBLICK, ATTACK_GENESUNG, ATTACK_BEGRENZER, ATTACK_TIEFSCHLAG, ATTACK_TRICKBETRUG, 
	// Kangama
	20000 + POKEMON_KANGAMA, ATTACK_ENERGIEFOKUS, ATTACK_AUFRUHR, ATTACK_GESICHTE, ATTACK_STAMPFER, ATTACK_KONTER, ATTACK_HAMMERARM, ATTACK_POWER_PUNCH, ATTACK_AUSSETZER, ATTACK_ZERMALMKLAUE, ATTACK_RISIKOTACKLE, ATTACK_NOTSITUATION, 
	// Seeper
	20000 + POKEMON_SEEPER, ATTACK_AURORASTRAHL, ATTACK_KLINGENSTURM, ATTACK_WUTANFALL, ATTACK_FEUERODEM, ATTACK_DRACHENWUT, ATTACK_AQUAWELLE, ATTACK_LEHMBRUEHE, ATTACK_AMPELLEUCHTE, ATTACK_OCTAZOOKA, ATTACK_AUSSETZER, ATTACK_PLATSCHER, ATTACK_DRESCHFLEGEL, 
	// Quabbel
	20000 + POKEMON_QUABBEL, ATTACK_SAEUREPANZER, ATTACK_UMKLAMMERUNG, ATTACK_WEISSNEBEL, ATTACK_GENESUNG, ATTACK_LEIDTEILER, ATTACK_KONFUSTRAHL, 
	// Traunfugil
	20000 + POKEMON_TRAUNFUGIL, ATTACK_MEMENTO_MORI, ATTACK_GROLL, ATTACK_ABGANGSBUND, ATTACK_SCHATTENSTOSS, ATTACK_BEGRENZER, ATTACK_KREIDESCHREI, ATTACK_TIEFSCHLAG, ATTACK_FLUCH, 
	// Sichlor
	20000 + POKEMON_SICHLOR, ATTACK_STAFETTE, ATTACK_SILBERHAUCH, ATTACK_KLINGENSTURM, ATTACK_AUSDAUER, ATTACK_KONTER, ATTACK_NACHTHIEB, ATTACK_KAEFERGEBRUMM, ATTACK_STAHLFLUEGEL, ATTACK_GEGENSCHLAG, 
	// Pinsir
	20000 + POKEMON_PINSIR, ATTACK_NAHKAMPF, ATTACK_FINTE, ATTACK_KRAFTKOLOSS, ATTACK_RUCKZUCKHIEB, ATTACK_FURIENSCHLAG, ATTACK_KAEFERBISS, ATTACK_DRESCHFLEGEL, 
	// Lapras
	20000 + POKEMON_LAPRAS, ATTACK_DRACHENTANZ, ATTACK_GEOFISSUR, ATTACK_SEHER, ATTACK_WHIRLPOOL, ATTACK_GESICHTE, ATTACK_SCHLAFREDE, ATTACK_ANTIK_KRAFT, ATTACK_SPASSKANONE, ATTACK_FLUCH, ATTACK_HEILUNG, ATTACK_HORNBOHRER, ATTACK_DRACHENPULS, 
	// Evoli
	20000 + POKEMON_EVOLI, ATTACK_CHARME, ATTACK_AUSDAUER, ATTACK_SCANNER, ATTACK_TRUGTRAENE, ATTACK_SPASSKANONE, ATTACK_FLUCH, ATTACK_GAEHNER, ATTACK_DRESCHFLEGEL, ATTACK_WUNSCHTRAUM, ATTACK_BEZIRZER, 
	// Amonitas
	20000 + POKEMON_AMONITAS, ATTACK_AURORASTRAHL, ATTACK_STACHLER, ATTACK_BLUBBSTRAHL, ATTACK_WHIRLPOOL, ATTACK_DUNKELNEBEL, ATTACK_GEDULD, ATTACK_LEHMBRUEHE, ATTACK_AQUAWELLE, ATTACK_ABSCHLAG, ATTACK_SLAM, ATTACK_SUPERSCHALL, 
	// Kabuto
	20000 + POKEMON_KABUTO, ATTACK_AURORASTRAHL, ATTACK_BLUBBSTRAHL, ATTACK_BODYCHECK, ATTACK_GESICHTE, ATTACK_ABSCHLAG, ATTACK_KREIDESCHREI, ATTACK_EISSTURM, ATTACK_GIGASAUGER, ATTACK_LEHMSCHUSS, ATTACK_DRESCHFLEGEL, ATTACK_KONFUSTRAHL, ATTACK_TURBODREHER, 
	// Aerodactyl
	20000 + POKEMON_AERODACTYL, ATTACK_WIRBELWIND, ATTACK_GESICHTE, ATTACK_VERFOLGUNG, ATTACK_FEUERODEM, ATTACK_STAHLFLUEGEL, ATTACK_FLUCH, 
	// Relaxo
	20000 + POKEMON_RELAXO, ATTACK_CHARME, ATTACK_GEOFISSUR, ATTACK_KONTER, ATTACK_SCHLECKER, ATTACK_FLUCH, ATTACK_RISIKOTACKLE, 
	// Dratini
	20000 + POKEMON_DRATINI, ATTACK_DRACHENTANZ, ATTACK_EISENSCHWEIF, ATTACK_WEISSNEBEL, ATTACK_DUNKELNEBEL, ATTACK_FEUERODEM, ATTACK_TURBOTEMPO, ATTACK_AQUAWELLE, ATTACK_SUPERSCHALL, ATTACK_WASSERDUESE, ATTACK_DRACHENPULS, 
	// Endivie
	20000 + POKEMON_ENDIVIE, ATTACK_AROMAKUR, ATTACK_BODYSLAM, ATTACK_NATUR_KRAFT, ATTACK_KONTER, ATTACK_ANTIK_KRAFT, ATTACK_VERWURZLER, ATTACK_GRASFLOETE, ATTACK_BLAETTERSTURM, ATTACK_RANKENHIEB, ATTACK_EGELSAMEN, ATTACK_DRESCHFLEGEL, ATTACK_HEILUNG, 
	// Feurigel
	20000 + POKEMON_FEURIGEL, ATTACK_FLAMMENBLITZ, ATTACK_FUCHTLER, ATTACK_NATUR_KRAFT, ATTACK_GESICHTE, ATTACK_DOPPELKICK, ATTACK_RUCKZUCKHIEB, ATTACK_SONDERSENSOR, ATTACK_GEGENSCHLAG, ATTACK_KRATZFURIE, ATTACK_JAULER, ATTACK_ZERMALMKLAUE, ATTACK_BEZIRZER, ATTACK_RISIKOTACKLE, 
	// Karnimani
	20000 + POKEMON_KARNIMANI, ATTACK_DRACHENTANZ, ATTACK_SCHMEICHLER, ATTACK_KNIRSCHER, ATTACK_FUCHTLER, ATTACK_NASSMACHER, ATTACK_LEHMSUHLER, ATTACK_ANTIK_KRAFT, ATTACK_RUECKENTZUG, ATTACK_AQUAWELLE, ATTACK_HYDROPUMPE, ATTACK_TRUGTRAENE, ATTACK_METALLKLAUE, ATTACK_WASSERDUESE, ATTACK_EISHIEB, 
	// Ignivor
	20000 + POKEMON_IGNIVOR, ATTACK_FADENSCHUSS, ATTACK_HAERTNER, ATTACK_GESICHTE, ATTACK_AUSDAUER, ATTACK_MORGENGRAUEN, ATTACK_ZEN_KOPFSTOSS, 
	// Glaziola
	20000 + POKEMON_GLAZIOLA, ATTACK_CHARME, ATTACK_AUSDAUER, ATTACK_SCANNER, ATTACK_TRUGTRAENE, ATTACK_SPASSKANONE, ATTACK_FLUCH, ATTACK_GAEHNER, ATTACK_DRESCHFLEGEL, ATTACK_WUNSCHTRAUM, ATTACK_BEZIRZER, 
	// Resladero
	20000 + POKEMON_RESLADERO, ATTACK_LEHMSUHLER, ATTACK_AGILITAET, 
	// Ledyba
	20000 + POKEMON_LEDYBA, ATTACK_AUSDAUER, ATTACK_ABSCHLAG, 
	// Webarak
	20000 + POKEMON_WEBARAK, ATTACK_AMPELLEUCHTE, 
	// Lampi
	20000 + POKEMON_LAMPI, ATTACK_PSYSTRAHL, ATTACK_SCHOCKWELLE, ATTACK_WHIRLPOOL, ATTACK_WEISSNEBEL, ATTACK_AGILITAET, ATTACK_AQUAWELLE, ATTACK_KREIDESCHREI, ATTACK_AMNESIE, ATTACK_DRESCHFLEGEL, 
	// Flabebe
	20000 + POKEMON_FLABEBE, ATTACK_TARNUNG, 
	// Togepi
	20000 + POKEMON_TOGEPI, ATTACK_SEHER, ATTACK_GESICHTE, ATTACK_GEHEIMPOWER, ATTACK_GESCHENK, ATTACK_SPIEGELTRICK, ATTACK_MORGENGRAUEN, ATTACK_SONDERSENSOR, ATTACK_SCHNABEL, 
	// Natu
	20000 + POKEMON_NATU, ATTACK_FINTE, ATTACK_DAUNENREIGEN, ATTACK_RUCKZUCKHIEB, ATTACK_DUNKELNEBEL, ATTACK_STAHLFLUEGEL, ATTACK_ZEN_KOPFSTOSS, ATTACK_BOHRSCHNABEL, ATTACK_TIEFSCHLAG, ATTACK_HEILUNG, 
	// Voltilamm
	20000 + POKEMON_VOLTILAMM, ATTACK_SCHMEICHLER, ATTACK_EISENSCHWEIF, ATTACK_BODYSLAM, ATTACK_BODYCHECK, ATTACK_SANDWIRBEL, ATTACK_AGILITAET, ATTACK_LADEVORGANG, ATTACK_KREIDESCHREI, ATTACK_SCHNUEFFLER, 
	// Mogelbaum
	20000 + POKEMON_MOGELBAUM, ATTACK_KOPFNUSS, ATTACK_HAERTNER, ATTACK_AUSDAUER, ATTACK_FINALE, ATTACK_SANDGRAB, ATTACK_EINIGLER, ATTACK_FLUCH, ATTACK_WALZER, 
	// Clavion
	20000 + POKEMON_CLAVION, ATTACK_EISENABWEHR, ATTACK_ZIELSCHUSS, ATTACK_RAUB, 
	// Lichtel
	20000 + POKEMON_LICHTEL, ATTACK_SAEUREPANZER, ATTACK_SAEURE, ATTACK_AUSDAUER, ATTACK_HITZEWELLE, ATTACK_DUNKELNEBEL, 
	// Griffel
	20000 + POKEMON_GRIFFEL, ATTACK_SPRUNGFEDER, ATTACK_DUPLEXHIEB, ATTACK_GROLL, ATTACK_VERFOLGUNG, ATTACK_KONTER, ATTACK_AGILITAET, ATTACK_MOGELHIEB, ATTACK_KREIDESCHREI, ATTACK_PRUEGLER, ATTACK_VERGELTUNG, ATTACK_SLAM, ATTACK_BEZIRZER, 
	// Shnebedeck
	20000 + POKEMON_SHNEBEDECK, ATTACK_WACHSTUM, ATTACK_SCHAEDELWUMME, ATTACK_KUGELSAAT, ATTACK_WEISSNEBEL, ATTACK_STAMPFER, ATTACK_ZAUBERBLATT, ATTACK_EGELSAMEN, ATTACK_RISIKOTACKLE, 
	// Felino
	20000 + POKEMON_FELINO, ATTACK_BODYSLAM, ATTACK_DOPPELKICK, ATTACK_SCHLAFREDE, ATTACK_ANTIK_KRAFT, ATTACK_HORTER, ATTACK_KONTER, ATTACK_LEHMSUHLER, ATTACK_ENTFESSLER, ATTACK_GENESUNG, ATTACK_FLUCH, 
	// Kramurx
	20000 + POKEMON_KRAMURX, ATTACK_SCHMEICHLER, ATTACK_ABGESANG, ATTACK_FLUEGELSCHLAG, ATTACK_FINTE, ATTACK_DAUNENREIGEN, ATTACK_SPIEGELTRICK, ATTACK_KREIDESCHREI, ATTACK_BOHRSCHNABEL, ATTACK_KONFUSTRAHL, ATTACK_HIMMELSFEGER, 
	// Tannza
	20000 + POKEMON_TANNZA, ATTACK_AUSDAUER, ATTACK_SANDGRAB, ATTACK_KONTER, ATTACK_NADELRAKETE, ATTACK_VERGELTUNG, ATTACK_DRESCHFLEGEL, ATTACK_RISIKOTACKLE, ATTACK_STERNSCHAUER, 
	// Skorgla
	20000 + POKEMON_SKORGLA, ATTACK_STAFETTE, ATTACK_FLUEGELSCHLAG, ATTACK_KLINGENSTURM, ATTACK_SANDGRAB, ATTACK_KONTER, ATTACK_AGILITAET, ATTACK_KRAXLER, ATTACK_NACHTHIEB, ATTACK_METALLKLAUE, ATTACK_GIFTSCHWEIF, ATTACK_RISIKOTACKLE, 
	// Snubbull
	20000 + POKEMON_SNUBBULL, ATTACK_EISZAHN, ATTACK_NAHKAMPF, ATTACK_KNIRSCHER, ATTACK_FINTE, ATTACK_DONNER, ATTACK_GESCHENK, ATTACK_SCHNARCHER, ATTACK_RIECHSALZ, ATTACK_VITALGLOCKE, ATTACK_FEUERZAHN, ATTACK_MIMIKRY, ATTACK_TRUGTRAENE, ATTACK_POWER_PUNCH, ATTACK_RISIKOTACKLE, ATTACK_METRONOM, 
	// Pottrott
	20000 + POKEMON_POTTROTT, ATTACK_SAEURE, ATTACK_LEHMSCHELLE, ATTACK_SANDGRAB, ATTACK_ABSCHLAG, ATTACK_FELSWURF, ATTACK_RECHTE_HAND, ATTACK_LOCKDUFT, 
	// Skaraborn
	20000 + POKEMON_SKARABORN, ATTACK_HAERTNER, ATTACK_VIELENDER, ATTACK_VERFOLGUNG, ATTACK_GEDULD, ATTACK_FELSWURF, ATTACK_VERGELTUNG, ATTACK_POWER_PUNCH, ATTACK_GEOWURF, ATTACK_DRESCHFLEGEL, ATTACK_RISIKOTACKLE, 
	// Kryppuk
	20000 + POKEMON_KRYPPUK, ATTACK_ABGANGSBUND, ATTACK_AUSSETZER, 
	// Teddiursa
	20000 + POKEMON_TEDDIURSA, ATTACK_KNUDDLER, ATTACK_KNIRSCHER, ATTACK_NAHKAMPF, ATTACK_BODYCHECK, ATTACK_SCHLAFREDE, ATTACK_KONTER, ATTACK_NACHTHIEB, ATTACK_KREUZHIEB, ATTACK_TRUGTRAENE, ATTACK_METALLKLAUE, ATTACK_GEOWURF, ATTACK_BAUCHTROMMEL, ATTACK_GAEHNER, ATTACK_RISIKOTACKLE, 
	// Schneckmag
	20000 + POKEMON_SCHNECKMAG, ATTACK_MEMENTO_MORI, ATTACK_SAEUREPANZER, ATTACK_VERZEHRER, ATTACK_HITZEWELLE, ATTACK_HORTER, ATTACK_ENTFESSLER, ATTACK_ERDKRAEFTE, ATTACK_FLUCH, ATTACK_WALZER, ATTACK_RAUCHWOLKE, 
	// Quiekel
	20000 + POKEMON_QUIEKEL, ATTACK_BODYSLAM, ATTACK_GEOFISSUR, ATTACK_BODYCHECK, ATTACK_ANTIK_KRAFT, ATTACK_EISSPEER, ATTACK_LEHMSCHUSS, ATTACK_FLUCH, ATTACK_RISIKOTACKLE, ATTACK_BISS, 
	// Corasonn
	20000 + POKEMON_CORASONN, ATTACK_NATUR_KRAFT, ATTACK_WEISSNEBEL, ATTACK_BARRIERE, ATTACK_GEDULD, ATTACK_VERWURZLER, ATTACK_AQUAWELLE, ATTACK_KREIDESCHREI, ATTACK_TARNUNG, ATTACK_EISSPEER, ATTACK_FLUCH, ATTACK_AMNESIE, ATTACK_KONFUSTRAHL, 
	// Remoraid
	20000 + POKEMON_REMORAID, ATTACK_AURORASTRAHL, ATTACK_FONTRAENEN, ATTACK_SCHNARCHER, ATTACK_DUNKELNEBEL, ATTACK_AQUAWELLE, ATTACK_FELSWURF, ATTACK_KREIDESCHREI, ATTACK_OCTAZOOKA, ATTACK_LEHMSCHUSS, ATTACK_DRESCHFLEGEL, ATTACK_SUPERSCHALL, ATTACK_STERNSCHAUER, 
	// Botogel
	20000 + POKEMON_BOTOGEL, ATTACK_AURORASTRAHL, ATTACK_FROSTBEULE, ATTACK_KONTER, ATTACK_ABGANGSBUND, ATTACK_EISSTURM, ATTACK_EISSPLITTER, ATTACK_EISHIEB, 
	// Panzaeron
	20000 + POKEMON_PANZAERON, ATTACK_WIRBELWIND, ATTACK_AUSDAUER, ATTACK_VERFOLGUNG, ATTACK_STURZFLUG, ATTACK_BOHRSCHNABEL, ATTACK_FLUCH, ATTACK_HIMMELSFEGER, 
	// Hunduster
	20000 + POKEMON_HUNDUSTER, ATTACK_GROLL, ATTACK_RASEREI, ATTACK_DONNER, ATTACK_VERFOLGUNG, ATTACK_KONTER, ATTACK_ABGANGSBUND, ATTACK_FEUERZAHN, ATTACK_PRUEGLER, ATTACK_GEGENSCHLAG, ATTACK_TIEFSCHLAG, ATTACK_FEUERWIRBEL, 
	// Phanpy
	20000 + POKEMON_PHANPY, ATTACK_ENERGIEFOKUS, ATTACK_KNUDDLER, ATTACK_BODYSLAM, ATTACK_GEOFISSUR, ATTACK_LEHMSCHELLE, ATTACK_ANTIK_KRAFT, ATTACK_SCHNARCHER, ATTACK_KONTER, ATTACK_EISSPLITTER, ATTACK_NOTSITUATION, 
	// Traunmagil
	20000 + POKEMON_TRAUNMAGIL, ATTACK_MEMENTO_MORI, ATTACK_GROLL, ATTACK_ABGANGSBUND, ATTACK_SCHATTENSTOSS, ATTACK_BEGRENZER, ATTACK_KREIDESCHREI, ATTACK_TIEFSCHLAG, ATTACK_FLUCH, 
	// Rabauz
	20000 + POKEMON_RABAUZ, ATTACK_WILLENSLESER, ATTACK_AUSDAUER, ATTACK_VERFOLGUNG, ATTACK_KONTER, ATTACK_PATRONENHIEB, ATTACK_TEMPOHIEB, ATTACK_RECHTE_HAND, ATTACK_TURBODREHER, ATTACK_TURMKICK, 
	// Kussilla
	20000 + POKEMON_KUSSILLA, ATTACK_MOGELHIEB, ATTACK_WUNSCHTRAUM, ATTACK_MEDITATION, ATTACK_EISHIEB, 
	// Elekid
	20000 + POKEMON_ELEKID, ATTACK_KARATESCHLAG, ATTACK_MEDITATION, ATTACK_BARRIERE, ATTACK_WUCHTSCHLAG, ATTACK_KREUZHIEB, ATTACK_FEUERSCHLAG, ATTACK_HAMMERARM, ATTACK_POWER_PUNCH, ATTACK_FEGEKICK, ATTACK_EISHIEB, 
	// Magby
	20000 + POKEMON_MAGBY, ATTACK_ENERGIEFOKUS, ATTACK_EISENSCHWEIF, ATTACK_KARATESCHLAG, ATTACK_FLAMMENBLITZ, ATTACK_DONNER, ATTACK_BARRIERE, ATTACK_WUCHTSCHLAG, ATTACK_KREUZHIEB, ATTACK_TEMPOHIEB, ATTACK_KREIDESCHREI, ATTACK_MEGAHIEB, ATTACK_BAUCHTROMMEL, 
	// Miltank
	20000 + POKEMON_MILTANK, ATTACK_IRRSCHLAG, ATTACK_GESCHENK, ATTACK_AUSDAUER, ATTACK_SCHLAFREDE, ATTACK_RECHTE_HAND, ATTACK_HAMMERARM, ATTACK_GEGENSCHLAG, ATTACK_GEOWURF, ATTACK_FLUCH, ATTACK_RISIKOTACKLE, 
	// Larvitar
	20000 + POKEMON_LARVITAR, ATTACK_DRACHENTANZ, ATTACK_EISENABWEHR, ATTACK_ENERGIEFOKUS, ATTACK_EISENSCHWEIF, ATTACK_STAMPFER, ATTACK_WUTANFALL, ATTACK_ANTIK_KRAFT, ATTACK_VERFOLGUNG, ATTACK_FLUCH, 
	// Fiffyen
	20000 + POKEMON_FIFFYEN, ATTACK_EISZAHN, ATTACK_KNUDDLER, ATTACK_SILBERBLICK, ATTACK_GIFTZAHN, ATTACK_DONNER, ATTACK_UEBERNAHME, ATTACK_SCHLAFREDE, ATTACK_ERSTAUNER, ATTACK_FEUERZAHN, ATTACK_TIEFSCHLAG, ATTACK_GAEHNER, ATTACK_BEZIRZER, 
	// Zigzachs
	20000 + POKEMON_ZIGZACHS, ATTACK_CHARME, ATTACK_LEHMSCHELLE, ATTACK_SCHLAFREDE, ATTACK_KRAXLER, ATTACK_TURBOTEMPO, ATTACK_RECHTE_HAND, ATTACK_SPASSKANONE, ATTACK_TRICKBETRUG, 
	// Loturzel
	20000 + POKEMON_LOTURZEL, ATTACK_AQUAKNARRE, ATTACK_KONTER, ATTACK_TAUMELTANZ, ATTACK_GIGASAUGER, ATTACK_SPASSKANONE, ATTACK_LOCKDUFT, ATTACK_EGELSAMEN, ATTACK_DRESCHFLEGEL, ATTACK_RASIERBLATT, ATTACK_SYNTHESE, 
	// Samurzel
	20000 + POKEMON_SAMURZEL, ATTACK_BODYCHECK, ATTACK_KUGELSAAT, ATTACK_KLINGENSTURM, ATTACK_RUCKZUCKHIEB, ATTACK_PRUEGLER, ATTACK_EGELSAMEN, ATTACK_AMNESIE, 
	// Nincada
	20000 + POKEMON_NINCADA, ATTACK_WINDSTOSS, ATTACK_SILBERHAUCH, ATTACK_FINTE, ATTACK_AUSDAUER, ATTACK_KAEFERBISS, ATTACK_NACHTHIEB, ATTACK_KAEFERGEBRUMM, 
	// Schwalbini
	20000 + POKEMON_SCHWALBINI, ATTACK_RASEREI, ATTACK_WIRBELWIND, ATTACK_SPIEGELTRICK, ATTACK_VERFOLGUNG, ATTACK_STAHLFLUEGEL, ATTACK_STURZFLUG, ATTACK_HEILUNG, ATTACK_HIMMELSFEGER, ATTACK_SUPERSCHALL, 
	// Knilz
	20000 + POKEMON_KNILZ, ATTACK_POWER_PUNCH, ATTACK_KUGELSAAT, ATTACK_CHARME, ATTACK_RECHTE_HAND, ATTACK_TRUGTRAENE, 
	// Pandir
	20000 + POKEMON_PANDIR, ATTACK_STAFETTE, ATTACK_ZUSCHUSS, ATTACK_ZUGABE, ATTACK_RIECHSALZ, ATTACK_AQUAWELLE, ATTACK_MOGELHIEB, ATTACK_EISSTURM, ATTACK_TRUGTRAENE, ATTACK_AUSSETZER, ATTACK_ROLLENTAUSCH, ATTACK_WUNSCHTRAUM, ATTACK_TURBODREHER, ATTACK_TRICKBETRUG, 
	// Wingull
	20000 + POKEMON_WINGULL, ATTACK_WINDSTOSS, ATTACK_WEISSNEBEL, ATTACK_NASSMACHER, ATTACK_ABSCHLAG, ATTACK_AGILITAET, ATTACK_WINDHOSE, 
	// Gehweiher
	20000 + POKEMON_GEHWEIHER, ATTACK_PSYSTRAHL, ATTACK_WILLENSLESER, ATTACK_GESICHTE, ATTACK_AUSDAUER, ATTACK_KAEFERBISS, ATTACK_HYDROPUMPE, ATTACK_AMPELLEUCHTE, ATTACK_LEHMSCHUSS, ATTACK_WASSERDUESE, 
	// Wailmer
	20000 + POKEMON_WAILMER, ATTACK_BODYSLAM, ATTACK_GEOFISSUR, ATTACK_FUCHTLER, ATTACK_SCHLAFREDE, ATTACK_SCHNARCHER, ATTACK_ZEN_KOPFSTOSS, ATTACK_EINIGLER, ATTACK_SPASSKANONE, ATTACK_FLUCH, ATTACK_RISIKOTACKLE, 
	// Eneco
	20000 + POKEMON_ENECO, ATTACK_STAFETTE, ATTACK_AUFRUHR, ATTACK_KOSMIK_KRAFT, ATTACK_MOGELHIEB, ATTACK_RECHTE_HAND, ATTACK_ZEN_KOPFSTOSS, ATTACK_TRUGTRAENE, ATTACK_SPASSKANONE, ATTACK_TIEFSCHLAG, ATTACK_WUNSCHTRAUM, 
	// Kecleon
	20000 + POKEMON_KECLEON, ATTACK_GENESUNG, ATTACK_AUSSETZER, ATTACK_IRRSCHLAG, ATTACK_MOGELHIEB, ATTACK_MAGIEMANTEL, 
	// Nasgnet
	20000 + POKEMON_NASGNET, ATTACK_WALZER, ATTACK_AUSDAUER, ATTACK_RISIKOTACKLE, ATTACK_INTENSITAET, ATTACK_RUECKENTZUG, 
	// Schmerbe
	20000 + POKEMON_SCHMERBE, ATTACK_DRACHENTANZ, ATTACK_BODYCHECK, ATTACK_FUCHTLER, ATTACK_WHIRLPOOL, ATTACK_FUNKENSPRUNG, ATTACK_HYDROPUMPE, ATTACK_LEHMBRUEHE, ATTACK_ERDKRAEFTE, ATTACK_LEHMSCHUSS, ATTACK_DRESCHFLEGEL, 
	// Liebiskus
	20000 + POKEMON_LIEBISKUS, ATTACK_PLATSCHER, ATTACK_LEHMSUHLER, ATTACK_WASSERDUESE, ATTACK_NASSMACHER, ATTACK_SUPERSCHALL, 
	// Krebscorps
	20000 + POKEMON_KREBSCORPS, ATTACK_DRACHENTANZ, ATTACK_BODYSLAM, ATTACK_KRAFTKOLOSS, ATTACK_LEHMSUHLER, ATTACK_ANTIK_KRAFT, ATTACK_ABSCHLAG, ATTACK_METALLKLAUE, ATTACK_WASSERDUESE, ATTACK_RISIKOTACKLE, ATTACK_NOTSITUATION, 
	// Barschwa
	20000 + POKEMON_BARSCHWA, ATTACK_HYPNOSE, ATTACK_SPIEGELCAPE, ATTACK_EISENSCHWEIF, ATTACK_WEISSNEBEL, ATTACK_LEHMSUHLER, ATTACK_DUNKELNEBEL, ATTACK_FEUERODEM, ATTACK_SPASSKANONE, ATTACK_KONFUSTRAHL, ATTACK_DRACHENPULS, 
	// Kanivanha
	20000 + POKEMON_KANIVANHA, ATTACK_FUCHTLER, ATTACK_ANTIK_KRAFT, ATTACK_HYDROPUMPE, ATTACK_ABGANGSBUND, ATTACK_STERNSCHAUER, ATTACK_RISIKOTACKLE, 
	// Knacklion
	20000 + POKEMON_KNACKLION, ATTACK_WINDSTOSS, ATTACK_ENERGIEFOKUS, ATTACK_AUSDAUER, ATTACK_RUCKZUCKHIEB, ATTACK_KAEFERBISS, ATTACK_AMPELLEUCHTE, ATTACK_ERDKRAEFTE, ATTACK_LEHMSCHUSS, ATTACK_ZORNKLINGE, ATTACK_DRESCHFLEGEL, 
	// Riolu
	20000 + POKEMON_RIOLU, ATTACK_TURMKICK, ATTACK_EISENABWEHR, ATTACK_FEUERFEGER, ATTACK_KNIRSCHER, ATTACK_FUSSKICK, ATTACK_WILLENSLESER, ATTACK_AGILITAET, ATTACK_KREUZHIEB, ATTACK_PATRONENHIEB, ATTACK_SCANNER, ATTACK_SPOTLIGHT, ATTACK_BISS, ATTACK_HIMMELHIEB, 
	// Frizelbliz
	20000 + POKEMON_FRIZELBLIZ, ATTACK_AUFRUHR, ATTACK_EISZAHN, ATTACK_KOPFNUSS, ATTACK_SCHOCKWELLE, ATTACK_KNIRSCHER, ATTACK_DONNER, ATTACK_FEUERZAHN, ATTACK_FLUCH, ATTACK_STERNSCHAUER, 
	// Camaub
	20000 + POKEMON_CAMAUB, ATTACK_WACHSTUM, ATTACK_BODYSLAM, ATTACK_VERZEHRER, ATTACK_AUSDAUER, ATTACK_HITZEWELLE, ATTACK_STAMPFER, ATTACK_HORTER, ATTACK_GRIMASSE, ATTACK_ANTIK_KRAFT, ATTACK_ENTFESSLER, ATTACK_EINIGLER, ATTACK_JAULER, ATTACK_GAEHNER, ATTACK_WALZER, 
	// Seemops
	20000 + POKEMON_SEEMOPS, ATTACK_GEOFISSUR, ATTACK_VERZEHRER, ATTACK_NASSMACHER, ATTACK_SCHLAFREDE, ATTACK_HORTER, ATTACK_AQUAWELLE, ATTACK_ENTFESSLER, ATTACK_AMPELLEUCHTE, ATTACK_FLUCH, ATTACK_BAUCHTROMMEL, ATTACK_GAEHNER, ATTACK_WALZER, 
	// Tuska
	20000 + POKEMON_TUSKA, ATTACK_FUSSKICK, ATTACK_SAEURE, ATTACK_RIECHSALZ, ATTACK_KONTER, ATTACK_RUECKENTZUG, ATTACK_GRASFLOETE, ATTACK_AUSSETZER, 
	// Schneppke
	20000 + POKEMON_SCHNEPPKE, ATTACK_STACHLER, ATTACK_GEDULD, ATTACK_RUECKENTZUG, ATTACK_METEOROLOGE, ATTACK_TRUGTRAENE, ATTACK_AUSSETZER, ATTACK_WALZER, 
	// Azurill
	20000 + POKEMON_AZURILL, ATTACK_BODYSLAM, ATTACK_ZUGABE, ATTACK_NASSMACHER, ATTACK_LEHMBRUEHE, ATTACK_TARNUNG, ATTACK_TRUGTRAENE, ATTACK_SPASSKANONE, ATTACK_SLAM, ATTACK_GESANG, ATTACK_HEILUNG, 
	// Spoink
	20000 + POKEMON_SPOINK, ATTACK_SPIEGELCAPE, ATTACK_SEHER, ATTACK_WIRBELWIND, ATTACK_AUSDAUER, ATTACK_ZEN_KOPFSTOSS, ATTACK_SONDERSENSOR, ATTACK_AMNESIE, ATTACK_TRICKBETRUG, 
	// Plusle
	20000 + POKEMON_PLUSLE, ATTACK_BITTERKUSS, ATTACK_CHARME, ATTACK_GESANG, 
	// Minun
	20000 + POKEMON_MINUN, ATTACK_BITTERKUSS, ATTACK_CHARME, ATTACK_GESANG, 
	// Flunkifer
	20000 + POKEMON_FLUNKIFER, ATTACK_EISZAHN, ATTACK_GIFTZAHN, ATTACK_DONNER, ATTACK_ANTIK_KRAFT, ATTACK_FEUERZAHN, ATTACK_SPASSKANONE, ATTACK_GEOWURF, ATTACK_SLAM, 
	// Meditie
	20000 + POKEMON_MEDITIE, ATTACK_STAFETTE, ATTACK_DONNER, ATTACK_GESICHTE, ATTACK_GEHEIMPOWER, ATTACK_WUCHTSCHLAG, ATTACK_PATRONENHIEB, ATTACK_MOGELHIEB, ATTACK_FEUERSCHLAG, ATTACK_EISHIEB, 
	// Wablu
	20000 + POKEMON_WABLU, ATTACK_KNUDDLER, ATTACK_DUNKELNEBEL, ATTACK_AGILITAET, ATTACK_DAUNENREIGEN, 
	// Zwirrlicht
	20000 + POKEMON_ZWIRRLICHT, ATTACK_MEMENTO_MORI, ATTACK_FINTE, ATTACK_NACHSPIEL, ATTACK_FINSTERAURA, ATTACK_DUNKELNEBEL, ATTACK_ABGANGSBUND, ATTACK_BEGRENZER, ATTACK_LEIDTEILER, 
	// Bummelz
	20000 + POKEMON_BUMMELZ, ATTACK_SCHLITZER, ATTACK_BODYSLAM, ATTACK_SCHLAFREDE, ATTACK_SCHNARCHER, ATTACK_VERFOLGUNG, ATTACK_NACHTHIEB, ATTACK_HAMMERARM, ATTACK_SPASSKANONE, ATTACK_FLUCH, ATTACK_ZERMALMKLAUE, 
	// Schluppuck
	20000 + POKEMON_SCHLUPPUCK, ATTACK_SAEUREPANZER, ATTACK_LEHMSCHELLE, ATTACK_SMOG, ATTACK_ABGANGSBUND, ATTACK_FLUCH, ATTACK_LEIDTEILER, 
	// Tropius
	20000 + POKEMON_TROPIUS, ATTACK_BLAETTERSTURM, 
	// Kaumalat
	20000 + POKEMON_KAUMALAT, ATTACK_EISENSCHWEIF, ATTACK_BODYSLAM, ATTACK_FUCHTLER, ATTACK_WUTANFALL, ATTACK_GRIMASSE, ATTACK_FEUERODEM, ATTACK_KRAXLER, ATTACK_SANDGRAB, ATTACK_METALLKLAUE, ATTACK_LEHMSCHUSS, ATTACK_RISIKOTACKLE, ATTACK_WINDHOSE, 
	// Perlu
	20000 + POKEMON_PERLU, ATTACK_BODYSLAM, ATTACK_AUSDAUER, ATTACK_BARRIERE, ATTACK_LEHMSUHLER, ATTACK_LEHMBRUEHE, ATTACK_AQUAWELLE, ATTACK_HEILUNG, ATTACK_KONFUSTRAHL, ATTACK_SUPERSCHALL, 
	// Absol
	20000 + POKEMON_ABSOL, ATTACK_STAFETTE, ATTACK_ABGESANG, ATTACK_KNUDDLER, ATTACK_FINTE, ATTACK_VIELENDER, ATTACK_HORRORBLICK, ATTACK_MAGIEMANTEL, ATTACK_ZEN_KOPFSTOSS, ATTACK_TIEFSCHLAG, ATTACK_FLUCH, ATTACK_RISIKOTACKLE, 
	// Shuppet
	20000 + POKEMON_SHUPPET, ATTACK_GESICHTE, ATTACK_VERFOLGUNG, ATTACK_ERSTAUNER, ATTACK_ABGANGSBUND, ATTACK_SCHATTENSTOSS, ATTACK_BEGRENZER, ATTACK_AUSSETZER, ATTACK_KONFUSTRAHL, 
	// Vipitis
	20000 + POKEMON_VIPITIS, ATTACK_EISENSCHWEIF, ATTACK_BODYSLAM, ATTACK_VERZEHRER, ATTACK_HORTER, ATTACK_NACHTHIEB, ATTACK_GRIMASSE, ATTACK_ENTFESSLER, 
	// Sengo
	20000 + POKEMON_SENGO, ATTACK_AUSSETZER, ATTACK_BAUCHTROMMEL, 
	// Relicanth
	20000 + POKEMON_RELICANTH, ATTACK_SCHAEDELWUMME, ATTACK_NASSMACHER, ATTACK_SCHLAFREDE, ATTACK_SCHNARCHER, ATTACK_LEHMSCHELLE, ATTACK_LEHMBRUEHE, ATTACK_ZEN_KOPFSTOSS, ATTACK_INTENSITAET, ATTACK_LEHMSCHUSS, ATTACK_AMNESIE, 
	// Stollunior
	20000 + POKEMON_STOLLUNIOR, ATTACK_BODYSLAM, ATTACK_KRAFTKOLOSS, ATTACK_STAMPFER, ATTACK_RIECHSALZ, ATTACK_KREIDESCHREI, ATTACK_GEGENSCHLAG, ATTACK_FLUCH, ATTACK_NOTSITUATION, 
	// Formeo
	20000 + POKEMON_FORMEO, ATTACK_AUSSETZER, ATTACK_AMNESIE, ATTACK_SEHER, ATTACK_KOSMIK_KRAFT, 
	// Illumise
	20000 + POKEMON_ILLUMISE, ATTACK_AROMAKUR, 
	// Liliep
	20000 + POKEMON_LILIEP, ATTACK_SPIEGELCAPE, ATTACK_AUSDAUER, ATTACK_BARRIERE, ATTACK_GENESUNG, ATTACK_MEGASAUGER, ATTACK_SPASSKANONE, ATTACK_FLUCH, 
	// Anorith
	20000 + POKEMON_ANORITH, ATTACK_EISENABWEHR, ATTACK_SANDWIRBEL, ATTACK_ABSCHLAG, ATTACK_AQUAWELLE, ATTACK_KREIDESCHREI, ATTACK_FLUCH, ATTACK_WASSERDUESE, ATTACK_TURBODREHER, 
	// Trasla
	20000 + POKEMON_TRASLA, ATTACK_MEMENTO_MORI, ATTACK_NACHSPIEL, ATTACK_ZUGABE, ATTACK_HORRORBLICK, ATTACK_ABGANGSBUND, ATTACK_SCHATTENSTOSS, ATTACK_AUSSETZER, ATTACK_KONFUSTRAHL, 
	// Kindwurm
	20000 + POKEMON_KINDWURM, ATTACK_DRACHENTANZ, ATTACK_FUCHTLER, ATTACK_AUSDAUER, ATTACK_DRACHENWUT, ATTACK_HYDROPUMPE, ATTACK_FEUERZAHN, ATTACK_EINIGLER, ATTACK_WINDHOSE, ATTACK_DRACHENPULS, 
	// Palimpalim
	20000 + POKEMON_PALIMPALIM, ATTACK_ABGESANG, 
	0xFFFF
};

void _pokemon_get_egg_moves_stub(){
    derrf("Rom called old invalid stub for pokemon_get_egg_moves!\n");
}

u16 *pokemon_get_egg_moves(u16 species, int *size){
    // First find the proper table entry
    *size = 0;
    int i = 0;
    while(egg_moves[i] != 0xFFFF){
        if(egg_moves[i] >= 20000 && egg_moves[i] - 20000 == species)
            break;
        i++;
    }
    // If no match simply return null
    if(egg_moves[i] == 0xFFFF) return NULL;
    while(egg_moves[i + 1 + *size] < 20000)
        (*size)++;
    return &egg_moves[i + 1];
}