#ifndef TILE_INTERACTION_PC_H
#define TILE_INTERACTION_PC_H

#include "types.h"

enum {
    TILE_INTERACTION_PC_GENERIC_OFF = 0xA2,
    TILE_INTERACTION_PC_GENERIC_ON = 0xA6,
    TILE_INTERACTION_PC_POKESTOP_OFF = 0x28D,
    TILE_INTERACTION_PC_POKESTOP_ON = 0x294,
};

extern const u8 ow_script_pc[];

#endif // TILE_INTERACTION_PC_H