/*
 * communication.h
 *
 *  Created on: Feb 14, 2019
 *      Author: dominik
 */

#ifndef INCLUDE_C_BATTLE_COMMUNICATION_H_
#define INCLUDE_C_BATTLE_COMMUNICATION_H_

#define BATTLE_COMMUNICATION_MULTIUSE 0x0
#define BATTLE_COMMUNICATION_CURSOR_POSITION 1
#define BATTLE_COMMUNICATION_TASK_IDX 1
#define BATTLE_COMMUNICATION_SPRITES_INIT_STATE1 1
#define BATTLE_COMMUNICATION_SPRITES_INIT_STATE2 2
#define BATTLE_COMMUNICATION_MOVE_EFFECT_BYTE 3
#define BATTLE_COMMUNICATION_ACTIONS_CONFIRMED_COUNT 4
#define BATTLE_COMMUNICATION_MULTISTRING_CHOOSER 5
#define BATTLE_COMMUNICATION_MESSAGE_DISPLAY 7
#define BATTLE_COMMUNICATION_ENTRIES_COUNT 8

extern u8 battle_communication[9];

#endif /* INCLUDE_C_BATTLE_COMMUNICATION_H_ */
