#ifndef H_BASESTATS
#define H_BASESTATS

#include "types.h"
#include "pokemon.h"

#define SHAPE_BALL 12
#define SHAPE_SNAKE 3
#define SHAPE_FISH 11
#define SHAPE_ARMS 8
#define SHAPE_HEAD 7
#define SHAPE_TAIL 2
#define SHAPE_LEGS 9
#define SHAPE_ANIMAL 0
#define SHAPE_WINGED 5
#define SHAPE_TENTACLES 10
#define SHAPE_MULTI 13
#define SHAPE_HUMANOID 1
#define SHAPE_WINGED_INSECT 4
#define SHAPE_INSECT 6

#define TYPE_NORMAL 0
#define TYPE_FIGHTING 1
#define TYPE_FLYING 2
#define TYPE_POISON 3
#define TYPE_GROUND 4
#define TYPE_ROCK 5
#define TYPE_BUG 6
#define TYPE_GHOST 7
#define TYPE_STEEL 8
#define TYPE_FAIRY 9
#define TYPE_FIRE 10
#define TYPE_WATER 11
#define TYPE_GRASS 12
#define TYPE_ELECTRIC 13
#define TYPE_PSYCHIC 14
#define TYPE_ICE 15
#define TYPE_DRAGON 16
#define TYPE_DARK 17

#define EGG_GROUP_NONE 0
#define EGG_GROUP_MONSTER 1
#define EGG_GROUP_WATER_1 2
#define EGG_GROUP_BUG 3
#define EGG_GROUP_FLYING 4
#define EGG_GROUP_FIELD 5
#define EGG_GROUP_FAIRY 6
#define EGG_GROUP_GRASS 7
#define EGG_GROUP_HUMAN 8
#define EGG_GROUP_WATER_3 9
#define EGG_GROUP_MINERAL 10
#define EGG_GROUP_AMORPHUS 11
#define EGG_GROUP_WATER_2 12
#define EGG_GROUP_DITTO 13
#define EGG_GROUP_DRAGON 14
#define EGG_GROUP_UNDISCOVERED 15

#define POKEMON_POKEMON_0 0x0
#define POKEMON_BISASAM 0x1
#define POKEMON_BISAKNOSP 0x2
#define POKEMON_BISAFLOR 0x3
#define POKEMON_GLUMANDA 0x4
#define POKEMON_GLUTEXO 0x5
#define POKEMON_GLURAK 0x6
#define POKEMON_SCHIGGY 0x7
#define POKEMON_SCHILLOK 0x8
#define POKEMON_TURTOK 0x9
#define POKEMON_DARTIRI 0xa
#define POKEMON_DARTIGNIS 0xb
#define POKEMON_FIARO 0xc
#define POKEMON_HORNLIU 0xd
#define POKEMON_KOKUNA 0xe
#define POKEMON_BIBOR 0xf
#define POKEMON_STARALILI 0x10
#define POKEMON_STARAVIA 0x11
#define POKEMON_STARAPTOR 0x12
#define POKEMON_BRONZEL 0x13
#define POKEMON_BRONZONG 0x14
#define POKEMON_MAEHIKEL 0x15
#define POKEMON_CHEVRUMM 0x16
#define POKEMON_PARAGONI 0x17
#define POKEMON_TROMBORK 0x18
#define POKEMON_PIKACHU 0x19
#define POKEMON_RAICHU 0x1a
#define POKEMON_SANDAN 0x1b
#define POKEMON_SANDAMER 0x1c
#define POKEMON_NIDORANW 0x1d
#define POKEMON_NIDORINA 0x1e
#define POKEMON_NIDOQUEEN 0x1f
#define POKEMON_NIDORANM 0x20
#define POKEMON_NIDORINO 0x21
#define POKEMON_NIDOKING 0x22
#define POKEMON_FLOETTE 0x23
#define POKEMON_FLORGES 0x24
#define POKEMON_VULPIX 0x25
#define POKEMON_VULNONA 0x26
#define POKEMON_PUMMELUFF 0x27
#define POKEMON_KNUDDELUFF 0x28
#define POKEMON_ZUBAT 0x29
#define POKEMON_GOLBAT 0x2a
#define POKEMON_MYRAPLA 0x2b
#define POKEMON_DUFLOR 0x2c
#define POKEMON_GIFLOR 0x2d
#define POKEMON_FOLIPURBA 0x2e
#define POKEMON_FEELINARA 0x2f
#define POKEMON_WATTZAPF 0x30
#define POKEMON_VOLTULA 0x31
#define POKEMON_DIGDA 0x32
#define POKEMON_DIGDRI 0x33
#define POKEMON_KASTADUR 0x34
#define POKEMON_TENTANTEL 0x35
#define POKEMON_ENTON 0x36
#define POKEMON_ENTORON 0x37
#define POKEMON_MENKI 0x38
#define POKEMON_RASAFF 0x39
#define POKEMON_FUKANO 0x3a
#define POKEMON_ARKANI 0x3b
#define POKEMON_GRAMOKLES 0x3c
#define POKEMON_DUOKLES 0x3d
#define POKEMON_DURENGARD 0x3e
#define POKEMON_ABRA 0x3f
#define POKEMON_KADABRA 0x40
#define POKEMON_SIMSALA 0x41
#define POKEMON_MACHOLLO 0x42
#define POKEMON_MASCHOCK 0x43
#define POKEMON_MACHOMEI 0x44
#define POKEMON_KNOFENSA 0x45
#define POKEMON_ULTRIGARIA 0x46
#define POKEMON_SARZENIA 0x47
#define POKEMON_TENTACHA 0x48
#define POKEMON_TENTOXA 0x49
#define POKEMON_KLEINSTEIN 0x4a
#define POKEMON_GEOROK 0x4b
#define POKEMON_GEOWAZ 0x4c
#define POKEMON_PONITA 0x4d
#define POKEMON_GALLOPA 0x4e
#define POKEMON_FLEGMON 0x4f
#define POKEMON_LAHMUS 0x50
#define POKEMON_MAGNETILO 0x51
#define POKEMON_MAGNETON 0x52
#define POKEMON_PORENTA 0x53
#define POKEMON_DODU 0x54
#define POKEMON_DODRI 0x55
#define POKEMON_JURBO 0x56
#define POKEMON_JUGONG 0x57
#define POKEMON_SLEIMA 0x58
#define POKEMON_SLEIMOK 0x59
#define POKEMON_MUSCHAS 0x5a
#define POKEMON_AUSTOS 0x5b
#define POKEMON_NEBULAK 0x5c
#define POKEMON_ALPOLLO 0x5d
#define POKEMON_GENGAR 0x5e
#define POKEMON_ONIX 0x5f
#define POKEMON_TRAUMATO 0x60
#define POKEMON_HYPNO 0x61
#define POKEMON_KRABBY 0x62
#define POKEMON_KINGLER 0x63
#define POKEMON_VOLTOBAL 0x64
#define POKEMON_LEKTROBAL 0x65
#define POKEMON_OWEI 0x66
#define POKEMON_KOKOWEI 0x67
#define POKEMON_TRAGOSSO 0x68
#define POKEMON_KNOGGA 0x69
#define POKEMON_KICKLEE 0x6a
#define POKEMON_NOCKCHAN 0x6b
#define POKEMON_SCHLURP 0x6c
#define POKEMON_SMOGON 0x6d
#define POKEMON_SMOGMOG 0x6e
#define POKEMON_RIHORN 0x6f
#define POKEMON_RIZEROS 0x70
#define POKEMON_CHANEIRA 0x71
#define POKEMON_ZOBIRIS 0x72
#define POKEMON_KANGAMA 0x73
#define POKEMON_SEEPER 0x74
#define POKEMON_SEEMON 0x75
#define POKEMON_QUABBEL 0x76
#define POKEMON_APOQUALLYP 0x77
#define POKEMON_STERNDU 0x78
#define POKEMON_STARMIE 0x79
#define POKEMON_TRAUNFUGIL 0x7a
#define POKEMON_SICHLOR 0x7b
#define POKEMON_GALAGLADI 0x7c
#define POKEMON_ELEKTEK 0x7d
#define POKEMON_MAGMAR 0x7e
#define POKEMON_PINSIR 0x7f
#define POKEMON_TAUROS 0x80
#define POKEMON_KARPADOR 0x81
#define POKEMON_GARADOS 0x82
#define POKEMON_LAPRAS 0x83
#define POKEMON_DITTO 0x84
#define POKEMON_EVOLI 0x85
#define POKEMON_AQUANA 0x86
#define POKEMON_BLITZA 0x87
#define POKEMON_FLAMARA 0x88
#define POKEMON_PORYGON 0x89
#define POKEMON_AMONITAS 0x8a
#define POKEMON_AMOROSO 0x8b
#define POKEMON_KABUTO 0x8c
#define POKEMON_KABUTOPS 0x8d
#define POKEMON_AERODACTYL 0x8e
#define POKEMON_RELAXO 0x8f
#define POKEMON_ARKTOS 0x90
#define POKEMON_ZAPDOS 0x91
#define POKEMON_LAVADOS 0x92
#define POKEMON_DRATINI 0x93
#define POKEMON_DRAGONIR 0x94
#define POKEMON_DRAGORAN 0x95
#define POKEMON_MEWTU 0x96
#define POKEMON_MEW 0x97
#define POKEMON_ENDIVIE 0x98
#define POKEMON_LORBLATT 0x99
#define POKEMON_MEGANIE 0x9a
#define POKEMON_FEURIGEL 0x9b
#define POKEMON_IGELAVAR 0x9c
#define POKEMON_TORNUPTO 0x9d
#define POKEMON_KARNIMANI 0x9e
#define POKEMON_TYRACROC 0x9f
#define POKEMON_IMPERGATOR 0xa0
#define POKEMON_IGNIVOR 0xa1
#define POKEMON_RAMOTH 0xa2
#define POKEMON_GLAZIOLA 0xa3
#define POKEMON_RESLADERO 0xa4
#define POKEMON_LEDYBA 0xa5
#define POKEMON_LEDIAN 0xa6
#define POKEMON_WEBARAK 0xa7
#define POKEMON_ARIADOS 0xa8
#define POKEMON_IKSBAT 0xa9
#define POKEMON_LAMPI 0xaa
#define POKEMON_LANTURN 0xab
#define POKEMON_MAGNEZONE 0xac
#define POKEMON_TOGEKISS 0xad
#define POKEMON_FLABEBE 0xae
#define POKEMON_TOGEPI 0xaf
#define POKEMON_TOGETIC 0xb0
#define POKEMON_NATU 0xb1
#define POKEMON_XATU 0xb2
#define POKEMON_VOLTILAMM 0xb3
#define POKEMON_WAATY 0xb4
#define POKEMON_AMPHAROS 0xb5
#define POKEMON_BLUBELLA 0xb6
#define POKEMON_MARILL 0xb7
#define POKEMON_AZUMARILL 0xb8
#define POKEMON_MOGELBAUM 0xb9
#define POKEMON_CLAVION 0xba
#define POKEMON_LICHTEL 0xbb
#define POKEMON_LATERNECTO 0xbc
#define POKEMON_SKLELABRA 0xbd
#define POKEMON_GRIFFEL 0xbe
#define POKEMON_SHNEBEDECK 0xbf
#define POKEMON_REXBLISAR 0xc0
#define POKEMON_AMBIDIFFEL 0xc1
#define POKEMON_FELINO 0xc2
#define POKEMON_MORLORD 0xc3
#define POKEMON_PSIANA 0xc4
#define POKEMON_NACHTARA 0xc5
#define POKEMON_KRAMURX 0xc6
#define POKEMON_LASCHOKING 0xc7
#define POKEMON_KRAMSHEF 0xc8
#define POKEMON_ICOGNITO 0xc9
#define POKEMON_FROSDEDJE 0xca
#define POKEMON_SKORGRO 0xcb
#define POKEMON_TANNZA 0xcc
#define POKEMON_FORSTELLKA 0xcd
#define POKEMON_ELEVOLTEK 0xce
#define POKEMON_SKORGLA 0xcf
#define POKEMON_STAHLOS 0xd0
#define POKEMON_SNUBBULL 0xd1
#define POKEMON_GRANBULL 0xd2
#define POKEMON_MAMUTEL 0xd3
#define POKEMON_SCHEROX 0xd4
#define POKEMON_POTTROTT 0xd5
#define POKEMON_SKARABORN 0xd6
#define POKEMON_KRYPPUK 0xd7
#define POKEMON_TEDDIURSA 0xd8
#define POKEMON_URSARING 0xd9
#define POKEMON_SCHNECKMAG 0xda
#define POKEMON_MAGCARGO 0xdb
#define POKEMON_QUIEKEL 0xdc
#define POKEMON_KEIFEL 0xdd
#define POKEMON_CORASONN 0xde
#define POKEMON_REMORAID 0xdf
#define POKEMON_OCTILLERY 0xe0
#define POKEMON_BOTOGEL 0xe1
#define POKEMON_SCHLURPLEK 0xe2
#define POKEMON_PANZAERON 0xe3
#define POKEMON_HUNDUSTER 0xe4
#define POKEMON_HUNDEMON 0xe5
#define POKEMON_SEEDRAKING 0xe6
#define POKEMON_PHANPY 0xe7
#define POKEMON_DONPHAN 0xe8
#define POKEMON_PORYGON2 0xe9
#define POKEMON_VOLUMINAS 0xea
#define POKEMON_TRAUNMAGIL 0xeb
#define POKEMON_RABAUZ 0xec
#define POKEMON_KAPOERA 0xed
#define POKEMON_KUSSILLA 0xee
#define POKEMON_ELEKID 0xef
#define POKEMON_MAGBY 0xf0
#define POKEMON_MILTANK 0xf1
#define POKEMON_HEITEIRA 0xf2
#define POKEMON_RAIKOU 0xf3
#define POKEMON_ENTEI 0xf4
#define POKEMON_SUICUNE 0xf5
#define POKEMON_LARVITAR 0xf6
#define POKEMON_PUPITAR 0xf7
#define POKEMON_DESPOTAR 0xf8
#define POKEMON_LUGIA 0xf9
#define POKEMON_HO_OH 0xfa
#define POKEMON_CELEBI 0xfb
#define POKEMON_BISAFLORM 0xfc
#define POKEMON_GLURAKM 0xfd
#define POKEMON_AQUANAM 0xfe
#define POKEMON_BLITZAM 0xff
#define POKEMON_FLAMARM 0x100
#define POKEMON_DURENGARDA 0x101
#define POKEMON_IN 0x102
#define POKEMON_GAME 0x103
#define POKEMON_TURTOKM 0x104
#define POKEMON_AMPHARAOSM 0x105
#define POKEMON_GENGARM 0x106
#define POKEMON_BIBORM 0x107
#define POKEMON_ALTARIAM 0x108
#define POKEMON_GEOWAZM 0x109
#define POKEMON_SENGOM 0x10a
#define POKEMON_VIPITISM 0x10b
#define POKEMON_ZOBIRISM 0x10c
#define POKEMON_10d 0x10d
#define POKEMON_10e 0x10e
#define POKEMON_10f 0x10f
#define POKEMON_110 0x110
#define POKEMON_111 0x111
#define POKEMON_112 0x112
#define POKEMON_113 0x113
#define POKEMON_114 0x114
#define POKEMON_LOCKSCHAL 0x115
#define POKEMON_STICHSCHAL 0x116
#define POKEMON_STAHLSTICH 0x117
#define POKEMON_WELUNO 0x118
#define POKEMON_ORTHODOS 0x119
#define POKEMON_ZERBERTRES 0x11a
#define POKEMON_SEEKID 0x11b
#define POKEMON_SEESKULL 0x11c
#define POKEMON_SKULLYDRA 0x11d
#define POKEMON_FIFFYEN 0x11e
#define POKEMON_MAGNAYEN 0x11f
#define POKEMON_ZIGZACHS 0x120
#define POKEMON_GERADAKS 0x121
#define POKEMON_WAUMPEL 0x122
#define POKEMON_SCHALOKO 0x123
#define POKEMON_PAPINELLA 0x124
#define POKEMON_PANEKON 0x125
#define POKEMON_PUDOX 0x126
#define POKEMON_LOTURZEL 0x127
#define POKEMON_LOMBRERO 0x128
#define POKEMON_KAPPALORES 0x129
#define POKEMON_SAMURZEL 0x12a
#define POKEMON_BLANAS 0x12b
#define POKEMON_TENGULIST 0x12c
#define POKEMON_NINCADA 0x12d
#define POKEMON_NINJASK 0x12e
#define POKEMON_NINJATOM 0x12f
#define POKEMON_SCHWALBINI 0x130
#define POKEMON_SCHWALBOSS 0x131
#define POKEMON_KNILZ 0x132
#define POKEMON_KAPILZ 0x133
#define POKEMON_PANDIR 0x134
#define POKEMON_WINGULL 0x135
#define POKEMON_PELIPPER 0x136
#define POKEMON_GEHWEIHER 0x137
#define POKEMON_MASKEREGEN 0x138
#define POKEMON_WAILMER 0x139
#define POKEMON_WAILORD 0x13a
#define POKEMON_ENECO 0x13b
#define POKEMON_ENEKORO 0x13c
#define POKEMON_KECLEON 0x13d
#define POKEMON_PUPPANCE 0x13e
#define POKEMON_LEPUMENTAS 0x13f
#define POKEMON_NASGNET 0x140
#define POKEMON_MAGBRANT 0x141
#define POKEMON_ZWIRRFINST 0x142
#define POKEMON_SCHMERBE 0x143
#define POKEMON_WELSAR 0x144
#define POKEMON_LIEBISKUS 0x145
#define POKEMON_KREBSCORPS 0x146
#define POKEMON_KREBUTACK 0x147
#define POKEMON_BARSCHWA 0x148
#define POKEMON_MILOTIC 0x149
#define POKEMON_KANIVANHA 0x14a
#define POKEMON_TOHAIDO 0x14b
#define POKEMON_KNACKLION 0x14c
#define POKEMON_VIBRAVA 0x14d
#define POKEMON_LIBELLDRA 0x14e
#define POKEMON_RIOLU 0x14f
#define POKEMON_LUCARIO 0x150
#define POKEMON_FRIZELBLIZ 0x151
#define POKEMON_VOLTENSO 0x152
#define POKEMON_CAMAUB 0x153
#define POKEMON_CAMERUPT 0x154
#define POKEMON_SEEMOPS 0x155
#define POKEMON_SEEJONG 0x156
#define POKEMON_WALRAISA 0x157
#define POKEMON_TUSKA 0x158
#define POKEMON_NOKTUSKA 0x159
#define POKEMON_SCHNEPPKE 0x15a
#define POKEMON_FIRNONTOR 0x15b
#define POKEMON_LUNASTEIN 0x15c
#define POKEMON_SONNFEL 0x15d
#define POKEMON_AZURILL 0x15e
#define POKEMON_SPOINK 0x15f
#define POKEMON_GROINK 0x160
#define POKEMON_PLUSLE 0x161
#define POKEMON_MINUN 0x162
#define POKEMON_FLUNKIFER 0x163
#define POKEMON_MEDITIE 0x164
#define POKEMON_MEDITALIS 0x165
#define POKEMON_WABLU 0x166
#define POKEMON_ALTARIA 0x167
#define POKEMON_ISSO 0x168
#define POKEMON_ZWIRRLICHT 0x169
#define POKEMON_ZWIRRKLOP 0x16a
#define POKEMON_ROSELIA 0x16b
#define POKEMON_BUMMELZ 0x16c
#define POKEMON_MUNTIER 0x16d
#define POKEMON_LETARKING 0x16e
#define POKEMON_SCHLUPPUCK 0x16f
#define POKEMON_SCHLUKWECH 0x170
#define POKEMON_TROPIUS 0x171
#define POKEMON_KAUMALAT 0x172
#define POKEMON_KNARKSEL 0x173
#define POKEMON_KNAKRACK 0x174
#define POKEMON_PERLU 0x175
#define POKEMON_AALABYSS 0x176
#define POKEMON_SAGANABYSS 0x177
#define POKEMON_ABSOL 0x178
#define POKEMON_SHUPPET 0x179
#define POKEMON_BANETTE 0x17a
#define POKEMON_VIPITIS 0x17b
#define POKEMON_SENGO 0x17c
#define POKEMON_RELICANTH 0x17d
#define POKEMON_STOLLUNIOR 0x17e
#define POKEMON_STOLLRAK 0x17f
#define POKEMON_STOLLOSS 0x180
#define POKEMON_FORMEO 0x181
#define POKEMON_VOLBEAT 0x182
#define POKEMON_ILLUMISE 0x183
#define POKEMON_LILIEP 0x184
#define POKEMON_WIELIE 0x185
#define POKEMON_ANORITH 0x186
#define POKEMON_ARMALDO 0x187
#define POKEMON_TRASLA 0x188
#define POKEMON_KIRLIA 0x189
#define POKEMON_GUARDEVOIR 0x18a
#define POKEMON_KINDWURM 0x18b
#define POKEMON_DRASCHEL 0x18c
#define POKEMON_BRUTALANDA 0x18d
#define POKEMON_TANHEL 0x18e
#define POKEMON_METANG 0x18f
#define POKEMON_METAGROSS 0x190
#define POKEMON_REGIROCK 0x191
#define POKEMON_REGICE 0x192
#define POKEMON_REGISTEEL 0x193
#define POKEMON_KYOGRE 0x194
#define POKEMON_GROUDON 0x195
#define POKEMON_RAYQUAZA 0x196
#define POKEMON_LATIAS 0x197
#define POKEMON_LATIOS 0x198
#define POKEMON_JIRACHI 0x199
#define POKEMON_DEOXYS 0x19a
#define POKEMON_PALIMPALIM 0x19b
#define POKEMON_EGG 0x19C
#define POKEMON_ICOGNITO_B 0x19d
#define POKEMON_ICOGNITO_C 0x19e
#define POKEMON_ICOGNITO_D 0x19f
#define POKEMON_ICOGNITO_E 0x1a0
#define POKEMON_ICOGNITO_F 0x1a1
#define POKEMON_ICOGNITO_G 0x1a2
#define POKEMON_ICOGNITO_H 0x1a3
#define POKEMON_ICOGNITO_I 0x1a4
#define POKEMON_ICOGNITO_J 0x1a5
#define POKEMON_ICOGNITO_K 0x1a6
#define POKEMON_ICOGNITO_L 0x1a7
#define POKEMON_ICOGNITO_M 0x1a8
#define POKEMON_ICOGNITO_N 0x1a9
#define POKEMON_ICOGNITO_O 0x1aa
#define POKEMON_ICOGNITO_P 0x1ab
#define POKEMON_ICOGNITO_Q 0x1ac
#define POKEMON_ICOGNITO_R 0x1ad
#define POKEMON_ICOGNITO_S 0x1ae
#define POKEMON_ICOGNITO_T 0x1af
#define POKEMON_ICOGNITO_U 0x1b0
#define POKEMON_ICOGNITO_V 0x1b1
#define POKEMON_ICOGNITO_W 0x1b2
#define POKEMON_ICOGNITO_X 0x1b3
#define POKEMON_ICOGNITO_Y 0x1b4
#define POKEMON_ICOGNITO_Z 0x1b5
#define POKEMON_ICOGNITO_EXL 0x1B6
#define POKEMON_ICOGNITO_QUE 0x1B7
#define POKEMON_GROUDON_REGENT 0x1B8

typedef struct {
    u8 base_hp;
    u8 base_atk;
    u8 base_def;
    u8 base_speed;
    u8 base_satk;
    u8 base_sdef;
    u8 type1;
    u8 type2;
    u8 catch_rate;
    u8 exp_yield;

    struct {
        u16 hp : 2;
        u16 att : 2;
        u16 def : 2;
        u16 speed : 2;
        u16 satt : 2;
        u16 sdef : 2;
        u16 padding : 4;
    } ev_yield;
    u16 common_item;
    u16 rare_item;
    u8 gender_value;
    u8 egg_cycles;
    u8 base_happiness;
    u8 level_up_type;
    u8 egg_group_1;
    u8 egg_group_2;
    u8 ability1;
    u8 ability2;
    u8 safari_rate;
    u8 color_flip_field;
    u8 hidden_ability;
    u8 form;
} basestat;

typedef struct {
    u8 header[4];
    void *data;
    u8 vol_curve[4];
} pokemon_cry;

pokemon_cry pokemon_cries_forward[POKEMON_CNT];
pokemon_cry pokemon_cries_backward[POKEMON_CNT];
basestat basestats[POKEMON_CNT];
extern u8 pokemon_names[POKEMON_CNT][11];


extern u8 cry_661[];
extern u8 cry_662[];
extern u8 cry_663[];
extern u8 cry_396[];
extern u8 cry_397[];
extern u8 cry_398[];
extern u8 cry_436[];
extern u8 cry_437[];
extern u8 cry_672[];
extern u8 cry_673[];
extern u8 cry_708[];
extern u8 cry_709[];
extern u8 cry_669[];
extern u8 cry_670[];
extern u8 cry_671[];
extern u8 cry_470[];
extern u8 cry_700[];
extern u8 cry_595[];
extern u8 cry_596[];
extern u8 cry_597[];
extern u8 cry_598[];
extern u8 cry_679[];
extern u8 cry_680[];
extern u8 cry_681[];
extern u8 cry_302[];
extern u8 cry_592[];
extern u8 cry_593[];
extern u8 cry_200[];
extern u8 cry_475[];
extern u8 cry_636[];
extern u8 cry_637[];
extern u8 cry_471[];
extern u8 cry_701[];
extern u8 cry_462[];
extern u8 cry_468[];
extern u8 cry_707[];
extern u8 cry_607[];
extern u8 cry_608[];
extern u8 cry_609[];
extern u8 cry_459[];
extern u8 cry_460[];
extern u8 cry_424[];
extern u8 cry_430[];
extern u8 cry_478[];
extern u8 cry_472[];
extern u8 cry_466[];
extern u8 cry_473[];
extern u8 cry_442[];
extern u8 cry_463[];
extern u8 cry_476[];
extern u8 cry_429[];
extern u8 cry_467[];
extern u8 cry_477[];
extern u8 cry_447[];
extern u8 cry_448[];
extern u8 cry_443[];
extern u8 cry_444[];
extern u8 cry_445[];
extern u8 cry_115[];

#endif
