#ifndef H_ITEM
#define H_ITEM

#include "stdbool.h"

#define ITEM_NONE 0
#define ITEM_MEISTERBALL 0x1
#define ITEM_HYPERBALL 0x2
#define ITEM_SUPERBALL 0x3
#define ITEM_POKEBALL 0x4
#define ITEM_SAFARIBALL 0x5
#define ITEM_NETZBALL 0x6
#define ITEM_TAUCHBALL 0x7
#define ITEM_NESTBALL 0x8
#define ITEM_WIEDERBALL 0x9
#define ITEM_TIMERBALL 0xa
#define ITEM_LUXUSBALL 0xb
#define ITEM_PREMIERBALL 0xc
#define ITEM_TRANK 0xd
#define ITEM_GEGENGIFT 0xe
#define ITEM_FEUERHEILER 0xf
#define ITEM_EISHEILER 0x10
#define ITEM_AUFWECKER 0x11
#define ITEM_PARA_HEILER 0x12
#define ITEM_TOP_GENESUNG 0x13
#define ITEM_TOP_TRANK 0x14
#define ITEM_HYPERTRANK 0x15
#define ITEM_SUPERTRANK 0x16
#define ITEM_HYPERHEILER 0x17
#define ITEM_BELEBER 0x18
#define ITEM_TOP_BELEBER 0x19
#define ITEM_TAFELWASSER 0x1a
#define ITEM_SPRUDEL 0x1b
#define ITEM_LIMONADE 0x1c
#define ITEM_KUHMUH_MILCH 0x1d
#define ITEM_ENERGIESTAUB 0x1e
#define ITEM_KRAFTWURZEL 0x1f
#define ITEM_HEILPUDER 0x20
#define ITEM_VITALKRAUT 0x21
#define ITEM_AETHER 0x22
#define ITEM_TOP_AETHER 0x23
#define ITEM_ELIXIER 0x24
#define ITEM_TOP_ELIXIER 0x25
#define ITEM_LAVAKEKS 0x26
#define ITEM_BLAUE_FLOETE 0x27
#define ITEM_GELBE_FLOETE 0x28
#define ITEM_ROTE_FLOETE 0x29
#define ITEM_SCHW_FLOETE 0x2a
#define ITEM_WEISSE_FLOETE 0x2b
#define ITEM_BEERENSAFT 0x2c
#define ITEM_ZAUBERASCHE 0x2d
#define ITEM_KUESTENSALZ 0x2e
#define ITEM_KUESTENSCHALE 0x2f
#define ITEM_PURPURSTUECK 0x30
#define ITEM_INDIGOSTUECK 0x31
#define ITEM_GELBSTUECK 0x32
#define ITEM_GRUENSTUECK 0x33
#define ITEM_MAGMAISIERER 0x34
#define ITEM_STROMISIERER 0x35
#define ITEM_SCHOENSCHUPPE 0x36
#define ITEM_DUBIOSDISK 0x37
#define ITEM_DUESTERUMHANG 0x38
#define ITEM_SCHUETZER 0x39
#define ITEM_LEBEN_ORB 0x3a
#define ITEM_EVOLITH 0x3b
#define ITEM_ITEM_3C 0x3c
#define ITEM_ITEM_3D 0x3d
#define ITEM_ITEM_3E 0x3e
#define ITEM_KP_PLUS 0x3f
#define ITEM_PROTEIN 0x40
#define ITEM_EISEN 0x41
#define ITEM_CARBON 0x42
#define ITEM_KALZIUM 0x43
#define ITEM_SONDERBONBON 0x44
#define ITEM_AP_PLUS 0x45
#define ITEM_ZINK 0x46
#define ITEM_AP_TOP 0x47
#define ITEM_ITEM_48 0x48
#define ITEM_MEGABLOCK 0x49
#define ITEM_ANGRIFFPLUS 0x4a
#define ITEM_X_ANGRIFF 0x4b
#define ITEM_X_ABWEHR 0x4c
#define ITEM_X_TEMPO 0x4d
#define ITEM_X_TREFFER 0x4e
#define ITEM_X_SPEZIAL 0x4f
#define ITEM_POKEPUPPE 0x50
#define ITEM_ENECO_RUTE 0x51
#define ITEM_ITEM_52 0x52
#define ITEM_SUPERSCHUTZ 0x53
#define ITEM_TOP_SCHUTZ 0x54
#define ITEM_FLUCHTSEIL 0x55
#define ITEM_SCHUTZ 0x56
#define ITEM_ITEM_57 0x57
#define ITEM_ITEM_58 0x58
#define ITEM_ITEM_59 0x59
#define ITEM_ITEM_5A 0x5a
#define ITEM_ITEM_5B 0x5b
#define ITEM_ITEM_5C 0x5c
#define ITEM_SONNENSTEIN 0x5d
#define ITEM_MONDSTEIN 0x5e
#define ITEM_FEUERSTEIN 0x5f
#define ITEM_DONNERSTEIN 0x60
#define ITEM_WASSERSTEIN 0x61
#define ITEM_BLATTSTEIN 0x62
#define ITEM_LINKKABEL 0x63
#define ITEM_FINSTERSTEIN 0x64
#define ITEM_LEUCHTSTEIN 0x65
#define ITEM_FUNKELSTEIN 0x66
#define ITEM_MINIPILZ 0x67
#define ITEM_RIESENPILZ 0x68
#define ITEM_SPV_ORB_N 0x69
#define ITEM_PERLE 0x6a
#define ITEM_RIESENPERLE 0x6b
#define ITEM_STERNENSTAUB 0x6c
#define ITEM_STERNENSTUECK 0x6d
#define ITEM_NUGGET 0x6e
#define ITEM_HERZSCHUPPE 0x6f
#define ITEM_ANGR_ORB_P 0x70
#define ITEM_ANGR_ORB_N 0x71
#define ITEM_VERT_ORB_P 0x72
#define ITEM_VERT_ORB_N 0x73
#define ITEM_INIT_ORB_P 0x74
#define ITEM_INIT_ORB_N 0x75
#define ITEM_SPA_ORB_P 0x76
#define ITEM_SPA_ORB_N 0x77
#define ITEM_SPV_ORB_P 0x78
#define ITEM_79 0x79
#define ITEM_HAFENBRIEF 0x7a
#define ITEM_GLITZERBRIEF 0x7b
#define ITEM_EILBRIEF 0x7c
#define ITEM_WALDBRIEF 0x7d
#define ITEM_WELLENBRIEF 0x7e
#define ITEM_PERLENBRIEF 0x7f
#define ITEM_DUNKELBRIEF 0x80
#define ITEM_TROPENBRIEF 0x81
#define ITEM_TRAUMBRIEF 0x82
#define ITEM_EDELBRIEF 0x83
#define ITEM_RETROBRIEF 0x84
#define ITEM_AMRENABEERE 0x85
#define ITEM_MARONBEERE 0x86
#define ITEM_PIRSIFBEERE 0x87
#define ITEM_FRAGIABEERE 0x88
#define ITEM_WILBIRBEERE 0x89
#define ITEM_JONAGOBEERE 0x8a
#define ITEM_SINELBEERE 0x8b
#define ITEM_PERSIMBEERE 0x8c
#define ITEM_PRUNUSBEERE 0x8d
#define ITEM_TSITRUBEERE 0x8e
#define ITEM_GIEFEBEERE 0x8f
#define ITEM_WIKIBEERE 0x90
#define ITEM_MAGOBEERE 0x91
#define ITEM_GAUVEBEERE 0x92
#define ITEM_YAPABEERE 0x93
#define ITEM_HIMMIHBEERE 0x94
#define ITEM_MORBBEERE 0x95
#define ITEM_NANABBEERE 0x96
#define ITEM_NIRBEBEERE 0x97
#define ITEM_SANANABEERE 0x98
#define ITEM_GRANABEERE 0x99
#define ITEM_SETANGBEERE 0x9a
#define ITEM_QUALOTBEERE 0x9b
#define ITEM_HONMELBEERE 0x9c
#define ITEM_LABRUSBEERE 0x9d
#define ITEM_TAMOTBEERE 0x9e
#define ITEM_SAIMBEERE 0x9f
#define ITEM_MAGOSTBEERE 0xa0
#define ITEM_RABUTABEERE 0xa1
#define ITEM_TRONZIBEERE 0xa2
#define ITEM_KIWANBEERE 0xa3
#define ITEM_PALLMBEERE 0xa4
#define ITEM_WASMELBEERE 0xa5
#define ITEM_DURINBEERE 0xa6
#define ITEM_MYRTILBEERE 0xa7
#define ITEM_LYDZIBEERE 0xa8
#define ITEM_LINGANBEERE 0xa9
#define ITEM_SALKABEERE 0xaa
#define ITEM_TAHAYBEERE 0xab
#define ITEM_APIKOBEERE 0xac
#define ITEM_LANSATBEERE 0xad
#define ITEM_KRAMBOBEERE 0xae
#define ITEM_ENIGMABEERE 0xaf
#define ITEM_ITEM_B0 0xb0
#define ITEM_WAHLGLAS 0xb1
#define ITEM_WAHLSCHAL 0xb2
#define ITEM_BLENDPUDER 0xb3
#define ITEM_SCHLOHKRAUT 0xb4
#define ITEM_MACHOBAND 0xb5
#define ITEM_EP_TEILER 0xb6
#define ITEM_FLINKKLAUE 0xb7
#define ITEM_SANFTGLOCKE 0xb8
#define ITEM_MENTALKRAUT 0xb9
#define ITEM_WAHLBAND 0xba
#define ITEM_KING_STEIN 0xbb
#define ITEM_SILBERSTAUB 0xbc
#define ITEM_MUENZAMULETT 0xbd
#define ITEM_SCHUTZBAND 0xbe
#define ITEM_SEELENTAU 0xbf
#define ITEM_ABYSSZAHN 0xc0
#define ITEM_ABYSSPLATTE 0xc1
#define ITEM_RAUCHBALL 0xc2
#define ITEM_EWIGSTEIN 0xc3
#define ITEM_FOKUS_BAND 0xc4
#define ITEM_GLUECKS_EI 0xc5
#define ITEM_SCOPE_LINSE 0xc6
#define ITEM_METALLMANTEL 0xc7
#define ITEM_UEBERRESTE 0xc8
#define ITEM_DRACHENHAUT 0xc9
#define ITEM_KUGELBLITZ 0xca
#define ITEM_PUDERSAND 0xcb
#define ITEM_GRANITSTEIN 0xcc
#define ITEM_WUNDERSAAT 0xcd
#define ITEM_SCHATTENGLAS 0xce
#define ITEM_SCHWARZGURT 0xcf
#define ITEM_MAGNET 0xd0
#define ITEM_ZAUBERWASSER 0xd1
#define ITEM_HACKATTACK 0xd2
#define ITEM_GIFTSTICH 0xd3
#define ITEM_EWIGES_EIS 0xd4
#define ITEM_BANNSTICKER 0xd5
#define ITEM_KRUEMMLOEFFEL 0xd6
#define ITEM_HOLZKOHLE 0xd7
#define ITEM_DRACHENZAHN 0xd8
#define ITEM_SEIDENSCHAL 0xd9
#define ITEM_UP_GRADE 0xda
#define ITEM_SEEGESANG 0xdb
#define ITEM_SEERAUCH 0xdc
#define ITEM_LAXRAUCH 0xdd
#define ITEM_LUCKY_PUNCH 0xde
#define ITEM_METALLSTAUB 0xdf
#define ITEM_KAMPFKNOCHEN 0xe0
#define ITEM_LAUCHSTANGE 0xe1
#define ITEM_BISAFLORNIT 0xe2
#define ITEM_GLURAKNIT 0xe3
#define ITEM_TURTOKNIT 0xe4
#define ITEM_TERRASORNIT 0xe5
#define ITEM_ZERBERNIT 0xe6
#define ITEM_SKULLYDRANIT 0xe7
#define ITEM_AQUANANIT 0xe8
#define ITEM_FLAMARANIT 0xe9
#define ITEM_BLITZANIT 0xea
#define ITEM_AMPHAROSNIT 0xeb
#define ITEM_GENGARNIT 0xec
#define ITEM_BIBORNIT 0xed
#define ITEM_MAGMAHERZ 0xee
#define ITEM_ITEM_EF 0xef
#define ITEM_ITEM_F0 0xf0
#define ITEM_ITEM_F1 0xf1
#define ITEM_ITEM_F2 0xf2
#define ITEM_ITEM_F3 0xf3
#define ITEM_ITEM_F4 0xf4
#define ITEM_ITEM_F5 0xf5
#define ITEM_ITEM_F6 0xf6
#define ITEM_ITEM_F7 0xf7
#define ITEM_ITEM_F8 0xf8
#define ITEM_ITEM_F9 0xf9
#define ITEM_ITEM_FA 0xfa
#define ITEM_ITEM_FB 0xfb
#define ITEM_ITEM_FC 0xfc
#define ITEM_ITEM_FD 0xfd
#define ITEM_ROTER_SCHAL 0xfe
#define ITEM_BLAUER_SCHAL 0xff
#define ITEM_ROSA_SCHAL 0x100
#define ITEM_GRUENER_SCHAL 0x101
#define ITEM_GELBER_SCHAL 0x102
#define ITEM_EILRAD 0x103
#define ITEM_MUENZKORB 0x104
#define ITEM_DETEKTOR 0x105
#define ITEM_ANGEL 0x106
#define ITEM_PROFIANGEL 0x107
#define ITEM_SUPERANGEL 0x108
#define ITEM_BOOTSTICKET 0x109
#define ITEM_WETTB_KARTE 0x10a
#define ITEM_WOLKENHERZ 0x10b
#define ITEM_WAILMERKANNE 0x10c
#define ITEM_DEVON_WAREN 0x10d
#define ITEM_ASCHETASCHE 0x10e
#define ITEM_KELLEROEFFNER 0x10f
#define ITEM_KUNSTRAD 0x110
#define ITEM_BOX 0x111
#define ITEM_BRIEF 0x112
#define ITEM_AEON_TICKET 0x113
#define ITEM_SPIRITKERN 0x114
#define ITEM_BLAUE_KUGEL 0x115
#define ITEM_SCANNER 0x116
#define ITEM_WUESTENGLAS 0x117
#define ITEM_METEORIT 0x118
#define ITEM_K1_SCHLUESSEL 0x119
#define ITEM_K2_SCHLUESSEL 0x11a
#define ITEM_K4_SCHLUESSEL 0x11b
#define ITEM_K6_SCHLUESSEL 0x11c
#define ITEM_L_SCHLUESSEL 0x11d
#define ITEM_WURZELFOSSIL 0x11e
#define ITEM_KLAUENFOSSIL 0x11f
#define ITEM_DEVON_SCOPE 0x120
#define ITEM_TM01 0x121
#define ITEM_TM02 0x122
#define ITEM_TM03 0x123
#define ITEM_TM04 0x124
#define ITEM_TM05 0x125
#define ITEM_TM06 0x126
#define ITEM_TM07 0x127
#define ITEM_TM08 0x128
#define ITEM_TM09 0x129
#define ITEM_TM10 0x12a
#define ITEM_TM11 0x12b
#define ITEM_TM12 0x12c
#define ITEM_TM13 0x12d
#define ITEM_TM14 0x12e
#define ITEM_TM15 0x12f
#define ITEM_TM16 0x130
#define ITEM_TM17 0x131
#define ITEM_TM18 0x132
#define ITEM_TM19 0x133
#define ITEM_TM20 0x134
#define ITEM_TM21 0x135
#define ITEM_TM22 0x136
#define ITEM_TM23 0x137
#define ITEM_TM24 0x138
#define ITEM_TM25 0x139
#define ITEM_TM26 0x13a
#define ITEM_TM27 0x13b
#define ITEM_TM28 0x13c
#define ITEM_TM29 0x13d
#define ITEM_TM30 0x13e
#define ITEM_TM31 0x13f
#define ITEM_TM32 0x140
#define ITEM_TM33 0x141
#define ITEM_TM34 0x142
#define ITEM_TM35 0x143
#define ITEM_TM36 0x144
#define ITEM_TM37 0x145
#define ITEM_TM38 0x146
#define ITEM_TM39 0x147
#define ITEM_TM40 0x148
#define ITEM_TM41 0x149
#define ITEM_TM42 0x14a
#define ITEM_TM43 0x14b
#define ITEM_TM44 0x14c
#define ITEM_TM45 0x14d
#define ITEM_TM46 0x14e
#define ITEM_TM47 0x14f
#define ITEM_TM48 0x150
#define ITEM_TM49 0x151
#define ITEM_TM50 0x152
#define ITEM_VM01 0x153
#define ITEM_VM02 0x154
#define ITEM_VM03 0x155
#define ITEM_VM04 0x156
#define ITEM_VM05 0x157
#define ITEM_VM06 0x158
#define ITEM_VM07 0x159
#define ITEM_VM08 0x15a
#define ITEM_ITEM_15B 0x15b
#define ITEM_ITEM_15C 0x15c
#define ITEM_ZUGANGSKARTE 0x15d
#define ITEM_POKEFLOETE 0x15e
#define ITEM__OEFFNER 0x15f
#define ITEM_RAD_COUPON 0x160
#define ITEM_PKMCORDER 0x161
#define ITEM_ALTBERNSTEIN 0x162
#define ITEM_TUEROEFFNER 0x163
#define ITEM_LIFTOEFFNER 0x164
#define ITEM_HELIXFOSSIL 0x165
#define ITEM_DOMFOSSIL 0x166
#define ITEM_SILPH_SCOPE 0x167
#define ITEM_FAHRRAD 0x168
#define ITEM_KARTE 0x169
#define ITEM_KAMPFFAHNDER 0x16a
#define ITEM_RUHMESDATEI 0x16b
#define ITEM_VMTM_BOX 0x16c
#define ITEM_BEERENTUETE 0x16d
#define ITEM_LEHRKANAL 0x16e
#define ITEM_TRI_PASS 0x16f
#define ITEM_BUNT_PASS 0x170
#define ITEM_MEGA_AMULETT 0x171
#define ITEM_GEHEIMTICKET 0x172
#define ITEM_AURORATICKET 0x173
#define ITEM_PUDERDOESCHEN 0x174
#define ITEM_RUBIN 0x175
#define ITEM_SAPHIR 0x176

#define ITEM_CNT 0x177

#define POCKET_NONE 0
#define POCKET_ITEMS 1
#define POCKET_KEY_ITEMS 2
#define POCKET_POKEBALLS 3
#define POCKET_TM_HM 4
#define POCKET_BERRIES 5

typedef struct {
    u8 name[14];
    u16 index;
    u16 price;
    u8 holding_effect_id;
    u8 holding_effect_param;
    u8 *description_ptr;
    u16 field_18;
    u8 pocket;
    u8 type;
    void (*field_usage)(u8);
    void (*battle_usage_1)(u8);
    void (*battle_usage_2)(u8);
    void (*field_28)(u8);
} item;

typedef struct{
    u16 flag;
    u16 item;
}mart_item;

typedef struct{
    void (*end_callback)();
    u16 *item_list;
}mart_state;

item items[ITEM_CNT];

//item* items = (item*) 0x083DA518;
mart_state *mstate = (mart_state*)0x02039934;

void item_field_nature_stone(u8 self);
void item_ashbag_field(u8 self);

void item_nature_stone(u8 self, void (*failure_func)(u8));

bool script_cmd_x86_pokemart(void *script_state);

extern u8 str_item_desc_x0_item_none[];
extern u8 str_item_desc_x1_item_meisterball[];
extern u8 str_item_desc_x2_item_hyperball[];
extern u8 str_item_desc_x3_item_superball[];
extern u8 str_item_desc_x4_item_pokeball[];
extern u8 str_item_desc_x5_item_safariball[];
extern u8 str_item_desc_x6_item_netzball[];
extern u8 str_item_desc_x7_item_tauchball[];
extern u8 str_item_desc_x8_item_nestball[];
extern u8 str_item_desc_x9_item_wiederball[];
extern u8 str_item_desc_xa_item_timerball[];
extern u8 str_item_desc_xb_item_luxusball[];
extern u8 str_item_desc_xc_item_premierball[];
extern u8 str_item_desc_xd_item_trank[];
extern u8 str_item_desc_xe_item_gegengift[];
extern u8 str_item_desc_xf_item_feuerheiler[];
extern u8 str_item_desc_x10_item_eisheiler[];
extern u8 str_item_desc_x11_item_aufwecker[];
extern u8 str_item_desc_x12_item_para_heiler[];
extern u8 str_item_desc_x13_item_top_genesung[];
extern u8 str_item_desc_x14_item_top_trank[];
extern u8 str_item_desc_x15_item_hypertrank[];
extern u8 str_item_desc_x16_item_supertrank[];
extern u8 str_item_desc_x17_item_hyperheiler[];
extern u8 str_item_desc_x18_item_beleber[];
extern u8 str_item_desc_x19_item_top_beleber[];
extern u8 str_item_desc_x1a_item_tafelwasser[];
extern u8 str_item_desc_x1b_item_sprudel[];
extern u8 str_item_desc_x1c_item_limonade[];
extern u8 str_item_desc_x1d_item_kuhmuh_milch[];
extern u8 str_item_desc_x1e_item_energiestaub[];
extern u8 str_item_desc_x1f_item_kraftwurzel[];
extern u8 str_item_desc_x20_item_heilpuder[];
extern u8 str_item_desc_x21_item_vitalkraut[];
extern u8 str_item_desc_x22_item_aether[];
extern u8 str_item_desc_x23_item_top_aether[];
extern u8 str_item_desc_x24_item_elixier[];
extern u8 str_item_desc_x25_item_top_elixier[];
extern u8 str_item_desc_x26_item_lavakeks[];
extern u8 str_item_desc_x27_item_blaue_floete[];
extern u8 str_item_desc_x28_item_gelbe_floete[];
extern u8 str_item_desc_x29_item_rote_floete[];
extern u8 str_item_desc_x2a_item_schw_floete[];
extern u8 str_item_desc_x2b_item_weisse_floete[];
extern u8 str_item_desc_x2c_item_beerensaft[];
extern u8 str_item_desc_x2d_item_zauberasche[];
extern u8 str_item_desc_x2e_item_kuestensalz[];
extern u8 str_item_desc_x2f_item_kuestenschale[];
extern u8 str_item_desc_x30_item_purpurstueck[];
extern u8 str_item_desc_x31_item_indigostueck[];
extern u8 str_item_desc_x32_item_gelbstueck[];
extern u8 str_item_desc_x33_item_gruenstueck[];
extern u8 str_item_desc_x34_item_magmaisierer[];
extern u8 str_item_desc_x35_item_stromisierer[];
extern u8 str_item_desc_x36_item_schoenschuppe[];
extern u8 str_item_desc_x37_item_dubiosdisk[];
extern u8 str_item_desc_x38_item_duesterumhang[];
extern u8 str_item_desc_x39_item_schuetzer[];
extern u8 str_item_desc_x3a_item_leben_orb[];
extern u8 str_item_desc_x3b_item_evolith[];
extern u8 str_item_desc_x3c_item_item_3c[];
extern u8 str_item_desc_x3d_item_item_3d[];
extern u8 str_item_desc_x3e_item_item_3e[];
extern u8 str_item_desc_x3f_item_kp_plus[];
extern u8 str_item_desc_x40_item_protein[];
extern u8 str_item_desc_x41_item_eisen[];
extern u8 str_item_desc_x42_item_carbon[];
extern u8 str_item_desc_x43_item_kalzium[];
extern u8 str_item_desc_x44_item_sonderbonbon[];
extern u8 str_item_desc_x45_item_ap_plus[];
extern u8 str_item_desc_x46_item_zink[];
extern u8 str_item_desc_x47_item_ap_top[];
extern u8 str_item_desc_x48_item_item_48[];
extern u8 str_item_desc_x49_item_megablock[];
extern u8 str_item_desc_x4a_item_angriffplus[];
extern u8 str_item_desc_x4b_item_x_angriff[];
extern u8 str_item_desc_x4c_item_x_abwehr[];
extern u8 str_item_desc_x4d_item_x_tempo[];
extern u8 str_item_desc_x4e_item_x_treffer[];
extern u8 str_item_desc_x4f_item_x_spezial[];
extern u8 str_item_desc_x50_item_pokepuppe[];
extern u8 str_item_desc_x51_item_eneco_rute[];
extern u8 str_item_desc_x52_item_item_52[];
extern u8 str_item_desc_x53_item_superschutz[];
extern u8 str_item_desc_x54_item_top_schutz[];
extern u8 str_item_desc_x55_item_fluchtseil[];
extern u8 str_item_desc_x56_item_schutz[];
extern u8 str_item_desc_x57_item_item_57[];
extern u8 str_item_desc_x58_item_item_58[];
extern u8 str_item_desc_x59_item_item_59[];
extern u8 str_item_desc_x5a_item_item_5a[];
extern u8 str_item_desc_x5b_item_item_5b[];
extern u8 str_item_desc_x5c_item_item_5c[];
extern u8 str_item_desc_x5d_item_sonnenstein[];
extern u8 str_item_desc_x5e_item_mondstein[];
extern u8 str_item_desc_x5f_item_feuerstein[];
extern u8 str_item_desc_x60_item_donnerstein[];
extern u8 str_item_desc_x61_item_wasserstein[];
extern u8 str_item_desc_x62_item_blattstein[];
extern u8 str_item_desc_x63_item_linkkabel[];
extern u8 str_item_desc_x64_item_finsterstein[];
extern u8 str_item_desc_x65_item_leuchtstein[];
extern u8 str_item_desc_x66_item_funkelstein[];
extern u8 str_item_desc_x67_item_minipilz[];
extern u8 str_item_desc_x68_item_riesenpilz[];
extern u8 str_item_desc_x69_item_spv_orb_n[];
extern u8 str_item_desc_x6a_item_perle[];
extern u8 str_item_desc_x6b_item_riesenperle[];
extern u8 str_item_desc_x6c_item_sternenstaub[];
extern u8 str_item_desc_x6d_item_sternenstueck[];
extern u8 str_item_desc_x6e_item_nugget[];
extern u8 str_item_desc_x6f_item_herzschuppe[];
extern u8 str_item_desc_x70_item_angr_orb_p[];
extern u8 str_item_desc_x71_item_angr_orb_n[];
extern u8 str_item_desc_x72_item_vert_orb_p[];
extern u8 str_item_desc_x73_item_vert_orb_n[];
extern u8 str_item_desc_x74_item_init_orb_p[];
extern u8 str_item_desc_x75_item_init_orb_n[];
extern u8 str_item_desc_x76_item_spa_orb_p[];
extern u8 str_item_desc_x77_item_spa_orb_n[];
extern u8 str_item_desc_x78_item_spv_orb_p[];
extern u8 str_item_desc_x79_item_79[];
extern u8 str_item_desc_x7a_item_hafenbrief[];
extern u8 str_item_desc_x7b_item_glitzerbrief[];
extern u8 str_item_desc_x7c_item_eilbrief[];
extern u8 str_item_desc_x7d_item_waldbrief[];
extern u8 str_item_desc_x7e_item_wellenbrief[];
extern u8 str_item_desc_x7f_item_perlenbrief[];
extern u8 str_item_desc_x80_item_dunkelbrief[];
extern u8 str_item_desc_x81_item_tropenbrief[];
extern u8 str_item_desc_x82_item_traumbrief[];
extern u8 str_item_desc_x83_item_edelbrief[];
extern u8 str_item_desc_x84_item_retrobrief[];
extern u8 str_item_desc_x85_item_amrenabeere[];
extern u8 str_item_desc_x86_item_maronbeere[];
extern u8 str_item_desc_x87_item_pirsifbeere[];
extern u8 str_item_desc_x88_item_fragiabeere[];
extern u8 str_item_desc_x89_item_wilbirbeere[];
extern u8 str_item_desc_x8a_item_jonagobeere[];
extern u8 str_item_desc_x8b_item_sinelbeere[];
extern u8 str_item_desc_x8c_item_persimbeere[];
extern u8 str_item_desc_x8d_item_prunusbeere[];
extern u8 str_item_desc_x8e_item_tsitrubeere[];
extern u8 str_item_desc_x8f_item_giefebeere[];
extern u8 str_item_desc_x90_item_wikibeere[];
extern u8 str_item_desc_x91_item_magobeere[];
extern u8 str_item_desc_x92_item_gauvebeere[];
extern u8 str_item_desc_x93_item_yapabeere[];
extern u8 str_item_desc_x94_item_himmihbeere[];
extern u8 str_item_desc_x95_item_morbbeere[];
extern u8 str_item_desc_x96_item_nanabbeere[];
extern u8 str_item_desc_x97_item_nirbebeere[];
extern u8 str_item_desc_x98_item_sananabeere[];
extern u8 str_item_desc_x99_item_granabeere[];
extern u8 str_item_desc_x9a_item_setangbeere[];
extern u8 str_item_desc_x9b_item_qualotbeere[];
extern u8 str_item_desc_x9c_item_honmelbeere[];
extern u8 str_item_desc_x9d_item_labrusbeere[];
extern u8 str_item_desc_x9e_item_tamotbeere[];
extern u8 str_item_desc_x9f_item_saimbeere[];
extern u8 str_item_desc_xa0_item_magostbeere[];
extern u8 str_item_desc_xa1_item_rabutabeere[];
extern u8 str_item_desc_xa2_item_tronzibeere[];
extern u8 str_item_desc_xa3_item_kiwanbeere[];
extern u8 str_item_desc_xa4_item_pallmbeere[];
extern u8 str_item_desc_xa5_item_wasmelbeere[];
extern u8 str_item_desc_xa6_item_durinbeere[];
extern u8 str_item_desc_xa7_item_myrtilbeere[];
extern u8 str_item_desc_xa8_item_lydzibeere[];
extern u8 str_item_desc_xa9_item_linganbeere[];
extern u8 str_item_desc_xaa_item_salkabeere[];
extern u8 str_item_desc_xab_item_tahaybeere[];
extern u8 str_item_desc_xac_item_apikobeere[];
extern u8 str_item_desc_xad_item_lansatbeere[];
extern u8 str_item_desc_xae_item_krambobeere[];
extern u8 str_item_desc_xaf_item_enigmabeere[];
extern u8 str_item_desc_xb0_item_item_b0[];
extern u8 str_item_desc_xb1_item_wahlglas[];
extern u8 str_item_desc_xb2_item_wahlschal[];
extern u8 str_item_desc_xb3_item_blendpuder[];
extern u8 str_item_desc_xb4_item_schlohkraut[];
extern u8 str_item_desc_xb5_item_machoband[];
extern u8 str_item_desc_xb6_item_ep_teiler[];
extern u8 str_item_desc_xb7_item_flinkklaue[];
extern u8 str_item_desc_xb8_item_sanftglocke[];
extern u8 str_item_desc_xb9_item_mentalkraut[];
extern u8 str_item_desc_xba_item_wahlband[];
extern u8 str_item_desc_xbb_item_king_stein[];
extern u8 str_item_desc_xbc_item_silberstaub[];
extern u8 str_item_desc_xbd_item_muenzamulett[];
extern u8 str_item_desc_xbe_item_schutzband[];
extern u8 str_item_desc_xbf_item_seelentau[];
extern u8 str_item_desc_xc0_item_abysszahn[];
extern u8 str_item_desc_xc1_item_abyssplatte[];
extern u8 str_item_desc_xc2_item_rauchball[];
extern u8 str_item_desc_xc3_item_ewigstein[];
extern u8 str_item_desc_xc4_item_fokus_band[];
extern u8 str_item_desc_xc5_item_gluecks_ei[];
extern u8 str_item_desc_xc6_item_scope_linse[];
extern u8 str_item_desc_xc7_item_metallmantel[];
extern u8 str_item_desc_xc8_item_ueberreste[];
extern u8 str_item_desc_xc9_item_drachenhaut[];
extern u8 str_item_desc_xca_item_kugelblitz[];
extern u8 str_item_desc_xcb_item_pudersand[];
extern u8 str_item_desc_xcc_item_granitstein[];
extern u8 str_item_desc_xcd_item_wundersaat[];
extern u8 str_item_desc_xce_item_schattenglas[];
extern u8 str_item_desc_xcf_item_schwarzgurt[];
extern u8 str_item_desc_xd0_item_magnet[];
extern u8 str_item_desc_xd1_item_zauberwasser[];
extern u8 str_item_desc_xd2_item_hackattack[];
extern u8 str_item_desc_xd3_item_giftstich[];
extern u8 str_item_desc_xd4_item_ewiges_eis[];
extern u8 str_item_desc_xd5_item_bannsticker[];
extern u8 str_item_desc_xd6_item_kruemmloeffel[];
extern u8 str_item_desc_xd7_item_holzkohle[];
extern u8 str_item_desc_xd8_item_drachenzahn[];
extern u8 str_item_desc_xd9_item_seidenschal[];
extern u8 str_item_desc_xda_item_up_grade[];
extern u8 str_item_desc_xdb_item_seegesang[];
extern u8 str_item_desc_xdc_item_seerauch[];
extern u8 str_item_desc_xdd_item_laxrauch[];
extern u8 str_item_desc_xde_item_lucky_punch[];
extern u8 str_item_desc_xdf_item_metallstaub[];
extern u8 str_item_desc_xe0_item_kampfknochen[];
extern u8 str_item_desc_xe1_item_lauchstange[];
extern u8 str_item_desc_xe2_item_bisaflornit[];
extern u8 str_item_desc_xe3_item_gluraknit[];
extern u8 str_item_desc_xe4_item_turtoknit[];
extern u8 str_item_desc_xe5_item_terrasornit[];
extern u8 str_item_desc_xe6_item_zerbernit[];
extern u8 str_item_desc_xe7_item_skullydranit[];
extern u8 str_item_desc_xe8_item_aquananit[];
extern u8 str_item_desc_xe9_item_flamaranit[];
extern u8 str_item_desc_xea_item_blitzanit[];
extern u8 str_item_desc_xeb_item_ampharosnit[];
extern u8 str_item_desc_xec_item_gengarnit[];
extern u8 str_item_desc_xed_item_bibornit[];
extern u8 str_item_desc_xee_item_item_ee[];
extern u8 str_item_desc_xef_item_item_ef[];
extern u8 str_item_desc_xf0_item_item_f0[];
extern u8 str_item_desc_xf1_item_item_f1[];
extern u8 str_item_desc_xf2_item_item_f2[];
extern u8 str_item_desc_xf3_item_item_f3[];
extern u8 str_item_desc_xf4_item_item_f4[];
extern u8 str_item_desc_xf5_item_item_f5[];
extern u8 str_item_desc_xf6_item_item_f6[];
extern u8 str_item_desc_xf7_item_item_f7[];
extern u8 str_item_desc_xf8_item_item_f8[];
extern u8 str_item_desc_xf9_item_item_f9[];
extern u8 str_item_desc_xfa_item_item_fa[];
extern u8 str_item_desc_xfb_item_item_fb[];
extern u8 str_item_desc_xfc_item_item_fc[];
extern u8 str_item_desc_xfd_item_item_fd[];
extern u8 str_item_desc_xfe_item_roter_schal[];
extern u8 str_item_desc_xff_item_blauer_schal[];
extern u8 str_item_desc_x100_item_rosa_schal[];
extern u8 str_item_desc_x101_item_gruener_schal[];
extern u8 str_item_desc_x102_item_gelber_schal[];
extern u8 str_item_desc_x103_item_eilrad[];
extern u8 str_item_desc_x104_item_muenzkorb[];
extern u8 str_item_desc_x105_item_detektor[];
extern u8 str_item_desc_x106_item_angel[];
extern u8 str_item_desc_x107_item_profiangel[];
extern u8 str_item_desc_x108_item_superangel[];
extern u8 str_item_desc_x109_item_bootsticket[];
extern u8 str_item_desc_x10a_item_wettb_karte[];
extern u8 str_item_desc_x10b_item_item_10b[];
extern u8 str_item_desc_x10c_item_wailmerkanne[];
extern u8 str_item_desc_x10d_item_devon_waren[];
extern u8 str_item_desc_x10e_item_aschetasche[];
extern u8 str_item_desc_x10f_item_kelleroeffner[];
extern u8 str_item_desc_x110_item_kunstrad[];
extern u8 str_item_desc_x111_item_box[];
extern u8 str_item_desc_x112_item_brief[];
extern u8 str_item_desc_x113_item_aeon_ticket[];
extern u8 str_item_desc_x114_item_spiritkern[];
extern u8 str_item_desc_x115_item_blaue_kugel[];
extern u8 str_item_desc_x116_item_scanner[];
extern u8 str_item_desc_x117_item_wuestenglas[];
extern u8 str_item_desc_x118_item_meteorit[];
extern u8 str_item_desc_x119_item_k1_schluessel[];
extern u8 str_item_desc_x11a_item_k2_schluessel[];
extern u8 str_item_desc_x11b_item_k4_schluessel[];
extern u8 str_item_desc_x11c_item_k6_schluessel[];
extern u8 str_item_desc_x11d_item_l_schluessel[];
extern u8 str_item_desc_x11e_item_wurzelfossil[];
extern u8 str_item_desc_x11f_item_klauenfossil[];
extern u8 str_item_desc_x120_item_devon_scope[];
extern u8 str_item_desc_x121_item_tm01[];
extern u8 str_item_desc_x122_item_tm02[];
extern u8 str_item_desc_x123_item_tm03[];
extern u8 str_item_desc_x124_item_tm04[];
extern u8 str_item_desc_x125_item_tm05[];
extern u8 str_item_desc_x126_item_tm06[];
extern u8 str_item_desc_x127_item_tm07[];
extern u8 str_item_desc_x128_item_tm08[];
extern u8 str_item_desc_x129_item_tm09[];
extern u8 str_item_desc_x12a_item_tm10[];
extern u8 str_item_desc_x12b_item_tm11[];
extern u8 str_item_desc_x12c_item_tm12[];
extern u8 str_item_desc_x12d_item_tm13[];
extern u8 str_item_desc_x12e_item_tm14[];
extern u8 str_item_desc_x12f_item_tm15[];
extern u8 str_item_desc_x130_item_tm16[];
extern u8 str_item_desc_x131_item_tm17[];
extern u8 str_item_desc_x132_item_tm18[];
extern u8 str_item_desc_x133_item_tm19[];
extern u8 str_item_desc_x134_item_tm20[];
extern u8 str_item_desc_x135_item_tm21[];
extern u8 str_item_desc_x136_item_tm22[];
extern u8 str_item_desc_x137_item_tm23[];
extern u8 str_item_desc_x138_item_tm24[];
extern u8 str_item_desc_x139_item_tm25[];
extern u8 str_item_desc_x13a_item_tm26[];
extern u8 str_item_desc_x13b_item_tm27[];
extern u8 str_item_desc_x13c_item_tm28[];
extern u8 str_item_desc_x13d_item_tm29[];
extern u8 str_item_desc_x13e_item_tm30[];
extern u8 str_item_desc_x13f_item_tm31[];
extern u8 str_item_desc_x140_item_tm32[];
extern u8 str_item_desc_x141_item_tm33[];
extern u8 str_item_desc_x142_item_tm34[];
extern u8 str_item_desc_x143_item_tm35[];
extern u8 str_item_desc_x144_item_tm36[];
extern u8 str_item_desc_x145_item_tm37[];
extern u8 str_item_desc_x146_item_tm38[];
extern u8 str_item_desc_x147_item_tm39[];
extern u8 str_item_desc_x148_item_tm40[];
extern u8 str_item_desc_x149_item_tm41[];
extern u8 str_item_desc_x14a_item_tm42[];
extern u8 str_item_desc_x14b_item_tm43[];
extern u8 str_item_desc_x14c_item_tm44[];
extern u8 str_item_desc_x14d_item_tm45[];
extern u8 str_item_desc_x14e_item_tm46[];
extern u8 str_item_desc_x14f_item_tm47[];
extern u8 str_item_desc_x150_item_tm48[];
extern u8 str_item_desc_x151_item_tm49[];
extern u8 str_item_desc_x152_item_tm50[];
extern u8 str_item_desc_x153_item_vm01[];
extern u8 str_item_desc_x154_item_vm02[];
extern u8 str_item_desc_x155_item_vm03[];
extern u8 str_item_desc_x156_item_vm04[];
extern u8 str_item_desc_x157_item_vm05[];
extern u8 str_item_desc_x158_item_vm06[];
extern u8 str_item_desc_x159_item_vm07[];
extern u8 str_item_desc_x15a_item_vm08[];
extern u8 str_item_desc_x15b_item_item_15b[];
extern u8 str_item_desc_x15c_item_item_15c[];
extern u8 str_item_desc_x15d_item_eichs_paket[];
extern u8 str_item_desc_x15e_item_pokefloete[];
extern u8 str_item_desc_x15f_item__oeffner[];
extern u8 str_item_desc_x160_item_rad_coupon[];
extern u8 str_item_desc_x161_item_pkmcorder[];
extern u8 str_item_desc_x162_item_altbernstein[];
extern u8 str_item_desc_x163_item_tueroeffner[];
extern u8 str_item_desc_x164_item_liftoeffner[];
extern u8 str_item_desc_x165_item_helixfossil[];
extern u8 str_item_desc_x166_item_domfossil[];
extern u8 str_item_desc_x167_item_silph_scope[];
extern u8 str_item_desc_x168_item_fahrrad[];
extern u8 str_item_desc_x169_item_karte[];
extern u8 str_item_desc_x16a_item_kampffahnder[];
extern u8 str_item_desc_x16b_item_ruhmesdatei[];
extern u8 str_item_desc_x16c_item_vmtm_box[];
extern u8 str_item_desc_x16d_item_beerentuete[];
extern u8 str_item_desc_x16e_item_lehrkanal[];
extern u8 str_item_desc_x16f_item_tri_pass[];
extern u8 str_item_desc_x170_item_bunt_pass[];
extern u8 str_item_desc_x171_item_mega_amulett[];
extern u8 str_item_desc_x172_item_geheimticket[];
extern u8 str_item_desc_x173_item_auroraticket[];
extern u8 str_item_desc_x174_item_puderdoeschen[];
extern u8 str_item_desc_x175_item_rubin[];
extern u8 str_item_desc_x176_item_saphir[];

#endif