#include "types.h"
#include "map/wild_pokemon.h"

wild_pokemon_data wild_pokemon[] = {
  {
		.bank = 3, .map = 0,
		.grass = NULL,
		.water = &wild_pokemon_3_0_water,
		.other = NULL,
		.rod = &wild_pokemon_3_0_rod,
	},
	{
		.bank = 3, .map = 1,
		.grass = NULL,
		.water = &wild_pokemon_3_1_water,
		.other = NULL,
		.rod = &wild_pokemon_3_1_rod,
	},
	{
		.bank = 3, .map = 2,
		.grass = NULL,
		.water = &wild_pokemon_3_2_water,
		.other = NULL,
		.rod = &wild_pokemon_3_2_rod,
	},
	{
		.bank = 6, .map = 2,
		.grass = NULL,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 19,
		.grass = &wild_pokemon_3_19_grass,
		.water = NULL,
		.other = &wild_pokemon_3_19_other,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 76,
		.grass = &wild_pokemon_3_76_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 57,
		.grass = &wild_pokemon_3_57_grass,
		.water = &wild_pokemon_3_57_water,
		.other = &wild_pokemon_3_57_other,
		.rod = &wild_pokemon_3_57_rod,
	},
	{
		.bank = 3, .map = 72,
		.grass = NULL,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 41,
		.grass = &wild_pokemon_3_41_grass,
		.water = &wild_pokemon_3_41_water,
		.other = &wild_pokemon_3_41_other,
		.rod = &wild_pokemon_3_41_rod,
	},
	{
		.bank = 3, .map = 70,
		.grass = &wild_pokemon_3_70_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 15, .map = 0,
		.grass = &wild_pokemon_15_0_grass,
		.water = &wild_pokemon_15_0_water,
		.other = &wild_pokemon_15_0_other,
		.rod = &wild_pokemon_15_0_rod,
	},
	{
		.bank = 15, .map = 4,
		.grass = &wild_pokemon_15_4_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 3,
		.grass = NULL,
		.water = &wild_pokemon_3_3_water,
		.other = NULL,
		.rod = &wild_pokemon_3_3_rod,
	},
	{
		.bank = 1, .map = 0,
		.grass = &wild_pokemon_1_0_grass,
		.water = &wild_pokemon_1_0_water,
		.other = &wild_pokemon_1_0_other,
		.rod = &wild_pokemon_1_0_rod,
	},
	{
		.bank = 0, .map = 5,
		.grass = &wild_pokemon_0_5_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 0, .map = 6,
		.grass = &wild_pokemon_0_6_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 0, .map = 7,
		.grass = &wild_pokemon_0_7_grass,
		.water = &wild_pokemon_0_7_water,
		.other = NULL,
		.rod = &wild_pokemon_0_7_rod,
	},
	{
		.bank = 3, .map = 21,
		.grass = &wild_pokemon_3_21_grass,
		.water = NULL,
		.other = &wild_pokemon_3_21_other,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 67,
		.grass = &wild_pokemon_3_67_grass,
		.water = &wild_pokemon_3_67_water,
		.other = NULL,
		.rod = &wild_pokemon_3_67_rod,
	},
	{
		.bank = 3, .map = 74,
		.grass = &wild_pokemon_3_74_grass,
		.water = NULL,
		.other = &wild_pokemon_3_74_other,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 4,
		.grass = NULL,
		.water = &wild_pokemon_3_4_water,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 8, .map = 11,
		.grass = NULL,
		.water = &wild_pokemon_8_11_water,
		.other = NULL,
		.rod = &wild_pokemon_8_11_rod,
	},
	{
		.bank = 1, .map = 59,
		.grass = &wild_pokemon_1_59_grass,
		.water = &wild_pokemon_1_59_water,
		.other = NULL,
		.rod = &wild_pokemon_1_59_rod,
	},
	{
		.bank = 3, .map = 22,
		.grass = &wild_pokemon_3_22_grass,
		.water = &wild_pokemon_3_22_water,
		.other = &wild_pokemon_3_22_other,
		.rod = &wild_pokemon_3_22_rod,
	},
	{
		.bank = 16, .map = 3,
		.grass = &wild_pokemon_16_3_grass,
		.water = NULL,
		.other = NULL,
		.rod = &wild_pokemon_16_3_rod,
	},
	{
		.bank = 3, .map = 23,
		.grass = &wild_pokemon_3_23_grass,
		.water = NULL,
		.other = &wild_pokemon_3_23_other,
		.rod = NULL,
	},
	{
		.bank = 17, .map = 2,
		.grass = &wild_pokemon_17_2_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 5,
		.grass = NULL,
		.water = &wild_pokemon_3_5_water,
		.other = NULL,
		.rod = &wild_pokemon_3_5_rod,
	},
	{
		.bank = 3, .map = 24,
		.grass = NULL,
		.water = &wild_pokemon_3_24_water,
		.other = NULL,
		.rod = &wild_pokemon_3_24_rod,
	},
	{
		.bank = 18, .map = 2,
		.grass = &wild_pokemon_18_2_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 18, .map = 3,
		.grass = &wild_pokemon_18_3_grass,
		.water = NULL,
		.other = &wild_pokemon_18_3_other,
		.rod = NULL,
	},
	{
		.bank = 1, .map = 30,
		.grass = &wild_pokemon_1_30_grass,
		.water = NULL,
		.other = &wild_pokemon_1_30_other,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 6,
		.grass = NULL,
		.water = &wild_pokemon_3_6_water,
		.other = NULL,
		.rod = &wild_pokemon_3_6_rod,
	},
	{
		.bank = 0, .map = 12,
		.grass = &wild_pokemon_0_12_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 1, .map = 81,
		.grass = &wild_pokemon_1_81_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 1, .map = 82,
		.grass = &wild_pokemon_1_82_grass,
		.water = NULL,
		.other = &wild_pokemon_1_82_other,
		.rod = NULL,
	},
	{
		.bank = 1, .map = 126,
		.grass = &wild_pokemon_1_126_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
		.bank = 3, .map = 7,
		.grass = &wild_pokemon_3_7_grass,
		.water = NULL,
		.other = &wild_pokemon_3_7_other,
		.rod = NULL,
	},
	{
		.bank = 11, .map = 2,
		.grass = &wild_pokemon_11_2_route_2_east_clouds_grass,
		.water = NULL,
		.other = NULL,
		.rod = NULL,
	},
	{
	    .bank = 3, .map = 8,
	    .grass = &wild_pokemon_3_8_grass,
	    .water = &wild_pokemon_3_8_water,
	    .other = &wild_pokemon_3_8_other,
	    .rod = &wild_pokemon_3_8_rod,
	},
	{
		.bank = 3, .map = 9,
		.water = &wild_pokemon_laubdorf_water, .rod = &wild_pokemon_laubdorf_rod,
		.grass = NULL, .other = NULL
	},
	{
		.bank = 3, .map = 10,
		.water = &wild_pokemon_route_9_water, .rod = &wild_pokemon_route_9_rod,
		.grass = NULL, .other = NULL

	},
	{
		.bank = 13, .map = 0,
		.water = &wild_pokemon_route_9_water, .rod = &wild_pokemon_route_9_rod,
		.grass = NULL, .other = NULL

	},
	{
		.bank = 3, .map = 11,
		.water = &wild_pokemon_route_10_water, .rod = &wild_pokemon_route_10_rod,
		.grass = NULL, .other = NULL

	},
	{
		.bank = 14, .map = 0,
		.water = NULL, .rod = NULL,
		.grass = &wild_pokemon_route_10_clouds_grass, .other = NULL

	},
	{
	    .bank = 0xFF, .map = 0xFF, .field_2 = 0xFF, .field_3 = 0xFF,
	    .grass = NULL, .water = NULL, .other = NULL, .rod = NULL
	},
};
